### ISSUE TITLE
Can't install demo_toolbox.py 

### ISSUE THREAD

**Issue by nav1-code** [CorentinJ/Real-Time-Voice-Cloning#10]
I try to run python demo_toolbox.py <dataset_root> in give an error (see bellow), I also try to run  in cmd this C:\Python37\Scripts>pip install unicode, but it doesn't help. Can anybody help me?

C:\Users\admin\Desktop\Real-Time-Voice-Cloning-master> python demo_toolbox.py "C:\Users\admin\Desktop\Real-Time-Voice-Cloning-master\datasets_root"
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\admin\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 3, in <module>
    from synthesizer import inference as synthesizer
  File "C:\Users\admin\Desktop\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 2, in <module>
    from synthesizer.synthesizer import Synthesizer
  File "C:\Users\admin\Desktop\Real-Time-Voice-Cloning-master\synthesizer\synthesizer.py", line 1, in <module>
    from synthesizer.utils.text import text_to_sequence
  File "C:\Users\admin\Desktop\Real-Time-Voice-Cloning-master\synthesizer\utils\text.py", line 2, in <module>
    from . import cleaners
  File "C:\Users\admin\Desktop\Real-Time-Voice-Cloning-master\synthesizer\utils\cleaners.py", line 14, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'

**Comment by CorentinJ** [comment]
The package is `Unidecode`, not unicode. It's only been added with a recent PR. Pull the repo and install the requirements again.

**Comment by nav1-code** [comment]
I followed your directions, and I've got an error (see below). I understand something is related with dataset. How do I properly configure dataset, because before I tried to download VoxCeleb1 and VoxCeleb2 I couldn't, it asked me some authentication and just I skipped this step.

PS: How do I train for other languages, not English, where I can get the data set, or how can I do it?

C:\Users\admin\Downloads\Real-Time-Voice-Cloning>python demo_toolbox.py "C:\User
s\admin\Downloads\Real-Time-Voice-Cloning\dataset_root"
WARNING: Logging before flag parsing goes to stderr.
W0619 00:22:47.159650  5648 deprecation_wrapper.py:118] From C:\Users\admin\Down
loads\Real-Time-Voice-Cloning\synthesizer\models\modules.py:91: The name tf.nn.r
nn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Arguments:
    datasets_root:    C:\Users\admin\Downloads\Real-Time-Voice-Cloning\dataset_root
        enc_models_dir:   encoder\saved_models
        syn_models_dir:   synthesizer\saved_models
        voc_models_dir:   vocoder\saved_models

Traceback (most recent call last):
  File "demo_toolbox.py", line 28, in <module>
    Toolbox(**vars(args))
  File "C:\Users\admin\Downloads\Real-Time-Voice-Cloning\toolbox\__init__.py", line 39, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir)
  File "C:\Users\admin\Downloads\Real-Time-Voice-Cloning\toolbox\__init__.py", line 85, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_
models_dir)
  File "C:\Users\admin\Downloads\Real-Time-Voice-Cloning\toolbox\ui.py", line 26
9, in populate_models
    raise Exception("No encoder models found in %s" % encoder_models_dir)
Exception: No encoder models found in encoder\saved_models

**Comment by CorentinJ** [comment]
You have not downloaded the pretrained models. Look for them in the readme. Don't worry, you can run the toolbox without datasets first. What is your native language?

**Comment by nav1-code** [comment]
roman, but about pretrained models I've got downloaded before, what I did wrong?

**Comment by CorentinJ** [comment]
You have to merge the pretrained models with the root of the repo. I think you put them in the wrong place. In the same folder you have `demo_toolbox.py` you should have the directory `encoder`, then `saved_models` under it and finally `pretrained.pt` under that. Right now, you don't have `pretrained.pt` there and that's causing the error.

As for retraining in Romanian, I think that's going to be difficult unless you find a good Romanian dataset. Even then that's a lot of work to interface the dataset with the project.

**Comment by nav1-code** [comment]
Could you suggest me some pre-trained reference of Romanian dataset source? or in other words, from what I should start?

**Comment by CorentinJ** [comment]
No, I don't know about any substantial one. [M-AILABS](https://www.caito.de/2019/01/the-m-ailabs-speech-dataset/) doesn't have any Romanian, and the only one I found is [SWARA](https://speech.utcluj.ro/swarasc/) which is way too small to do anything. Sorry.

**Comment by nav1-code** [comment]
the last question if I have some records (romaine) can I use them to train the speech?

**Comment by CorentinJ** [comment]
You would need hundreds of hours, and you need the text that comes with that data.

**Comment by daciansolgen3** [comment]
File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\dacia\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\dacia\Desktop\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 2, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "C:\Users\dacia\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "C:\Users\dacia\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_qt5.py", line 13, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\dacia\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "C:\Users\dacia\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\qt_compat.py", line 179, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
PS C:\Users\dacia\Desktop\Real-Time-Voice-Cloning-master>
