### ISSUE TITLE
Missing "PyQt5.QtCore"

### ISSUE THREAD

**Issue by LaxdalGe** [CorentinJ/Real-Time-Voice-Cloning#1044]
I tried to run the progrem and run into this error

Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
  File "E:\voice clone\toolbox\__init__.py", line 11, in <module>
    from toolbox.ui import UI
  File "E:\voice clone\toolbox\ui.py", line 12, in <module>
    from PyQt5.QtCore import Qt, QStringListModel
ModuleNotFoundError: No module named 'PyQt5.QtCore'

i tried pip install this missing file but:

ERROR: Could not find a version that satisfies the requirement PyQt5.QtCore (from versions: none)
ERROR: No matching distribution found for PyQt5.QtCore

**Comment by R1314** [comment]
I solved using this:
1)
sudo apt install pyqt5-dev-tools pyqt5-dev

https://stackoverflow.com/questions/57512730/cannot-install-pyqt5-tools-could-not-find-a-version-that-satisfies-the-requir

2) 
pip install pyqt5-sip==12.9.0

let me know, I got the same issue but its just module problems

**Comment by LaxdalGe** [comment]
it worked, thank you😊
