### ISSUE TITLE
No module named scipy.interpolate... and others

### ISSUE THREAD

**Issue by crackedeggs1** [CorentinJ/Real-Time-Voice-Cloning#1058]
python demo_toolbox.py

Traceback (most recent call last):
  File "[path]\demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
  File "[path]toolbox\__init__.py", line 9, in <module>
    from encoder import inference as encoder
  File "[path]\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "[path]\encoder\model.py", line 3, in <module>
    from scipy.interpolate import interp1d
ModuleNotFoundError: No module named 'scipy.interpolate'

pip install scipy==1.7.3
Requirement already satisfied: scipy==1.7.3 in [path]
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in [path] (1.20.3)

pip uninstall scipy
pip install scipy

Once installed (1.8.0), the scipy.interpolate error disappears. This suggests the requirements.txt is incorrect and that the minimum scipy version required is 1.8.0.

However, after fixing this, I now have another import error:

Traceback (most recent call last):
  File "[path]\demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
  File "[path]\toolbox\__init__.py", line 9, in <module>
    from encoder import inference as encoder
  File "[path]\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "[path]\model.py", line 4, in <module>
    from sklearn.metrics import roc_curve
ImportError: cannot import name 'roc_curve' from 'sklearn.metrics'

Not sure how to fix this one.

**Comment by raccoonML** [comment]
Which version of python are you using? It should be 3.6 or 3.7 at least.

**Comment by TrycsPublic** [comment]
Use python3.9.8

**Comment by TrycsPublic** [comment]
did you follow the instructions?
pip install -r requirements.txt

**Comment by crackedeggs1** [comment]
As implied in the first post, I did pip install -r requirements.txt, which installs scipy==1.7.3. That version causes this error. scipy 1.8.0+ is required. I eventually got past the second error but I don't remember what other dependencies I had to change. I eventually gave up on using AI for my project after several days.

**Comment by TrycsPublic** [comment]
Check python version, please install python3.8.9 uninstall script and install the latest version.
