### ISSUE TITLE
ImportError: No module named seq2seq

### ISSUE THREAD

**Issue by GamingTwist** [CorentinJ/Real-Time-Voice-Cloning#106]
I'm getting this error when try to execute demo_cli.py.
I have all the requirements installed.

Error:
`C:\Real-Time-Voice-Cloning-master>python demo_cli.py
Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 4, in <module>
    from synthesizer.models.helpers import TacoTrainingHelper, TacoTestHelper
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\models\helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
ModuleNotFoundError: No module named 'tensorflow.contrib'` 

I've seen some solutions and it involves changing the code but I don't see why I need to if the program works fine normally.

**Comment by GamingTwist** [comment]
Fixed. I worked out the install was wrong. Still need to set up CUDA tho but least the program is starting
