### ISSUE TITLE
Failed to interpret file as a pickle

### ISSUE THREAD

**Issue by Exocamp** [CorentinJ/Real-Time-Voice-Cloning#107]
Hello.

I am trying to create a custom voice dataset and feed it into the encoder training. When I try to run the training, however, I recieve this error:

Traceback (most recent call last):
  File "encoder_train.py", line 46, in <module>
    train(**vars(args))
  File "D:\Real-Time-Voice-Cloning-master\encoder\train.py", line 68, in train
    for step, speaker_batch in enumerate(loader, init_step):
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "D:\anaconda\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\numpy\lib\npyio.py", line 447, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: unpickling stack underflow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\Real-Time-Voice-Cloning-master\encoder\data_objects\speaker_verification_dataset.py", line 55, in collate
    return SpeakerBatch(speakers, self.utterances_per_speaker, partials_n_frames)
  File "D:\Real-Time-Voice-Cloning-master\encoder\data_objects\speaker_batch.py", line 8, in __init__
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "D:\Real-Time-Voice-Cloning-master\encoder\data_objects\speaker_batch.py", line 8, in <dictcomp>
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "D:\Real-Time-Voice-Cloning-master\encoder\data_objects\speaker.py", line 38, in random_partial
    a = [(u,) + u.random_partial(n_frames) for u in utterances]
  File "D:\Real-Time-Voice-Cloning-master\encoder\data_objects\speaker.py", line 38, in <listcomp>
    a = [(u,) + u.random_partial(n_frames) for u in utterances]
  File "D:\Real-Time-Voice-Cloning-master\encoder\data_objects\utterance.py", line 20, in random_partial
    frames = self.get_frames()
  File "D:\Real-Time-Voice-Cloning-master\encoder\data_objects\utterance.py", line 10, in get_frames
    return np.load(self.frames_fpath)
  File "D:\anaconda\lib\site-packages\numpy\lib\npyio.py", line 450, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file WindowsPath('D:/Voice_Datasets/Neptune_HD/00014402e.wav') as a pickle

Could anyone help me on how to solve this error? I am new to Python, so I may be missing something. Thank you.

**Comment by raanubis** [comment]
empty file/folder?

**Comment by Exocamp** [comment]
I tried that, and no empty directories. I also then tried other methods of formatting my data source, but whenever I do that, I get a RandomCycler error like this one:

Traceback (most recent call last):
  File "encoder_train.py", line 46, in <module>
    train(**vars(args))
  File "D:\real-time-voice-cloning-master\encoder\train.py", line 68, in train
    for step, speaker_batch in enumerate(loader, init_step):
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "D:\anaconda\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
Exception: Caught Exception in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\real-time-voice-cloning-master\encoder\data_objects\speaker_verification_dataset.py", line 55, in collate
    return SpeakerBatch(speakers, self.utterances_per_speaker, partials_n_frames)
  File "D:\real-time-voice-cloning-master\encoder\data_objects\speaker_batch.py", line 8, in __init__
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "D:\real-time-voice-cloning-master\encoder\data_objects\speaker_batch.py", line 8, in <dictcomp>
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "D:\real-time-voice-cloning-master\encoder\data_objects\speaker.py", line 34, in random_partial
    self._load_utterances()
  File "D:\real-time-voice-cloning-master\encoder\data_objects\speaker.py", line 18, in _load_utterances
    self.utterance_cycler = RandomCycler(self.utterances)
  File "D:\real-time-voice-cloning-master\encoder\data_objects\random_cycler.py", line 14, in __init__
    raise Exception("Can't create RandomCycler from an empty collection")
Exception: Can't create RandomCycler from an empty collection

I do know there is an issue with this error already, but I am not sure what the author meant when he found an 'illegal speaker folder', nor could I find anything that seemed to be illegal. Thanks again for your help.

**Comment by raanubis** [comment]
Do you also checked the folder where are the npy files are located?

I'm using the command "python C:\work\Real-Time-Voice-CloningML\encoder_train.py myLang C:\work\zTraindata\encoder -m C:\work\zTraindata\saved_models"

In the folder "C:\work\zTraindata\encoder" the npy files are stored.

Check if one of this folder is empty.

**Comment by Exocamp** [comment]
Thank you so much for all your help, I'm now doing the command the way you're doing it, but I now have this:

Traceback (most recent call last):
  File "encoder_train.py", line 46, in <module>
    train(**vars(args))
  File "D:\real-time-voice-cloning-master\encoder\train.py", line 61, in train
    vis.log_dataset(dataset)
  File "D:\real-time-voice-cloning-master\encoder\visualizations.py", line 85, in log_dataset
    dataset_string += "\n" + dataset.get_logs()
  File "D:\real-time-voice-cloning-master\encoder\data_objects\speaker_verification_dataset.py", line 29, in get_logs
    with log_fpath.open("r") as log_file:
  File "D:\anaconda\lib\pathlib.py", line 1193, in open
    opener=self._opener)
  File "D:\anaconda\lib\pathlib.py", line 1046, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'D:\\Voice_Datasets\\SV2TTS\\encoder\\project__sources.txt'
(base) PS D:\real-time-voice-cloning-master>

I realize this is a bit off from the main topic at this point, so if it needs to be closed I understand. I looked this up, and it might be a Windows problem or an Anaconda problem, which I use, but I don't know. Would you know anything about issues with this? Searching the issues here doesn't bring up anything.

Thanks a lot.

**Comment by Exocamp** [comment]
I fixed the issue by running the script in a virtualenv. Unless I need something else, I think I'm good now. Thank you for all your help.
