### ISSUE TITLE
synthesizer preprocess embeds error

### ISSUE THREAD

**Issue by TrycsPublic** [CorentinJ/Real-Time-Voice-Cloning#1074]
encoder model fpath:
saved models/default/encoder.pt
n processes:
16
Embedding:
0%
Embedding:
0%
10/112972 [00:54<?, ?utterances/sl
multiprocessing.pool.RemoteTraceback:
Traceback (most recent call last) :
File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args,
**kwds))
File "/home/ubuntu/run/synthesizer/preprocess.py",
line 231, in embed utterance
encoder.load _model(encoder_model_fpath)
File
"/home/ubuntu/run/encoder/inference.py", line 33, in load model
model.load_ state _dict (checkpoint [ "model state" ])
File
"/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py"
line 1497, in load state dict
raise RuntimeError ('Error(s) in loading state dict for (}: \n\t(}' .format (
RuntimeError: Error(s) in loading state dict for SpeakerEncoder:
Missing key(s) in state dict:
"Istm.weight ih 13", "Istm.weight hh 13", "Istm.bias in 13",
"Istm.bias ih 14"
"Istm.bias hh 14"
"Istm.bias hh 13",
"Istm.weight ih 14",
"Istm.weight hh_l
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "synthesizer preprocess embeds.py", line 25, in <module>
create embeddings (**vars (args) )

—
File "/us/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func (*args, **kwds))
File
"/home/ubuntu/run/synthesizer/preprocess.py",
line 231, in embed utterance
encoder.load model(encoder model fpath)
File "/home/ubuntu/run/encoder/inference.py", line 33, in load model
model.load state dict (checkpoint [ "model state" ])
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py",line1497, in load state dict
raise RuntimeError ('Error(s) in loading state dict for (: \n\t(}'. format (
RuntimeError: Error(s) in loading state dict for SpeakerEncoder:
Missing key(s) in state dict: "Istm.weight ih 13",
"Istm.weight hh 13",
"Istm.bias ih 14",
"1stm.bias hh_14"
"Istm.bias ih 13"
"]stm.bias hh 13"
"Istm.weight ih 14",
"Istm.weight hh l
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "synthesizer preprocess embeds.py", line 25, in <module>
create embeddings (**vars (args) )
File
"/home/ubuntu/run/synthesizer/preprocess.py", line 257, in create embeddings
list (tqdm(job,
"Embedding", len(fpaths), unit="utterances") )
File
"/usr/local/lib/python3.8/dist-packages/tqdm/std.py",line1180,in
_iter
for obj in iterable:
File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
raise value
RuntimeError: Error(s) in loading state dict for SpeakerEncoder:
Missing key(s) in state _dict:
"Istm.weight ih 13"
"Istm.weight hh l3", "lstm.bias ih l3", "lstm.bias hh 13", "lstm.weight ih 14",
"Istm.weight hh l

**Comment by TrycsPublic** [comment]
misconfiguration is 2 locals
