### ISSUE TITLE
Please help with "ModuleNotFoundError"!

### ISSUE THREAD

**Issue by rgsaura** [CorentinJ/Real-Time-Voice-Cloning#1078]
Getting this error:

_C:\Users\rodri\Downloads\Real-Time-Voice-Cloning-master>python demo_cli.py
Traceback (most recent call last):
  File "demo_cli.py", line 2, in <module>
    from utils.argutils import print_args
  File "C:\Users\rodri\Downloads\Real-Time-Voice-Cloning-master\utils\argutils.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

C:\Users\rodri\Downloads\Real-Time-Voice-Cloning-master>
C:\Users\rodri\Downloads\Real-Time-Voice-Cloning-master>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\rodri\Downloads\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\rodri\Downloads\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

C:\Users\rodri\Downloads\Real-Time-Voice-Cloning-master>
C:\Users\rodri\Downloads\Real-Time-Voice-Cloning-master>python demo_cli.py
Traceback (most recent call last):
  File "demo_cli.py", line 2, in <module>
    from utils.argutils import print_args
  File "C:\Users\rodri\Downloads\Real-Time-Voice-Cloning-master\utils\argutils.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'_

**Comment by rgsaura** [comment]
> pip install numpy

I tried but its not working 😢. I also did "pip install matplotlib" but it gave me the same reply as in "Requirement already satisfied". Any Ideas?

D:\Google Drive\EXOMENTUM\BAÚLES\INVENTARIO Y HERRAMIENTAS\Real-Time-Voice-Cloning-master>pip install numpy
Requirement already satisfied: numpy in c:\users\rodri\appdata\local\programs\python\python36\lib\site-packages (1.19.3)

D:\Google Drive\EXOMENTUM\BAÚLES\INVENTARIO Y HERRAMIENTAS\Real-Time-Voice-Cloning-master>python demo_cli.py
Traceback (most recent call last):
  File "demo_cli.py", line 2, in <module>
    from utils.argutils import print_args
  File "D:\Google Drive\EXOMENTUM\BAÚLES\INVENTARIO Y HERRAMIENTAS\Real-Time-Voice-Cloning-master\utils\argutils.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

D:\Google Drive\EXOMENTUM\BAÚLES\INVENTARIO Y HERRAMIENTAS\Real-Time-Voice-Cloning-master>

**Comment by TrycsPublic** [comment]
pip install numpy==1.21.0

do pip uninstall first.

**Comment by rgsaura** [comment]
So thankful for your replys. I got a problem installing version 1.21.0 but it seems it doesnt find it, i tried "pip install numpy" after the uninstall but i get the same problem :/

D:\Google Drive\EXOMENTUM\BAÚLES\INVENTARIO Y HERRAMIENTAS\Real-Time-Voice-Cloning-master>pip uninstall numpy
Found existing installation: numpy 1.19.3
Uninstalling numpy-1.19.3:
  Would remove:
    c:\users\rodri\appdata\local\programs\python\python36\lib\site-packages\numpy-1.19.3.dist-info\*
    c:\users\rodri\appdata\local\programs\python\python36\lib\site-packages\numpy\*
    c:\users\rodri\appdata\local\programs\python\python36\scripts\f2py.exe
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.19.3

D:\Google Drive\EXOMENTUM\BAÚLES\INVENTARIO Y HERRAMIENTAS\Real-Time-Voice-Cloning-master>pip install numpy==1.21.0
ERROR: Could not find a version that satisfies the requirement numpy==1.21.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
ERROR: No matching distribution found for numpy==1.21.0

D:\Google Drive\EXOMENTUM\BAÚLES\INVENTARIO Y HERRAMIENTAS\Real-Time-Voice-Cloning-master>pip install numpy
Collecting numpy
  Using cached numpy-1.19.5-cp36-cp36m-win_amd64.whl (13.2 MB)
Installing collected packages: numpy
Successfully installed numpy-1.19.5

D:\Google Drive\EXOMENTUM\BAÚLES\INVENTARIO Y HERRAMIENTAS\Real-Time-Voice-Cloning-master>python demo_cli.py
Traceback (most recent call last):
  File "demo_cli.py", line 2, in <module>
    from utils.argutils import print_args
  File "D:\Google Drive\EXOMENTUM\BAÚLES\INVENTARIO Y HERRAMIENTAS\Real-Time-Voice-Cloning-master\utils\argutils.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by TrycsPublic** [comment]
whats your python version? where are you getting your pip repo from? is it latest pip version?

also send the output of: pip freeze

**Comment by TrycsPublic** [comment]
Since your are in windows, try creating an empty conda venv and reinstall everything.
