### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by adpablos** [CorentinJ/Real-Time-Voice-Cloning#1113]
Hello,

using a new pyenv environment with the following versions and lib installed (after doing the `pip3 install torch torchvision torchaudio`)

```
% python --version
Python 3.10.4
% pyenv --version
pyenv 2.3.0
% pip list
Package            Version
------------------ ---------
certifi            2022.9.14
charset-normalizer 2.1.1
idna               3.4
numpy              1.23.3
Pillow             9.2.0
pip                22.2.2
requests           2.28.1
setuptools         58.1.0
torch              1.12.1
torchaudio         0.12.1
torchvision        0.13.1
typing_extensions  4.3.0
urllib3            1.26.12`

I am having an error when trying to install the requirements `pip3 install -r requirements.txt` 

`  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/adpablos/.pyenv/versions/3.10.4/envs/real-time-voice-cloning/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/adpablos/.pyenv/versions/3.10.4/envs/real-time-voice-cloning/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/adpablos/.pyenv/versions/3.10.4/envs/real-time-voice-cloning/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/adpablos/.pyenv/versions/3.10.4/envs/real-time-voice-cloning/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/7t/5snbn06x5j17zqr251ryl7p40000gn/T/pip-build-env-fp3sbooh/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/7t/5snbn06x5j17zqr251ryl7p40000gn/T/pip-build-env-fp3sbooh/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/7t/5snbn06x5j17zqr251ryl7p40000gn/T/pip-build-env-fp3sbooh/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 584, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/7t/5snbn06x5j17zqr251ryl7p40000gn/T/pip-install-eenv0a8p/pyqt5_77eef741f3924b23ad38cc2613c5171c/project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/7t/5snbn06x5j17zqr251ryl7p40000gn/T/pip-build-env-fp3sbooh/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/7t/5snbn06x5j17zqr251ryl7p40000gn/T/pip-build-env-fp3sbooh/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/7t/5snbn06x5j17zqr251ryl7p40000gn/T/pip-build-env-fp3sbooh/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any idea what I am missing?

Thanks in advance!

**Comment by wjy9902** [comment]
Hello, I meet same issue now. Do you already solve this problem?

**Comment by adpablos** [comment]
Hey wjy9902.

Not completely, but take a look to [this other thread](https://github.com/coqui-ai/TTS/discussions/1975#discussioncomment-3667050) since you can find useful things there.

**Comment by manas0707** [comment]
pip install shap

 note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


(please help)

**Comment by kasrsamareh** [comment]
Hi. Try this two commands below : 
```
pip install torchvision
pip install torchaudio
```

**Comment by ApaxPhoenix** [comment]
The solution is probably just installing the latest supported pip version.
```py
python.exe -m pip install pip==21.3.0
```

**Comment by BIGBRODIE94** [comment]
Hi Team, 
Any update on this issue, when trying to install pip install fix-yahoo-finance, I am getting the following error below
"error: metadata-generation-failed" &  error: subprocess-exited-with-error

**Comment by adpablos** [comment]
Follow [ImanuillKant1](https://github.com/ImanuillKant1) last recommendations and also read https://github.com/coqui-ai/TTS/discussions/1975#discussioncomment-3667050 where you could have some more help

**Comment by nurmukhammaddev** [comment]
pip install torchvision
pip install torchaudio

Solve

**Comment by Elliasov** [comment]
how do I solve this problem in kali linux?

**Comment by phpepe** [comment]
I had the same problem on MacOS w/ m1 processor.
The fix was: Setting  "Open using Rosetta" on iTerm and the reinstalling the venv and requirements.txt again.

**Comment by nurmukhammaddev** [comment]
pip install torchvision
pip install torchaudio
