### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy'

### ISSUE THREAD

**Issue by wjy9902** [CorentinJ/Real-Time-Voice-Cloning#1114]
Hello,

When I run `python demo_toolbox.py`, it shows
```
D:\语音\Real-Time-Voice-Cloning-master>python demo_toolbox.py
Traceback (most recent call last):
  File "D:\语音\Real-Time-Voice-Cloning-master\demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
  File "D:\语音\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 9, in <module>
    from encoder import inference as encoder
  File "D:\语音\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "D:\语音\Real-Time-Voice-Cloning-master\encoder\model.py", line 3, in <module>
    from scipy.interpolate import interp1d
ModuleNotFoundError: No module named 'scipy'
```
I followed Install Requirements, but it seems there's still something required.

**Comment by tanishdave** [comment]
Did you run pip install - requirements?
if it ran into any error open requirements file and install each module individually. 
in your case pip install scipy . run this commmand from git bash .

**Comment by HexBanana** [comment]
从你的电脑目录看，我猜你应该说中文，所以我就用中文和你交流了。你可能没有下载scipy这个库，所以我建议你运行pip install scipy或者在项目根目录下运行pip install -r requirements.txt以下载依赖项。希望能解决你的问题。

**Comment by abuzahid** [comment]
pip install scipy
