### ISSUE TITLE
DLL load failed while importing QtCore

### ISSUE THREAD

**Issue by michael-ts** [CorentinJ/Real-Time-Voice-Cloning#1124]
When I try to run `python demo_toolbox.py` it fails with this error:

    Traceback (most recent call last):
      File "C:\Users\michael\Real-Time-Voice-Cloning-master\demo_toolbox.py", line 5, in <module>
        from toolbox import Toolbox
      File "C:\Users\michael\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 11, in <module>
        from toolbox.ui import UI
      File "C:\Users\michael\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 12, in <module>
        from PyQt5.QtCore import Qt, QStringListModel
    ImportError: DLL load failed while importing QtCore: The specified module could not be found.

I tried upgrading PyQt5 to see if that would have any effect; it went from 5.15.6 to to 5.15.7 but this did not fixt the issue.

**Comment by michael-ts** [comment]
Fixed with:

    pip uninstall pyqt5
    pip uninstall pyqt5-sip
    pip uninstall pyqt5-qt5
    pip install pyqt5 --user
