### ISSUE TITLE
python demo_toolbox.py is not starting up..It's giving the error below...! I installed everything and did it correctly but still gives me this error. This is my 6th time of installing sv2tts program( using anaconda)

### ISSUE THREAD

**Issue by hackminer101** [CorentinJ/Real-Time-Voice-Cloning#1126]
(Voicecloning) C:\Users\hp>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
ImportError: cannot import name 'Toolbox' from 'toolbox' (C:\Users\hp\Documents\anaconda3\envs\Voicecloning\lib\site-packages\toolbox\__init__.py)

(Voicecloning) C:\Users\hp>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
ImportError: cannot import name 'Toolbox' from 'toolbox' (C:\Users\hp\Documents\anaconda3\envs\Voicecloning\lib\site-packages\toolbox\__init__.py)

(Voicecloning) C:\Users\hp>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
ImportError: cannot import name 'Toolbox' from 'toolbox' (C:\Users\hp\Documents\anaconda3\envs\Voicecloning\lib\site-packages\toolbox\__init__.py)

(Voicecloning) C:\Users\hp>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
ImportError: cannot import name 'Toolbox' from 'toolbox' (C:\Users\hp\Documents\anaconda3\envs\Voicecloning\lib\site-packages\toolbox\__init__.py)

(Voicecloning) C:\Users\hp>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
ImportError: cannot import name 'Toolbox' from 'toolbox' (C:\Users\hp\Documents\anaconda3\envs\Voicecloning\lib\site-packages\toolbox\__init__.py)

(Voicecloning) C:\Users\hp>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
ImportError: cannot import name 'Toolbox' from 'toolbox' (C:\Users\hp\Documents\anaconda3\envs\Voicecloning\lib\site-packages\toolbox\__init__.py)

(Voicecloning) C:\Users\hp>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
ImportError: cannot import name 'Toolbox' from 'toolbox' (C:\Users\hp\Documents\anaconda3\envs\Voicecloning\lib\site-packages\toolbox\__init__.py)

(Voicecloning) C:\Users\hp>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
ImportError: cannot import name 'Toolbox' from 'toolbox' (C:\Users\hp\Documents\anaconda3\envs\Voicecloning\lib\site-packages\toolbox\__init__.py)

(Voicecloning) C:\Users\hp>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
ImportError: cannot import name 'Toolbox' from 'toolbox' (C:\Users\hp\Documents\anaconda3\envs\Voicecloning\lib\site-packages\toolbox\__init__.py)

**Comment by auri99** [comment]
you should run the command `python demo_toolbox.py` in the project directory.
