### ISSUE TITLE
TypeError: load() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by enlightenight** [CorentinJ/Real-Time-Voice-Cloning#1166]
Hello,

I have done everything so far, but when I'm trying to load from the LibreSpeech samples, this is the error I get.

Arguments:
    datasets_root:   datasets_root
    models_dir:      saved_models
    cpu:             False
    seed:            None

Traceback (most recent call last):
  File "/Users/XYZ/Documents/real-time-voice-cloning/toolbox/__init__.py", line 76, in <lambda>
    self.ui.browser_load_button.clicked.connect(lambda: self.load_from_browser())
  File "/Users/XYZ/Documents/real-time-voice-cloning/toolbox/__init__.py", line 157, in load_from_browser
    wav = Synthesizer.load_preprocess_wav(fpath)
  File "/Users/XYZ/Documents/real-time-voice-cloning/synthesizer/inference.py", line 136, in load_preprocess_wav
    wav = librosa.load(str(fpath), hparams.sample_rate)[0]
TypeError: load() takes 1 positional argument but 2 were given

What should I do?

**Comment by yallavaibhav** [comment]
I have the same issue

**Comment by KhangTimm** [comment]
I seemed to have this problem too and it had something to do with the updated version of the librosa package. Installing an older version of librosa solved my problem:

`pip install librosa==0.9.2`

**Comment by SayedDubai** [comment]
Solved my error by reinstalling librosa

**Comment by umangkalavadiya** [comment]
> pip install librosa==0.9.2

solved my error using this.

**Comment by Danster23** [comment]
Solved error by doing this.

**Comment by XRone99** [comment]
worked for me too

**Comment by voilentKiller0** [comment]
solved my problem too

**Comment by pranavtushar** [comment]
Hey with the new update of librosa, you have to specify the argument name, it will work.

**Comment by poojuaj** [comment]
solved my issues too thank you

**Comment by alf2001br** [comment]
Try forcing "rate=" in the parameters 

E.g.: librosa.effects.time_stretch(original, rate=1.0)

that worked for me with several rates

**Comment by Thoufeeq2k** [comment]
i cant solve this even after installing librosa 0.9.2, i downgraded to 0.8.0 too
can anyone tell what version of python you were using pls

**Comment by csipapicsa** [comment]
I have the same problem for me 0.9.2 doesn't solve the problem. Problably 

Installing collected packages: numpy, librosa
librosa-0.9.2
numpy-2.0.2

harmonic, _ = librosa.effects.hpss(y)

stft = core.stft(y)

img = librosa.display.specshow(librosa.amplitude_to_db(S,
    [212](file:///E:/GITHUB_E/OrganicSubmission/.venv/Lib/site-packages/librosa/core/spectrum.py:212)     ...                                                        ref=np.max),
    [213](file:///E:/GITHUB_E/OrganicSubmission/.venv/Lib/site-packages/librosa/core/spectrum.py:213)     ...                                y_axis='log', x_axis='time', ax=ax)
    
   pad_center() takes 1 positional argument but 2 were given
