### ISSUE TITLE
Error when running demo_cli.py

### ISSUE THREAD

**Issue by ifuchs** [CorentinJ/Real-Time-Voice-Cloning#1175]
After installing the required modules, I tried running demo_cli.py and got:

`python demo_cli.py
Arguments:
    enc_model_fpath:   saved_models/default/encoder.pt
    syn_model_fpath:   saved_models/default/synthesizer.pt
    voc_model_fpath:   saved_models/default/vocoder.pt
    cpu:               False
    no_sound:          False
    seed:              None

Running a test of your configuration...

Using CPU for inference.

Preparing the encoder, the synthesizer and the vocoder...
                                                                                                                                      Loaded encoder "encoder.pt" trained to step 1564501
Synthesizer using device: cpu
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at saved_models/default/vocoder.pt
Testing your configuration with small inputs.
	Testing the encoder...
Traceback (most recent call last):
  File "/Users/ihf/Real-Time-Voice-Cloning/demo_cli.py", line 80, in <module>
    encoder.embed_utterance(np.zeros(encoder.sampling_rate))
  File "/Users/ihf/Real-Time-Voice-Cloning/encoder/inference.py", line 144, in embed_utterance
    frames = audio.wav_to_mel_spectrogram(wav)
  File "/Users/ihf/Real-Time-Voice-Cloning/encoder/audio.py", line 58, in wav_to_mel_spectrogram
    frames = librosa.feature.melspectrogram(
TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given`

**Comment by Vasanthan-aka-Maari** [comment]
Refer this  - https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/1166
