### ISSUE TITLE
error on requirments.txt MacOS

### ISSUE THREAD

**Issue by dlogneb** [CorentinJ/Real-Time-Voice-Cloning#1209]
trying to install on MacOS.  When I enter "pip install -r requirements.txt" it goes through a bunch of stuff but then errors out with  what is pasted below.  Anyone have any ideas?

MacOS 12.3.1, Mac Studio M1

Error output:
`    …
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/_common.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/Users/ben/anaconda3/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      blis_info:
        libraries blis not found in ['/Users/ben/anaconda3/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      openblas_info:
      C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/ben/anaconda3/include -fPIC -O2 -isystem /Users/ben/anaconda3/include
      
      creating /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var
      creating /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var/folders
      creating /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var/folders/s0
      creating /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var/folders/s0/j8wf6b05697_54202d1tr5800000gn
      creating /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T
      creating /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12
      compile options: '-c'
      clang: /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/source.c
      xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
      Traceback (most recent call last):
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/unixccompiler.py", line 53, in UnixCCompiler__compile
          self.spawn(self.compiler_so + cc_args + [src, '-o', obj] + deps +
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/ccompiler.py", line 90, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/ccompiler.py", line 173, in CCompiler_spawn
          raise DistutilsExecError('Command "%s" failed with exit status %d%s' %
      distutils.errors.DistutilsExecError: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/ben/anaconda3/include -fPIC -O2 -isystem /Users/ben/anaconda3/include -c /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/source.c -o /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/source.o -MMD -MF /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/source.o.d" failed with exit status 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/ben/anaconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/ben/anaconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ben/anaconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-build-env-7tj7xzft/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-build-env-7tj7xzft/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 248, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-build-env-7tj7xzft/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 513, in <module>
          setup_package()
        File "setup.py", line 505, in setup_package
          setup(**metadata)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/core.py", line 135, in setup
          config = configuration()
        File "setup.py", line 173, in configuration
          config.add_subpackage('numpy')
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/misc_util.py", line 1019, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/misc_util.py", line 985, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/misc_util.py", line 927, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/setup.py", line 8, in configuration
          config.add_subpackage('core')
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/misc_util.py", line 1019, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/misc_util.py", line 985, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/misc_util.py", line 927, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/core/setup.py", line 757, in configuration
          blas_info = get_info('blas_opt', 0)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 584, in get_info
          return cl().get_info(notfound_action)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 844, in get_info
          self.calc_info()
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 1989, in calc_info
          if self._calc_info(blas):
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 1981, in _calc_info
          return getattr(self, '_calc_info_{}'.format(name))()
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 1932, in _calc_info_openblas
          info = get_info('openblas')
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 584, in get_info
          return cl().get_info(notfound_action)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 844, in get_info
          self.calc_info()
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 2195, in calc_info
          info = self._calc_info()
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 2183, in _calc_info
          if not (skip_symbol_check or self.check_symbols(info)):
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/system_info.py", line 2262, in check_symbols
          obj = c.compile([src], output_dir=tmpdir)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/ccompiler.py", line 90, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/ccompiler.py", line 361, in CCompiler_compile
          single_compile(o)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/ccompiler.py", line 321, in single_compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/ccompiler.py", line 90, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-install-3od9mbik/numpy_75f80fbb24b443528443f3b884563934/numpy/distutils/unixccompiler.py", line 57, in UnixCCompiler__compile
          raise CompileError(msg)
      distutils.errors.CompileError: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/ben/anaconda3/include -fPIC -O2 -isystem /Users/ben/anaconda3/include -c /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/source.c -o /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/source.o -MMD -MF /var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/tmpkhmv3_12/source.o.d" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by dlogneb** [comment]
it seems that mkl_rt does not exist on my system

**Comment by stsykin** [comment]
It was a problem with `PyQt5`, you can solve it by Rossetta (enable Rossetta for Terminal -> install requirements), here are links that can help(more details, screenshots..):
1. [Link](https://dev.to/courier/tips-and-tricks-to-setup-your-apple-m1-for-development-547g) how to enable Rosetta on your M1: 
1. [Answer](https://stackoverflow.com/questions/65901162/how-can-i-run-pyqt5-on-my-mac-with-m1chip-ppc64el-architecture) on StackOverflow about `PyQt5`

**Comment by dlogneb** [comment]
thanks, I'll check this out.

**Comment by RonierisonMaciel** [comment]
Tks @stsykin!

I was able to install it by following these steps.

1.  Using iTerm [Duplication terminal in macOS Ventura](https://stackoverflow.com/questions/74198234/duplication-of-terminal-in-macos-ventura)
2. Your suggestion
