### ISSUE TITLE
error after runnig demo toolbox

### ISSUE THREAD

**Issue by gerdaa** [CorentinJ/Real-Time-Voice-Cloning#1222]
Hello, 

When I run demo_toolbox.py I get this error. How can I fix this errors?

=====================================================
(voice-clone) C:\Users\Linda\Desktop\voice>python demo_cli.py
Arguments:
    enc_model_fpath:   saved_models\default\encoder.pt
    syn_model_fpath:   saved_models\default\synthesizer.pt
    voc_model_fpath:   saved_models\default\vocoder.pt
    cpu:               False
    no_sound:          False
    seed:              None

Running a test of your configuration...

Using CPU for inference.

Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "encoder.pt" trained to step 1564501
Synthesizer using device: cpu
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at saved_models\default\vocoder.pt
Testing your configuration with small inputs.
        Testing the encoder...
Traceback (most recent call last):
  File "C:\Users\Linda\Desktop\voice\demo_cli.py", line 80, in <module>
    encoder.embed_utterance(np.zeros(encoder.sampling_rate))
  File "C:\Users\Linda\Desktop\voice\encoder\inference.py", line 144, in embed_utterance
    frames = audio.wav_to_mel_spectrogram(wav)
  File "C:\Users\Linda\Desktop\voice\encoder\audio.py", line 58, in wav_to_mel_spectrogram
    frames = librosa.feature.melspectrogram(
TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given
=====================================================
Thanks already,
Gerdaa

**Comment by radhavishnu** [comment]
Install the version of librosa they used, or go to each loaction and give parameters y=, n_mels=
example librosa.stft(y=y, n_fft=hparams.n_fft, hop_length=get_hop_size(hparams), win_length=hparams.win_size)
