### ISSUE TITLE
Error: metadata-generation-failed - related to scikit-learn? - python 3.11

### ISSUE THREAD

**Issue by jessienab** [CorentinJ/Real-Time-Voice-Cloning#1233]
Arch Linux, kernel 6.4.2-arch1-1, python 3.11.3 (GCC 13.1.1), pip 23.1.2
Thank you for any help!

I followed these steps:

```
python -m venv .env
pip install ffmpeg
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
pip install -r requirements.txt
```

Below is the log of `pip install -r requirements.txt`, with the relevant error:
```
Collecting inflect==5.3.0 (from -r requirements.txt (line 1))
  Using cached inflect-5.3.0-py3-none-any.whl (32 kB)
Collecting librosa==0.8.1 (from -r requirements.txt (line 2))
  Using cached librosa-0.8.1-py3-none-any.whl (203 kB)
Collecting matplotlib==3.5.1 (from -r requirements.txt (line 3))
  Using cached matplotlib-3.5.1.tar.gz (35.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting numpy==1.20.3 (from -r requirements.txt (line 4))
  Using cached numpy-1.20.3.zip (7.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting Pillow==8.4.0 (from -r requirements.txt (line 5))
  Using cached Pillow-8.4.0.tar.gz (49.4 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting PyQt5==5.15.6 (from -r requirements.txt (line 6))
  Using cached PyQt5-5.15.6-cp36-abi3-manylinux1_x86_64.whl (8.3 MB)
Collecting scikit-learn==1.0.2 (from -r requirements.txt (line 7))
  Using cached scikit-learn-1.0.2.tar.gz (6.7 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [261 lines of output]
      Partial import of sklearn during the build process.
      setup.py:128: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.command.build_ext import build_ext  # noqa
      INFO: C compiler: gcc -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -fPIC
      
      INFO: compile options: '-c'
      INFO: gcc: test_program.c
      INFO: gcc objects/test_program.o -o test_program
      INFO: C compiler: gcc -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -fPIC
      
      INFO: compile options: '-c'
      extra options: '-fopenmp'
      INFO: gcc: test_program.c
      INFO: gcc objects/test_program.o -o test_program -fopenmp
      Compiling sklearn/__check_build/_check_build.pyx because it changed.
      Compiling sklearn/preprocessing/_csr_polynomial_expansion.pyx because it changed.
      Compiling sklearn/cluster/_dbscan_inner.pyx because it changed.
      Compiling sklearn/cluster/_hierarchical_fast.pyx because it changed.
      Compiling sklearn/cluster/_k_means_common.pyx because it changed.
      Compiling sklearn/cluster/_k_means_lloyd.pyx because it changed.
      Compiling sklearn/cluster/_k_means_elkan.pyx because it changed.
      Compiling sklearn/cluster/_k_means_minibatch.pyx because it changed.
      Compiling sklearn/datasets/_svmlight_format_fast.pyx because it changed.
      Compiling sklearn/decomposition/_online_lda_fast.pyx because it changed.
      Compiling sklearn/decomposition/_cdnmf_fast.pyx because it changed.
      Compiling sklearn/ensemble/_gradient_boosting.pyx because it changed.
      Compiling sklearn/ensemble/_hist_gradient_boosting/_gradient_boosting.pyx because it changed.
      Compiling sklearn/ensemble/_hist_gradient_boosting/histogram.pyx because it changed.
      Compiling sklearn/ensemble/_hist_gradient_boosting/splitting.pyx because it changed.
      Compiling sklearn/ensemble/_hist_gradient_boosting/_binning.pyx because it changed.
      Compiling sklearn/ensemble/_hist_gradient_boosting/_predictor.pyx because it changed.
      Compiling sklearn/ensemble/_hist_gradient_boosting/_loss.pyx because it changed.
      Compiling sklearn/ensemble/_hist_gradient_boosting/_bitset.pyx because it changed.
      Compiling sklearn/ensemble/_hist_gradient_boosting/common.pyx because it changed.
      Compiling sklearn/ensemble/_hist_gradient_boosting/utils.pyx because it changed.
      Compiling sklearn/feature_extraction/_hashing_fast.pyx because it changed.
      Compiling sklearn/manifold/_utils.pyx because it changed.
      Compiling sklearn/manifold/_barnes_hut_tsne.pyx because it changed.
      Compiling sklearn/metrics/cluster/_expected_mutual_info_fast.pyx because it changed.
      Compiling sklearn/metrics/_pairwise_fast.pyx because it changed.
      Compiling sklearn/metrics/_dist_metrics.pyx because it changed.
      Compiling sklearn/neighbors/_ball_tree.pyx because it changed.
      Compiling sklearn/neighbors/_kd_tree.pyx because it changed.
      Compiling sklearn/neighbors/_partition_nodes.pyx because it changed.
      Compiling sklearn/neighbors/_quad_tree.pyx because it changed.
      Compiling sklearn/tree/_tree.pyx because it changed.
      Compiling sklearn/tree/_splitter.pyx because it changed.
      Compiling sklearn/tree/_criterion.pyx because it changed.
      Compiling sklearn/tree/_utils.pyx because it changed.
      Compiling sklearn/utils/sparsefuncs_fast.pyx because it changed.
      Compiling sklearn/utils/_cython_blas.pyx because it changed.
      Compiling sklearn/utils/arrayfuncs.pyx because it changed.
      Compiling sklearn/utils/murmurhash.pyx because it changed.
      Compiling sklearn/utils/_fast_dict.pyx because it changed.
      Compiling sklearn/utils/_openmp_helpers.pyx because it changed.
      Compiling sklearn/utils/_seq_dataset.pyx because it changed.
      Compiling sklearn/utils/_weight_vector.pyx because it changed.
      Compiling sklearn/utils/_random.pyx because it changed.
      Compiling sklearn/utils/_logistic_sigmoid.pyx because it changed.
      Compiling sklearn/utils/_readonly_array_wrapper.pyx because it changed.
      Compiling sklearn/utils/_typedefs.pyx because it changed.
      Compiling sklearn/svm/_newrand.pyx because it changed.
      Compiling sklearn/svm/_libsvm.pyx because it changed.
      Compiling sklearn/svm/_liblinear.pyx because it changed.
      Compiling sklearn/svm/_libsvm_sparse.pyx because it changed.
      Compiling sklearn/linear_model/_cd_fast.pyx because it changed.
      Compiling sklearn/linear_model/_sgd_fast.pyx because it changed.
      Compiling sklearn/linear_model/_sag_fast.pyx because it changed.
      Compiling sklearn/_isotonic.pyx because it changed.
      [ 1/55] Cythonizing sklearn/__check_build/_check_build.pyx
      [ 2/55] Cythonizing sklearn/_isotonic.pyx
      [ 3/55] Cythonizing sklearn/cluster/_dbscan_inner.pyx
      [ 4/55] Cythonizing sklearn/cluster/_hierarchical_fast.pyx
      [ 5/55] Cythonizing sklearn/cluster/_k_means_common.pyx
      [ 6/55] Cythonizing sklearn/cluster/_k_means_elkan.pyx
      [ 7/55] Cythonizing sklearn/cluster/_k_means_lloyd.pyx
      [ 8/55] Cythonizing sklearn/cluster/_k_means_minibatch.pyx
      [ 9/55] Cythonizing sklearn/datasets/_svmlight_format_fast.pyx
      [10/55] Cythonizing sklearn/decomposition/_cdnmf_fast.pyx
      [11/55] Cythonizing sklearn/decomposition/_online_lda_fast.pyx
      [12/55] Cythonizing sklearn/ensemble/_gradient_boosting.pyx
      [13/55] Cythonizing sklearn/ensemble/_hist_gradient_boosting/_binning.pyx
      [14/55] Cythonizing sklearn/ensemble/_hist_gradient_boosting/_bitset.pyx
      [15/55] Cythonizing sklearn/ensemble/_hist_gradient_boosting/_gradient_boosting.pyx
      [16/55] Cythonizing sklearn/ensemble/_hist_gradient_boosting/_loss.pyx
      [17/55] Cythonizing sklearn/ensemble/_hist_gradient_boosting/_predictor.pyx
      [18/55] Cythonizing sklearn/ensemble/_hist_gradient_boosting/common.pyx
      [19/55] Cythonizing sklearn/ensemble/_hist_gradient_boosting/histogram.pyx
      [20/55] Cythonizing sklearn/ensemble/_hist_gradient_boosting/splitting.pyx
      [21/55] Cythonizing sklearn/ensemble/_hist_gradient_boosting/utils.pyx
      [22/55] Cythonizing sklearn/feature_extraction/_hashing_fast.pyx
      [23/55] Cythonizing sklearn/linear_model/_cd_fast.pyx
      [24/55] Cythonizing sklearn/linear_model/_sag_fast.pyx
      [25/55] Cythonizing sklearn/linear_model/_sgd_fast.pyx
      [26/55] Cythonizing sklearn/manifold/_barnes_hut_tsne.pyx
      [27/55] Cythonizing sklearn/manifold/_utils.pyx
      [28/55] Cythonizing sklearn/metrics/_dist_metrics.pyx
      [29/55] Cythonizing sklearn/metrics/_pairwise_fast.pyx
      [30/55] Cythonizing sklearn/metrics/cluster/_expected_mutual_info_fast.pyx
      [31/55] Cythonizing sklearn/neighbors/_ball_tree.pyx
      [32/55] Cythonizing sklearn/neighbors/_kd_tree.pyx
      [33/55] Cythonizing sklearn/neighbors/_partition_nodes.pyx
      [34/55] Cythonizing sklearn/neighbors/_quad_tree.pyx
      [35/55] Cythonizing sklearn/preprocessing/_csr_polynomial_expansion.pyx
      [36/55] Cythonizing sklearn/svm/_liblinear.pyx
      [37/55] Cythonizing sklearn/svm/_libsvm.pyx
      [38/55] Cythonizing sklearn/svm/_libsvm_sparse.pyx
      [39/55] Cythonizing sklearn/svm/_newrand.pyx
      [40/55] Cythonizing sklearn/tree/_criterion.pyx
      [41/55] Cythonizing sklearn/tree/_splitter.pyx
      [42/55] Cythonizing sklearn/tree/_tree.pyx
      [43/55] Cythonizing sklearn/tree/_utils.pyx
      [44/55] Cythonizing sklearn/utils/_cython_blas.pyx
      [45/55] Cythonizing sklearn/utils/_fast_dict.pyx
      [46/55] Cythonizing sklearn/utils/_logistic_sigmoid.pyx
      [47/55] Cythonizing sklearn/utils/_openmp_helpers.pyx
      [48/55] Cythonizing sklearn/utils/_random.pyx
      [49/55] Cythonizing sklearn/utils/_readonly_array_wrapper.pyx
      [50/55] Cythonizing sklearn/utils/_seq_dataset.pyx
      [51/55] Cythonizing sklearn/utils/_typedefs.pyx
      [52/55] Cythonizing sklearn/utils/_weight_vector.pyx
      [53/55] Cythonizing sklearn/utils/arrayfuncs.pyx
      [54/55] Cythonizing sklearn/utils/murmurhash.pyx
      [55/55] Cythonizing sklearn/utils/sparsefuncs_fast.pyx
      running dist_info
      running build_src
      INFO: build_src
      INFO: building library "libsvm-skl" sources
      INFO: building library "liblinear-skl" sources
      INFO: building extension "sklearn.__check_build._check_build" sources
      INFO: building extension "sklearn.preprocessing._csr_polynomial_expansion" sources
      INFO: building extension "sklearn.cluster._dbscan_inner" sources
      INFO: building extension "sklearn.cluster._hierarchical_fast" sources
      INFO: building extension "sklearn.cluster._k_means_common" sources
      INFO: building extension "sklearn.cluster._k_means_lloyd" sources
      INFO: building extension "sklearn.cluster._k_means_elkan" sources
      INFO: building extension "sklearn.cluster._k_means_minibatch" sources
      INFO: building extension "sklearn.datasets._svmlight_format_fast" sources
      INFO: building extension "sklearn.decomposition._online_lda_fast" sources
      INFO: building extension "sklearn.decomposition._cdnmf_fast" sources
      INFO: building extension "sklearn.ensemble._gradient_boosting" sources
      INFO: building extension "sklearn.ensemble._hist_gradient_boosting._gradient_boosting" sources
      INFO: building extension "sklearn.ensemble._hist_gradient_boosting.histogram" sources
      INFO: building extension "sklearn.ensemble._hist_gradient_boosting.splitting" sources
      INFO: building extension "sklearn.ensemble._hist_gradient_boosting._binning" sources
      INFO: building extension "sklearn.ensemble._hist_gradient_boosting._predictor" sources
      INFO: building extension "sklearn.ensemble._hist_gradient_boosting._loss" sources
      INFO: building extension "sklearn.ensemble._hist_gradient_boosting._bitset" sources
      INFO: building extension "sklearn.ensemble._hist_gradient_boosting.common" sources
      INFO: building extension "sklearn.ensemble._hist_gradient_boosting.utils" sources
      INFO: building extension "sklearn.feature_extraction._hashing_fast" sources
      INFO: building extension "sklearn.manifold._utils" sources
      INFO: building extension "sklearn.manifold._barnes_hut_tsne" sources
      INFO: building extension "sklearn.metrics.cluster._expected_mutual_info_fast" sources
      INFO: building extension "sklearn.metrics._pairwise_fast" sources
      INFO: building extension "sklearn.metrics._dist_metrics" sources
      INFO: building extension "sklearn.neighbors._ball_tree" sources
      INFO: building extension "sklearn.neighbors._kd_tree" sources
      INFO: building extension "sklearn.neighbors._partition_nodes" sources
      INFO: building extension "sklearn.neighbors._quad_tree" sources
      INFO: building extension "sklearn.tree._tree" sources
      INFO: building extension "sklearn.tree._splitter" sources
      INFO: building extension "sklearn.tree._criterion" sources
      INFO: building extension "sklearn.tree._utils" sources
      INFO: building extension "sklearn.utils.sparsefuncs_fast" sources
      INFO: building extension "sklearn.utils._cython_blas" sources
      INFO: building extension "sklearn.utils.arrayfuncs" sources
      INFO: building extension "sklearn.utils.murmurhash" sources
      INFO: building extension "sklearn.utils._fast_dict" sources
      INFO: building extension "sklearn.utils._openmp_helpers" sources
      INFO: building extension "sklearn.utils._seq_dataset" sources
      INFO: building extension "sklearn.utils._weight_vector" sources
      INFO: building extension "sklearn.utils._random" sources
      INFO: building extension "sklearn.utils._logistic_sigmoid" sources
      INFO: building extension "sklearn.utils._readonly_array_wrapper" sources
      INFO: building extension "sklearn.utils._typedefs" sources
      INFO: building extension "sklearn.svm._newrand" sources
      INFO: building extension "sklearn.svm._libsvm" sources
      INFO: building extension "sklearn.svm._liblinear" sources
      INFO: building extension "sklearn.svm._libsvm_sparse" sources
      INFO: building extension "sklearn.linear_model._cd_fast" sources
      INFO: building extension "sklearn.linear_model._sgd_fast" sources
      INFO: building extension "sklearn.linear_model._sag_fast" sources
      INFO: building extension "sklearn._isotonic" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      /tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      Traceback (most recent call last):
        File "/tmp/Real-Time-Voice-Cloning/.env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/Real-Time-Voice-Cloning/.env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/Real-Time-Voice-Cloning/.env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 319, in <module>
          setup_package()
        File "setup.py", line 315, in setup_package
          setup(**metadata)
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/command/dist_info.py", line 31, in run
          egg_info.run()
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/numpy/distutils/command/egg_info.py", line 24, in run
          self.run_command("build_src")
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 144, in run
          self.build_sources()
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 164, in build_sources
          self.build_npy_pkg_config()
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 235, in build_npy_pkg_config
          install_cmd.finalize_options()
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/numpy/distutils/command/install.py", line 21, in finalize_options
          old_install.finalize_options(self)
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/command/install.py", line 45, in finalize_options
          orig.install.finalize_options(self)
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 325, in finalize_options
          self.finalize_unix()
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 498, in finalize_unix
          self.select_scheme("posix_prefix")
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 528, in select_scheme
          return self._select_scheme(resolved)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6h00dobt/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 537, in _select_scheme
          setattr(self, attrname, scheme[key])
                                  ~~~~~~^^^^^
      KeyError: 'headers'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rishav-bose0** [comment]
> Python 3.7 is recommended. Python 3.5 or greater should work, but you'll probably have to tweak the dependencies' versions. I recommend setting up a virtual environment using venv, but this is optional.

Please downgrade to 3.7 versions for it to work.
