### ISSUE TITLE
can i run this in google colab without any problem 

### ISSUE THREAD

**Issue by Gonharaka** [CorentinJ/Real-Time-Voice-Cloning#1245]
and i tried too 
and i got this 

Running a test of your configuration...

Found 1 GPUs available. Using GPU 0 (Tesla T4) of compute capability 7.5 with 15.8Gb total memory.

Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "encoder.pt" trained to step 1564501
Synthesizer using device: cuda
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at saved_models/default/vocoder.pt
Testing your configuration with small inputs.
	Testing the encoder...
Traceback (most recent call last):
  File "/content/Real-Time-Voice-Cloning/demo_cli.py", line 80, in <module>
    encoder.embed_utterance(np.zeros(encoder.sampling_rate))
  File "/content/Real-Time-Voice-Cloning/encoder/inference.py", line 144, in embed_utterance
    frames = audio.wav_to_mel_spectrogram(wav)
  File "/content/Real-Time-Voice-Cloning/encoder/audio.py", line 58, in wav_to_mel_spectrogram
    frames = librosa.feature.melspectrogram(
TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given

Colab paid products - Cancel contracts here

**Comment by SuitGuy** [comment]
#1166
pip install librosa==0.9.2
