### ISSUE TITLE
encoder error

### ISSUE THREAD

**Issue by bantikumarsatlokashram** [CorentinJ/Real-Time-Voice-Cloning#1247]
Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "encoder.pt" trained to step 1564501
Synthesizer using device: cuda
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at saved_models\default\vocoder.pt
Testing your configuration with small inputs.
        Testing the encoder...
Traceback (most recent call last):
  File "C:\voice\demo_cli.py", line 83, in <module>
    embedding = encoder.embed_utterance(audio_waveform)
  File "C:\voice\encoder\inference.py", line 144, in embed_utterance
    frames = audio.wav_to_mel_spectrogram(wav)
  File "C:\voice\encoder\audio.py", line 58, in wav_to_mel_spectrogram
    frames = librosa.feature.melspectrogram(
TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given

**Comment by koteyro** [comment]
did you find a solution?

**Comment by SuitGuy** [comment]
#1166 
pip install librosa==0.9.2
