### ISSUE TITLE
I got this error running demo_cli.py. Assistance would be appreciated.

### ISSUE THREAD

**Issue by Lijey427** [CorentinJ/Real-Time-Voice-Cloning#1249]
Traceback (most recent call last):
  File "c:\Users\----\Downloads\Real-Time-Voice-Cloning-master\demo_cli.py", line 80, in <module>
    encoder.embed_utterance(np.zeros(encoder.sampling_rate))
  File "c:\Users\----\Downloads\Real-Time-Voice-Cloning-master\encoder\inference.py", line 144, in embed_utterance
    frames = audio.wav_to_mel_spectrogram(wav)
File "c:\Users\----\Downloads\Real-Time-Voice-Cloning-master\encoder\audio.py", line 58, in wav_to_mel_spectrogram
    frames = librosa.feature.melspectrogram(
TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given

**Comment by SuitGuy** [comment]
pip install librosa==0.9.2

**Comment by DhiaAkermii** [comment]
> pip install librosa==0.9.2

Thank you so much, this solved the error
