### ISSUE TITLE
sipbuild.pyproject.PyProjectOptionException during pip install

### ISSUE THREAD

**Issue by marcobazzani** [CorentinJ/Real-Time-Voice-Cloning#1252]
While running
 pip install -r requirements.txt

got 

```
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/Users/marco/.pyenv/versions/3.11.5/envs/rtvc/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/marco/.pyenv/versions/3.11.5/envs/rtvc/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/marco/.pyenv/versions/3.11.5/envs/rtvc/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/py/9j3vxq9x44q9k9bc1_tb13bc0000gp/T/pip-build-env-avz9esk8/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/py/9j3vxq9x44q9k9bc1_tb13bc0000gp/T/pip-build-env-avz9esk8/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/py/9j3vxq9x44q9k9bc1_tb13bc0000gp/T/pip-build-env-avz9esk8/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/py/9j3vxq9x44q9k9bc1_tb13bc0000gp/T/pip-install-pm6odyos/pyqt5_381e2a1d4cbc42e5906a2b57d17ae409/project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/py/9j3vxq9x44q9k9bc1_tb13bc0000gp/T/pip-build-env-avz9esk8/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/py/9j3vxq9x44q9k9bc1_tb13bc0000gp/T/pip-build-env-avz9esk8/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/py/9j3vxq9x44q9k9bc1_tb13bc0000gp/T/pip-build-env-avz9esk8/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
```

python 3.11.5

**Comment by zoe4cs** [comment]
I had the same problem， did you solve it?
python 3.8
