### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found.

### ISSUE THREAD

**Issue by Reno0vacio** [CorentinJ/Real-Time-Voice-Cloning#1259]
(venv) PS F:\Voice github\Real-Time-Voice-Cloning> python .\demo_toolbox.py
Traceback (most recent call last):
  File ".\demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
  File "F:\Voice github\Real-Time-Voice-Cloning\toolbox\__init__.py", line 9, in <module>
    from encoder import inference as encoder
  File "F:\Voice github\Real-Time-Voice-Cloning\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "F:\Voice github\Real-Time-Voice-Cloning\encoder\model.py", line 3, in <module>
    from scipy.interpolate import interp1d
  File "F:\Voice github\Real-Time-Voice-Cloning\venv\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "F:\Voice github\Real-Time-Voice-Cloning\venv\lib\site-packages\scipy\_distributor_init.py", line 64, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found.

I use python 3.7 and venv as the repo owner suggested. Shoud i change the python version? Any ideas?

**Comment by MassEast** [comment]
Seems like you just got to install the missing module(s) via _pip_
