### ISSUE TITLE
Window crashes because no encoder models where found

### ISSUE THREAD

**Issue by js-on** [CorentinJ/Real-Time-Voice-Cloning#128]
Good morning,

I'm trying to setup your application on Windows / Linux.
Cause I won't install the C++ Build-Tools, I'm no trying on Linux.

After hours of work with pip, I'm now able to start the application.
But right after starting the program crashes with the following error message.

```
rtfm@Inspiron-5570:~/Schreibtisch/Real-Time-Voice-Cloning$ python3 demo_toolbox.py --low_mem --datasets_root LibriSpeech/LibriSpeech/train-clean-100/
WARNING:tensorflow:From /home/rtfm/Schreibtisch/Real-Time-Voice-Cloning/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Arguments:
    datasets_root:    LibriSpeech/LibriSpeech/train-clean-100
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    low_mem:          True

Warning: you do not have any of the recognized datasets in LibriSpeech/LibriSpeech/train-clean-100.
The recognized datasets are:
	LibriSpeech/dev-clean
	LibriSpeech/dev-other
	LibriSpeech/test-clean
	LibriSpeech/test-other
	LibriSpeech/train-clean-100
	LibriSpeech/train-clean-360
	LibriSpeech/train-other-500
	LibriTTS/dev-clean
	LibriTTS/dev-other
	LibriTTS/test-clean
	LibriTTS/test-other
	LibriTTS/train-clean-100
	LibriTTS/train-clean-360
	LibriTTS/train-other-500
	LJSpeech-1.1
	VoxCeleb1/wav
	VoxCeleb1/test_wav
	VoxCeleb2/dev/aac
	VoxCeleb2/test/aac
	VCTK-Corpus/wav48
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "demo_toolbox.py", line 32, in <module>
    Toolbox(**vars(args))
  File "/home/rtfm/Schreibtisch/Real-Time-Voice-Cloning/toolbox/__init__.py", line 49, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir)
  File "/home/rtfm/Schreibtisch/Real-Time-Voice-Cloning/toolbox/__init__.py", line 97, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_models_dir)
  File "/home/rtfm/Schreibtisch/Real-Time-Voice-Cloning/toolbox/ui.py", line 275, in populate_models
    raise Exception("No encoder models found in %s" % encoder_models_dir)
Exception: No encoder models found in encoder/saved_models
```

So why is it printing, that there's no valid datasets_root given, when the used parameter fits the datasets_root in the error message?
And how can I fix the issue with the missing encoders?

Anyway, thanks for your time to answer and for this astonishing project.
JS-ON

**Comment by CorentinJ** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models
