### ISSUE TITLE
Installing on M2 Chip error: metadata-generation-failed

### ISSUE THREAD

**Issue by angjelkom** [CorentinJ/Real-Time-Voice-Cloning#1287]
Getting an error when running `pip3 install -r requirements.txt`:

```
Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
  Traceback (most recent call last):
    File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/4y/7nm2j8sn2f935b4rj84p84mh0000gn/T/pip-build-env-07j124dl/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
      project = AbstractProject.bootstrap('wheel',
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/4y/7nm2j8sn2f935b4rj84p84mh0000gn/T/pip-build-env-07j124dl/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap
      project.setup(pyproject, tool, tool_description)
    File "/private/var/folders/4y/7nm2j8sn2f935b4rj84p84mh0000gn/T/pip-build-env-07j124dl/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 587, in setup
      self.apply_user_defaults(tool)
    File "/private/var/folders/4y/7nm2j8sn2f935b4rj84p84mh0000gn/T/pip-install-kvbrfkls/pyqt5_49452ce0d92b4cfe80762d39300f4151/project.py", line 63, in apply_user_defaults
      super().apply_user_defaults(tool)
    File "/private/var/folders/4y/7nm2j8sn2f935b4rj84p84mh0000gn/T/pip-build-env-07j124dl/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
      super().apply_user_defaults(tool)
    File "/private/var/folders/4y/7nm2j8sn2f935b4rj84p84mh0000gn/T/pip-build-env-07j124dl/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
      self.builder.apply_user_defaults(tool)
    File "/private/var/folders/4y/7nm2j8sn2f935b4rj84p84mh0000gn/T/pip-build-env-07j124dl/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
      raise PyProjectOptionException('qmake',
  sipbuild.pyproject.PyProjectOptionException
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/homebrew/opt/python@3.11/bin/python3.11 /opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/4y/7nm2j8sn2f935b4rj84p84mh0000gn/T/tmp4y66fvib
  cwd: /private/var/folders/4y/7nm2j8sn2f935b4rj84p84mh0000gn/T/pip-install-kvbrfkls/pyqt5_49452ce0d92b4cfe80762d39300f4151
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any solutions?

**Comment by Seanih** [comment]
Any luck? I'm facing the exact same issue.

**Comment by clemshubs** [comment]
For me, it was a problem with licence of QT5. Use brew, vent and be aware of python versions conflicts!
