### ISSUE TITLE
cuDNN error: CUDNN_STATUS_EXECUTION _FAILED

### ISSUE THREAD

**Issue by nonlin** [CorentinJ/Real-Time-Voice-Cloning#129]
```
Preparing the encoder, the synthesizer and the vocoder...
Traceback (most recent call last):
  File "demo_cli.py", line 61, in <module>
    encoder.load_model(args.enc_model_fpath)
  File "G:\Chrome Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\encoder\inference.py", line 32, in load_model
    _model = SpeakerEncoder(_device, torch.device("cpu"))
  File "G:\Chrome Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\encoder\model.py", line 21, in __init__
    batch_first=True).to(device)
  File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 381, in to
    return self._apply(convert)
  File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

Any tips?

**Comment by Summerok** [comment]
Hi! I've also had a runtime error because of compute capability of my GPU GeForce 820M which is 2.1. It seems that the lowest compute capability accepted is 3.0. I don't know if it can help you but I'm looking up if there were a way to avoid this step.

RuntimeError: cuDNN error: CUDNN_STATUS_ARCH_MISMATCH

**Comment by nonlin** [comment]
Had to unstiall torch and install  the right one for my CUDA version 10.1.
