### ISSUE TITLE
Download for synthesizer.pt failed. 

### ISSUE THREAD

**Issue by mikail-eliyah-00** [CorentinJ/Real-Time-Voice-Cloning#1295]
While at: Real-Time-Voice-Cloning-master/saved_models/default % tree -f
.
├── ./encoder.pt
├── ./synthesizer.pt
└── ./vocoder.pt

1 directory, 3 files
ursa@USQ04Q6HK79M default % cd ..
ursa@USQ04Q6HK79M saved_models % tree -f
.
└── ./default
    ├── ./default/encoder.pt
    ├── ./default/synthesizer.pt
    └── ./default/vocoder.pt

"""
Traceback (most recent call last):                                                                  
  File "/Real-Time-Voice-Cloning-master/demo_cli.py", line 64, in <module>                                                                                                   
    ensure_default_models(Path("saved_models"))
  File "/Real-Time-Voice-Cloning-master/utils/default_models.py", line 54, in ensure_default_models
    assert target_path.exists() and target_path.stat().st_size == size, \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Download for synthesizer.pt failed. You may download models manually instead.
https://drive.google.com/drive/folders/1fU6umc5uQAVR2udZdHX-lDgXYzTyqG_j
"""

**Comment by lingjie2098** [comment]
eg
(Real-Time-Voice-Cloning_Py38Venv) D:\AS_WorkSpace_X\Real-Time-Voice-Cloning_Py38Venv\Scripts>python ..\..\Real-Time-Voice-Cloning\demo_cli.py

you need put encoder.pt/synthesizer.pt/vocoder.pt into D:\AS_WorkSpace_X\Real-Time-Voice-Cloning_Py38Venv\Scripts\saved_models\default

**Comment by tailor802** [comment]
File saved_models\default\synthesizer.pt is not of expected size, redownloading...

**Comment by CorentinJ** [comment]
Should be fixed with HF as the model host
