### ISSUE TITLE
Error While Running python demo_cli.py

### ISSUE THREAD

**Issue by BJChettri** [CorentinJ/Real-Time-Voice-Cloning#1303]
Running a test of your configuration...

Using CPU for inference.

Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "encoder.pt" trained to step 1564501
Synthesizer using device: cpu
Building Wave-RNN
Traceback (most recent call last):
  File "C:\Users\ABCPC\Desktop\Voice\demo_cli.py", line 67, in <module>
    vocoder.load_model(args.voc_model_fpath)
  File "C:\Users\ABCPC\Desktop\Voice\vocoder\inference.py", line 13, in load_model
    _model = WaveRNN(
  File "C:\Users\ABCPC\Desktop\Voice\vocoder\models\fatchord_version.py", line 107, in __init__
    self.upsample = UpsampleNetwork(feat_dims, upsample_factors, compute_dims, res_blocks, res_out_dims, pad)
  File "C:\Users\ABCPC\Desktop\Voice\vocoder\models\fatchord_version.py", line 64, in __init__
    total_scale = np.cumproduct(upsample_scales)[-1]
  File "d:\anaconda3\envs\VoiceClone\lib\site-packages\numpy\__init__.py", line 440, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'cumproduct'

**Comment by germanebeing** [comment]
did you get a fix for this? I haven't been able to fix it
