### ISSUE TITLE
FileNotFoundError when file is available

### ISSUE THREAD

**Issue by testownik21** [CorentinJ/Real-Time-Voice-Cloning#135]
Currently I'm here:
Dell M4700, K1000M, Win10

1. Will it work with older GPU?
2. There is some problem with FileNotFoundError, because
\..\encoder\saved_models\pretrained.pt
is already there.

--------------
```(base) C:\Users\tester>python D:\VoiceCloning\Real-Time-Voice-Cloning-master\demo_cli.py

WARNING:tensorflow:From D:\VoiceCloning\Real-Time-Voice-Cloning-master\synthesizer\models\modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_dir:     synthesizer\saved_models\logs-pretrained
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    low_mem:           False
    no_sound:          False

Running a test of your configuration...

C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py:118: UserWarning:
    Found GPU0 Quadro K1000M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Found 1 GPUs available. Using GPU 0 (Quadro K1000M) of compute capability 3.0 with 2.1Gb total memory.

Preparing the encoder, the synthesizer and the vocoder...
Traceback (most recent call last):
  File "D:\VoiceCloning\Real-Time-Voice-Cloning-master\demo_cli.py", line 61, in <module>
    encoder.load_model(args.enc_model_fpath)
  File "D:\VoiceCloning\Real-Time-Voice-Cloning-master\encoder\inference.py", line 33, in load_model
    checkpoint = torch.load(weights_fpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 385, in load
    f = f.open('rb')
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 1186, in open
    opener=self._opener)
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'encoder\\saved_models\\pretrained.pt'

(base) C:\Users\tester>

**Comment by CorentinJ** [comment]
You're not executing from the repo root, cd into it.

**Comment by testownik21** [comment]
When starting from project dir, there is 
RuntimeError: CUDA error: no kernel image is available for execution on the device

Is this related to GPU warning?

CUDA v10.0 is installed in 'NVIDIA GPU Computing Toolkit' folder.
System info in NVidia driver shows: NVCUDA.DLL || 25.21.14.1678 || NVIDIA CUDA 10.0.132 driver

```
(base) D:\VoiceCloning\Real-Time-Voice-Cloning-master>python demo_cli.py
WARNING:tensorflow:From D:\VoiceCloning\Real-Time-Voice-Cloning-master\synthesizer\models\modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_dir:     synthesizer\saved_models\logs-pretrained
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    low_mem:           False
    no_sound:          False

Running a test of your configuration...

C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py:118: UserWarning:
    Found GPU0 Quadro K1000M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Found 1 GPUs available. Using GPU 0 (Quadro K1000M) of compute capability 3.0 with 2.1Gb total memory.

Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "pretrained.pt" trained to step 1564501
Found synthesizer "pretrained" trained to step 278000
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt
Testing your configuration with small inputs.
        Testing the encoder...
Traceback (most recent call last):
  File "demo_cli.py", line 76, in <module>
    encoder.embed_utterance(np.zeros(encoder.sampling_rate))
  File "D:\VoiceCloning\Real-Time-Voice-Cloning-master\encoder\inference.py", line 147, in embed_utterance
    partial_embeds = embed_frames_batch(frames_batch)
  File "D:\VoiceCloning\Real-Time-Voice-Cloning-master\encoder\inference.py", line 55, in embed_frames_batch
    embed = _model.forward(frames).detach().cpu().numpy()
  File "D:\VoiceCloning\Real-Time-Voice-Cloning-master\encoder\model.py", line 56, in forward
    embeds_raw = self.relu(self.linear(hidden[-1]))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\activation.py", line 99, in forward
    return F.relu(input, inplace=self.inplace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py", line 943, in relu
    result = torch.relu(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device

(base) D:\VoiceCloning\Real-Time-Voice-Cloning-master>

**Comment by CorentinJ** [comment]
I don't know, check that your pytorch install works first.

**Comment by johndonderry** [comment]
[
![error](https://user-images.githubusercontent.com/56107616/66253734-6e2eab00-e721-11e9-9704-3c9e92a1cbc0.PNG)
](url)### 
a similar error to this commit,
i did cd into the root directory of repo with runas admin,
the error remains connstant but the location of the file missing changes everytime i rerun the encode_train.

**Comment by CorentinJ** [comment]
You need to add a backslash after the colon for the drive, and I think you're passing the wrong directory. Should be `E:\dataset` or `E:\dataset\VoxCeleb1`

**Comment by johndonderry** [comment]
the error remains the same, could not find _sources.txt, but every time i rerun the target location of the error directory is diif.
tried both of your recommended paths.
![error2](https://user-images.githubusercontent.com/56107616/66254202-f31cc300-e727-11e9-918c-387a9cbcb509.PNG)

**Comment by johndonderry** [comment]
[
![dir](https://user-images.githubusercontent.com/56107616/66254396-8bb44280-e72a-11e9-8f06-ed31c01bb881.PNG)
](url)
directory of the dataset folder in E drive, after successfully running encoder_preprocess...

**Comment by johndonderry** [comment]
i am still struggling with the same error. if any help be provided, i shall be highly thankfull.
