### ISSUE TITLE
Call to cuInit results in CUDA_ERROR_NOT_INITIALIZED:

### ISSUE THREAD

**Issue by ichhabkeinbock** [CorentinJ/Real-Time-Voice-Cloning#148]
Trying to setup your Voice-Cloning Tool, I get this error:
```
WARNING:tensorflow:From /home/ubuntu/Schreibtisch/Real-Time-Voice-Cloning/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Arguments:
    enc_model_fpath:   encoder/saved_models/pretrained.pt
    syn_model_dir:     synthesizer/saved_models/logs-pretrained
    voc_model_fpath:   vocoder/saved_models/pretrained/pretrained.pt
    low_mem:           False
    no_sound:          True

Running a test of your configuration...

/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py:132: UserWarning:
    Found GPU0 GeForce GTX 760 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Found 1 GPUs available. Using GPU 0 (GeForce GTX 760) of compute capability 3.0 with 2.1Gb total memory.

Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "pretrained.pt" trained to step 1564501
Found synthesizer "pretrained" trained to step 278000
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder/saved_models/pretrained/pretrained.pt
Testing your configuration with small inputs.
        Testing the encoder...
Traceback (most recent call last):
  File "demo_cli.py", line 76, in <module>
    encoder.embed_utterance(np.zeros(encoder.sampling_rate))
  File "/home/ubuntu/Schreibtisch/Real-Time-Voice-Cloning/encoder/inference.py", line 147, in embed_utterance
    partial_embeds = embed_frames_batch(frames_batch)
  File "/home/ubuntu/Schreibtisch/Real-Time-Voice-Cloning/encoder/inference.py", line 55, in embed_frames_batch
    embed = _model.forward(frames).detach().cpu().numpy()
  File "/home/ubuntu/Schreibtisch/Real-Time-Voice-Cloning/encoder/model.py", line 53, in forward
    out, (hidden, cell) = self.lstm(utterances, hidden_init)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 564, in forward
    return self.forward_tensor(input, hx)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 543, in forward_tensor
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 526, in forward_impl
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

```
This raises, when I'm trying to execute the script demo_cli.py with the --low_mem argument, as well as without. 
Do you know why this happens, or what I can do to avoid this error?
It works till loading the checkpoints, than this message raises.

All libraries and dependencies seem to be installed, cause pytorch/torch/torchvision are working, as well as the CUDA test scripts and the nvidia-cuda drivers.

Does the non-supported Nvidia GTX 760 causes my problems?
If it is, it's sad, cause it's the only Nvidia GPU available.

Hopefully, anyone has an answer to me.
Best Regards,

**Comment by CorentinJ** [comment]
#36
