### ISSUE TITLE
cuda runtime error

### ISSUE THREAD

**Issue by JimBarrOfficial** [CorentinJ/Real-Time-Voice-Cloning#152]
Ubuntu 18.04 running w/8GB RAM in VirtualBox on Windows 10.
I can start the program. I installed NVidia Cuda compiler driver:

jlb@UBUDT01:~/Real-Time-Voice-Cloning$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

Getting errors while attempting to clone anything:

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=50 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "/home/jlb/Real-Time-Voice-Cloning/toolbox/__init__.py", line 87, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "/home/jlb/Real-Time-Voice-Cloning/toolbox/__init__.py", line 187, in vocode
    self.init_vocoder()
  File "/home/jlb/Real-Time-Voice-Cloning/toolbox/__init__.py", line 249, in init_vocoder
    vocoder.load_model(model_fpath)
  File "/home/jlb/Real-Time-Voice-Cloning/vocoder/inference.py", line 25, in load_model
    mode=hp.voc_mode
  File "/home/jlb/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 311, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/jlb/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/jlb/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/jlb/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/jlb/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/jlb/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 311, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/jlb/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 179, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:50

Any ideas?
![cuda_error](https://user-images.githubusercontent.com/55903191/65821958-7dd25f00-e20a-11e9-9210-15d21e8bd194.jpg)

**Comment by gnfrazier** [comment]
At the terminal start a python repl
`python`
then

```
import torch
torch.cuda.is_available()
```

It should return true. If it is false try the pytorch pages to trouble shoot how to get CUDA enabled on your VM.

[https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/ )

**Comment by JimBarrOfficial** [comment]
Thanks.. I'm using an old NVIDIA FX580 card with minimal cores (pulled from an old system). Ubuntu sees the drivers, so no need to try and change them. I was working on this last evening but bagged it due to the late hour. I'll try again tonight. Any link to the correct CUDA driver? I'm not sure about v9 vs v10.

**Comment by AaravVihan** [comment]
i am have correct result with v9 patch 4. please check
best regards

**Comment by CorentinJ** [comment]
You won't manage to run it with your card
