### ISSUE TITLE
how to continue train the pretrained.pt model ?

### ISSUE THREAD

**Issue by maya413** [CorentinJ/Real-Time-Voice-Cloning#158]
any body knows ?
when i continue train the pretrained.pt model, 
i get this error 
Traceback (most recent call last):
  File "encoder_train.py", line 46, in <module>
    train(**vars(args))
  File "D:\py\clone_voice\encoder\train.py", line 68, in train
    for step, speaker_batch in enumerate(loader, init_step):
  File "D:\conda_env2\torch-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "D:\conda_env2\torch-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "D:\conda_env2\torch-gpu\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
Exception: Caught Exception in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\conda_env2\torch-gpu\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\conda_env2\torch-gpu\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\py\clone_voice\encoder\data_objects\speaker_verification_dataset.py", line 55, in collate
    return SpeakerBatch(speakers, self.utterances_per_speaker, partials_n_frames)
  File "D:\py\clone_voice\encoder\data_objects\speaker_batch.py", line 8, in __init__
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "D:\py\clone_voice\encoder\data_objects\speaker_batch.py", line 8, in <dictcomp>
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "D:\py\clone_voice\encoder\data_objects\speaker.py", line 34, in random_partial
    self._load_utterances()
  File "D:\py\clone_voice\encoder\data_objects\speaker.py", line 18, in _load_utterances
    self.utterance_cycler = RandomCycler(self.utterances)
  File "D:\py\clone_voice\encoder\data_objects\random_cycler.py", line 14, in __init__
    raise Exception("Can't create RandomCycler from an empty collection")
Exception: Can't create RandomCycler from an empty collection
if some one tell me the resolvtion , i will gratefully for you

**Comment by raanubis** [comment]
The error "Exception: Can't create RandomCycler from an empty collection" means that you has an empty folder in your DataSet folder

Download and install "Remove empty directories" from https://www.jonasjohn.de/red
