### ISSUE TITLE
error demo_cli.py

### ISSUE THREAD

**Issue by Stellarize** [CorentinJ/Real-Time-Voice-Cloning#160]
when runninf `python demo_cli.py` get this error : 

`Testing your configuration with small inputs.
	Testing the encoder...
Traceback (most recent call last):
  File "demo_cli.py", line 76, in <module>
    encoder.embed_utterance(np.zeros(encoder.sampling_rate))
  File "/home/kubutsushimuzan/Bureau/Real-Time-Voice-Cloning/encoder/inference.py", line 145, in embed_utterance
    frames = audio.wav_to_mel_spectrogram(wav)
  File "/home/kubutsushimuzan/Bureau/Real-Time-Voice-Cloning/encoder/audio.py", line 53, in wav_to_mel_spectrogram
    n_mels=mel_n_channels
  File "/home/kubutsushimuzan/.local/lib/python3.7/site-packages/librosa/feature/spectral.py", line 1391, in melspectrogram
    mel_basis = filters.mel(sr, n_fft, **kwargs)
  File "/home/kubutsushimuzan/.local/lib/python3.7/site-packages/librosa/filters.py", line 247, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,201) (0,) `

**Comment by raanubis** [comment]
did you installed all dependencies?

pip install requirements.txt     ?

**Comment by Stellarize** [comment]
yes i installed all the dependencies

**Comment by raanubis** [comment]
librosa version? 
if librosa <= 0.6.2 than update
the same with numpy
minimum numpy version 1.14.3

**Comment by Stellarize** [comment]
ok i'll try and make a feedback

**Comment by blue-fish** [comment]
Hi there @Stellarize . Would you kindly pull the latest version of the repo and try again? We have updated the codebase quite a bit in the last few weeks and are unable to troubleshoot errors on an old version of the toolbox.

**Comment by blue-fish** [comment]
Feel free the reopen this issue if you experience problems with the latest code.
