### ISSUE TITLE
FileNotFoundError training encoder

### ISSUE THREAD

**Issue by robrhapsody** [CorentinJ/Real-Time-Voice-Cloning#161]
I have gone through the preprocess for the encoder, which output the SV2TTS folder with each speaker in the individual folders. All do contain the _sources.txt.

When I begin the training, however, it gives an error stating that the _sources.txt file is not found.

`Traceback (most recent call last):
  File "encoder_train.py", line 46, in <module>
    train(**vars(args))
  File "F:\Python\venv\Repo\encoder\train.py", line 68, in train
    for step, speaker_batch in enumerate(loader, init_step):
  File "F:\Python\venv\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "F:\Python\venv\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "F:\Python\venv\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "F:\Python\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "F:\Python\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "F:\Python\venv\Repo\encoder\data_objects\speaker_verification_dataset.py", line 55, in collate
    return SpeakerBatch(speakers, self.utterances_per_speaker, partials_n_frames)
  File "F:\Python\venv\Repo\encoder\data_objects\speaker_batch.py", line 8, in __init__
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "F:\Python\venv\Repo\encoder\data_objects\speaker_batch.py", line 8, in <dictcomp>
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "F:\Python\venv\Repo\encoder\data_objects\speaker.py", line 34, in random_partial
    self._load_utterances()
  File "F:\Python\venv\Repo\encoder\data_objects\speaker.py", line 14, in _load_utterances
    with self.root.joinpath("_sources.txt").open("r") as sources_file:
  File "f:\python\Lib\pathlib.py", line 1165, in open
    opener=self._opener)
  File "f:\python\Lib\pathlib.py", line 1019, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Python\\venv\\Repo\\SV2TTS\\encoder\\_sources.txt'`

I have rerun the preprocessing but still get the same error. Do you know what could cause them to not be found?

**Comment by raanubis** [comment]
look in encoder_preprocess.py

especially the option:
    parser.add_argument("-o", "--out_dir", type=Path, default=argparse.SUPPRESS, help=\
        "Path to the output directory that will contain the mel spectrograms. If left out, "
        "defaults to <datasets_root>/SV2TTS/encoder/")

If you didn't specify your output directory, create the folder SV2TTS/encoder manually or improve the source code ;)

**Comment by blue-fish** [comment]
I fixed the command on the wiki for running the encoder training script. Someone reported a similar issue in #262.
