### ISSUE TITLE
cannot run demo_cli.py

### ISSUE THREAD

**Issue by rdrlima** [CorentinJ/Real-Time-Voice-Cloning#163]
Traceback (most recent call last):
  File "D:\Real-Time-Voice-Cloning-master\demo_cli.py", line 2, in <module>
    from utils.argutils import print_args
  File "D:\Real-Time-Voice-Cloning-master\utils\argutils.py", line 2, in <module>
    import numpy as np
  File "C:\Users\Rodrigo\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\Rodrigo\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Rodrigo\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
>>>

**Comment by Stellarize** [comment]
have you launch it in virtual environnement

**Comment by blue-fish** [comment]
@rdrlima It looks like you have 2 environments and they're causing a conflict with each other:
`C:\Users\Rodrigo\AppData\Roaming\Python\Python37\`
`C:\Users\Rodrigo\AppData\Local\Programs\Python\Python37\`

Please check your `PATH` and remove one of the environments. Of course the environment you keep still needs to have all of the requirements.

Very similar issue described here: https://github.com/pytorch/pytorch/issues/27693
