### ISSUE TITLE
`demo_cli` passes, and fail when running `demo_toolbox`

### ISSUE THREAD

**Issue by GantMan** [CorentinJ/Real-Time-Voice-Cloning#17]
I'm getting some kind of DLL load failed, which is probably unrelated to your project but the CLI check passed and is happens when I run toolbox.

```
PS C:\Users\gantm\Desktop\Code\ml\Real-Time-Voice-Cloning> python .\demo_toolbox.py
C:\Python36\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
C:\Python36\lib\site-packages\numpy\.libs\libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll
C:\Python36\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
  stacklevel=1)
Traceback (most recent call last):
  File "C:\Users\gantm\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\gantm\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\gantm\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\gantm\Desktop\Code\ml\Real-Time-Voice-Cloning\toolbox\__init__.py", line 3, in <module>
    from synthesizer import inference as synthesizer
  File "C:\Users\gantm\Desktop\Code\ml\Real-Time-Voice-Cloning\synthesizer\inference.py", line 1, in <module>
    from synthesizer.hparams import hparams
  File "C:\Users\gantm\Desktop\Code\ml\Real-Time-Voice-Cloning\synthesizer\hparams.py", line 1, in <module>
    from tensorflow.contrib.training import HParams
  File "C:\Users\gantm\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\gantm\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\gantm\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\gantm\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\gantm\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\gantm\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by CorentinJ** [comment]
Yes that's a tensorflow classic. It's a mismatch between your cuda or cudnn dll IIRC.

**Comment by yolonovikov** [comment]
how fix it?
