### ISSUE TITLE
ImportError: Failed to import any qt binding

### ISSUE THREAD

**Issue by dexbyte** [CorentinJ/Real-Time-Voice-Cloning#176]
`python demo_cli.py` works fine
However when I run `python demo_toolbox.py` it throws an error as follows: 

Traceback (most recent call last):
  File ".\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\dexbyte\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\dexbyte\Desktop\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 1, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "C:\Users\dexbyte\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "C:\Users\dexbyte\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\backends\backend_qt5.py", line 15, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\dexbyte\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 13, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "C:\Users\dexbyte\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\backends\qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding

**Comment by dexbyte** [comment]
Solved this by installing Visual Studio 2017, CUDA 10.0 and cuDNN. The demo_toolbox.py doesn't run in anaconda environment, so I installed all the dependency in the local python environment and everything works fine.
