### ISSUE TITLE
numba.errors.TypingError: Failed at nopython (Preprocessing for parfors) Invalid usage of Function(<function argsort at 0x7fc2a69a9ae8>) with parameters (array(float32, 1d, C), const('quicksort'))

### ISSUE THREAD

**Issue by randyadams2000** [CorentinJ/Real-Time-Voice-Cloning#177]
Traceback (most recent call last):
  File "/home/ubuntu/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 59, in <lambda>
    self.ui.browser_load_button.clicked.connect(lambda: self.load_from_browser())
  File "/home/ubuntu/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 122, in load_from_browser
    self.add_real_utterance(wav, name, speaker_name)
  File "/home/ubuntu/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 152, in add_real_utterance
    self.ui.draw_umap_projections(self.utterances)
  File "/home/ubuntu/Real-Time-Voice-Cloning-master/toolbox/ui.py", line 121, in draw_umap_projections
    projections = reducer.fit_transform(embeds)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/umap_learn-0.3.10-py3.6.egg/umap/umap_.py", line 1825, in fit_transform
    self.fit(X, y)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/umap_learn-0.3.10-py3.6.egg/umap/umap_.py", line 1625, in fit
    self.verbose,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/umap_learn-0.3.10-py3.6.egg/umap/umap_.py", line 559, in fuzzy_simplicial_set
    verbose=verbose,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/umap_learn-0.3.10-py3.6.egg/umap/umap_.py", line 232, in nearest_neighbors
    knn_indices = fast_knn_indices(X, n_neighbors)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in _compile_for_args
    reraise(type(e), e, None)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed at nopython (Preprocessing for parfors)
Invalid usage of Function(<function argsort at 0x7fc2a69a9ae8>) with parameters (array(float32, 1d, C), const('quicksort'))
 * parameterized
In definition 0:
    AssertionError: 
    raised from /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/typing/arraydecl.py:415
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by blue-fish** [comment]
@randyadams2000 The codebase has changed quite a bit in the last few weeks, it is not worthwhile for us to troubleshoot an issue reported 8 months ago. May I ask that you please pull the latest and see if your error is reproducible? Most likely it will just work. Good luck!
