### ISSUE TITLE
error when running "python demo_cli.py"

### ISSUE THREAD

**Issue by migueltopsp** [CorentinJ/Real-Time-Voice-Cloning#185]
I'm getting error when i run "python demo_cli.py", how can i fix it?

LOG:

D:\DeepFakeLab\Real-Time-Voice-Cloning-master>python demo_cli.py
C:\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "D:\DeepFakeLab\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "D:\DeepFakeLab\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "D:\DeepFakeLab\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "D:\DeepFakeLab\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 4, in <module>
    from synthesizer.models.helpers import TacoTrainingHelper, TacoTestHelper
  File "D:\DeepFakeLab\Real-Time-Voice-Cloning-master\synthesizer\models\helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
  File "C:\Python37\lib\site-packages\tensorflow\contrib\__init__.py", line 37, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "C:\Python37\lib\site-packages\tensorflow\contrib\cudnn_rnn\__init__.py", line 38, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "C:\Python37\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "C:\Python37\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "C:\Python37\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "C:\Python37\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 91, in <module>
    from tensorflow.contrib.rnn.python.ops.lstm_ops import *
  File "C:\Python37\lib\site-packages\tensorflow\contrib\rnn\python\ops\lstm_ops.py", line 298, in <module>
    @ops.RegisterGradient("BlockLSTM")
  File "C:\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 2489, in __call__
    _gradient_registry.register(f, self._op_type)
  File "C:\Python37\lib\site-packages\tensorflow_core\python\framework\registry.py", line 61, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register C:\\Python37\\lib\\site-packages\\tensorflow_core\\python\\framework\\registry.py:66)"

**Comment by JeffStodd** [comment]
Your tensorflow version might be incompatible

**Comment by blue-fish** [comment]
@migueltopsp Did you find a way to resolve this issue? If not would you please pull the latest version of the code, reinstall the requirements and try again? I expect it should resolve your problem. It does look like a tensorflow version issue, the current toolbox uses tensorflow 1.15.
