### ISSUE TITLE
File contains data in an unknown format.

### ISSUE THREAD

**Issue by jdtrotta** [CorentinJ/Real-Time-Voice-Cloning#198]
```
Traceback (most recent call last):
  File "/home/jdtrotta/Documents/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 77, in <lambda>
    func = lambda: self.load_from_browser(self.ui.browse_file())
  File "/home/jdtrotta/Documents/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 119, in load_from_browser
    wav = Synthesizer.load_preprocess_wav(fpath)
  File "/home/jdtrotta/Documents/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 111, in load_preprocess_wav
    wav = librosa.load(fpath, hparams.sample_rate)[0]
  File "/usr/local/lib/python3.6/dist-packages/librosa/core/audio.py", line 149, in load
    six.reraise(*sys.exc_info())
  File "/home/jdtrotta/.local/lib/python3.6/site-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/librosa/core/audio.py", line 129, in load
    with sf.SoundFile(path) as sf_desc:
  File "/usr/local/lib/python3.6/dist-packages/soundfile.py", line 627, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.6/dist-packages/soundfile.py", line 1182, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/usr/local/lib/python3.6/dist-packages/soundfile.py", line 1355, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/home/jdtrotta/Documents/Real-Time-Voice-Cloning-master/data/LibriSpeech/dev-clean/Episode 1 - Reality and The Sacred.m4a': File contains data in an unknown format.

```

Occurs whether the file is .mp3 or .m4a.

**Comment by nicovong** [comment]
I have the same problem, can you tell me what you did to solve this please ?
