### ISSUE TITLE
Error: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Hashnoob** [CorentinJ/Real-Time-Voice-Cloning#200]
**OS: WIN 10
GPU: GTX 780 3GB
CUDA: 10.0
cuDNN: v7.6.5 (November 5th, 2019), for CUDA 10.0**

I got everything installed but I keep getting this error, any thoughts?

`
Traceback (most recent call last):

File "C:\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 59, in <lambda>
    self.ui.browser_load_button.clicked.connect(lambda: self.load_from_browser())

File "C:\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 104, in load_from_browser
    self.ui.current_utterance_name)

File "C:\Users\ID\AppData\Local\Python\Python37\lib\pathlib.py", line 1010, in __new__
    self = cls._from_parts(args, init=False)

File "C:\Users\ID\AppData\Local\Python\Python37\lib\pathlib.py", line 665, in _from_parts
    drv, root, parts = self._parse_args(args)

File "C:\Users\ID\AppData\Local\Python\Python37\lib\pathlib.py", line 649, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Loaded encoder "pretrained.pt" trained to step 1564501
Traceback (most recent call last):

File "C:\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 77, in <lambda>
    func = lambda: self.load_from_browser(self.ui.browse_file())

File "C:\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 122, in load_from_browser
    self.add_real_utterance(wav, name, speaker_name)

File "C:\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 143, in add_real_utterance
    embed, partial_embeds, _ = encoder.embed_utterance(encoder_wav, return_partials=True)

File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 147, in embed_utterance
    partial_embeds = embed_frames_batch(frames_batch)

File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 55, in embed_frames_batch
    embed = _model.forward(frames).detach().cpu().numpy()

File "C:\Real-Time-Voice-Cloning-master\encoder\model.py", line 53, in forward
    out, (hidden, cell) = self.lstm(utterances, hidden_init)

File "C:\Users\ID\AppData\Local\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)

File "C:\Users\ID\AppData\Local\Python\Python37\lib\site-packages\torch\nn\modules\rnn.py", line 564, in forward
    return self.forward_tensor(input, hx)

File "C:\Users\ID\AppData\Local\Python\Python37\lib\site-packages\torch\nn\modules\rnn.py", line 543, in forward_tensor
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)

File "C:\Users\ID\AppData\Local\Python\Python37\lib\site-packages\torch\nn\modules\rnn.py", line 526, in forward_impl
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA error: no kernel image is available for execution on the device
`

**Comment by fcolecumberri** [comment]
how did you solve it?

**Comment by jineshforever** [comment]
please reply.. tell how you solved it.. please

**Comment by coolcraftnet18** [comment]
Some kinda requirement version issue?
