### ISSUE TITLE
Can't run deno_cli or demo_toolbox

### ISSUE THREAD

**Issue by jnortheastfilms** [CorentinJ/Real-Time-Voice-Cloning#208]
Hey,
I installed python 3.7. I installed all the requirements.txt with pip. i install pytorch. I install Microsoft C+ build tools. I installed CUDA 10. I rebooted. But both these scripts dont run.

**deno_cli error** 

`Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "A:\Users\Jnortheast\Desktop\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "A:\Users\Jnortheast\Desktop\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "A:\Users\Jnortheast\Desktop\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "A:\Users\Jnortheast\Desktop\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\BigRed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\BigRed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\BigRed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\BigRed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive`

**demo_toolbox.py**

`Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "A:\Users\Jnortheast\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "A:\Users\Jnortheast\Desktop\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 1, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "C:\Users\BigRed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "C:\Users\BigRed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\backends\backend_qt5.py", line 15, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\BigRed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 13, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "C:\Users\BigRed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\backends\qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding`

Running Windows 10, Nvidia 2070.

Would love some help!
Cheers,
Josh

**Comment by futurityab** [comment]
Hi Josh, you seem to have two issues which are not strictly related to this repository.
The first indicates that you are missing an enviroment path needed by Tensorflow;
_ImportError: Could not find 'cudart64_100.dll'._

The second issue indicates you are missing qt; check with a pip list to make sure all the requirements are properly installed.
_Failed to import any qt binding_

Hope it helps,
BR Fred

**Comment by shashi007** [comment]
> ImportError: Could not find 'cudart64_100.dll'.
To solve this install NVIDIA cuDNN, For the other problem follow what futurityab said.

**Comment by SpeedOfSpin** [comment]
With Tensorflow 1.14 I couldn't get CUDA10 to work. I already hyad CUDA10  9.0 installed so I installed tensorflow 1.10 and I could then get the test to pass.

**Comment by Port0r** [comment]
With Tensorflow 1.14 make sure you have **CUDA 10.0**, not CUDA 10.1
Make sure the CUDA-path is listed in your PATH environment variable!

The next error will instruct you to install cuDNN. Make sure you take a version specifically for CUDA 10.0

Next up is PyTorch. The website doesn't directly offer older versions. Install via pip:
`pip install torch==1.2.0 torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by blue-fish** [comment]
Closing this item because these issues are not strictly related to this repository.
