### ISSUE TITLE
audioread.NoBackendError

### ISSUE THREAD

**Issue by josai** [CorentinJ/Real-Time-Voice-Cloning#21]
```
Traceback (most recent call last):
  File "C:\Users\The Atomizer\Desktop\text\voice\voice\toolbox\__init__.py", line 52, in <lambda>
    self.ui.browser_load_button.clicked.connect(lambda: self.load_from_browser())
  File "C:\Users\The Atomizer\Desktop\text\voice\voice\toolbox\__init__.py", line 110, in load_from_browser
    wav = Synthesizer.load_preprocess_wav(fpath)
  File "C:\Users\The Atomizer\Desktop\text\voice\voice\synthesizer\inference.py", line 111, in load_preprocess_wav
    wav = librosa.load(fpath, hparams.sample_rate)[0]
  File "C:\Users\The Atomizer\Miniconda3\envs\voice\lib\site-packages\librosa\core\audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\Users\The Atomizer\Miniconda3\envs\voice\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError
```

When clicking Load in the GUI

**Comment by fazlekarim** [comment]
You need ffmpeg installed

**Comment by josai** [comment]
your right that worked!
