### ISSUE TITLE
audioread.exceptions.NoBackendError

### ISSUE THREAD

**Issue by sdx0112** [CorentinJ/Real-Time-Voice-Cloning#22]
Traceback (most recent call last):
  File "D:\sdx\DeepFake\voice\Real-Time-Voice-Cloning\toolbox\__init__.py", line 70, in <lambda>
    func = lambda: self.load_from_browser(self.ui.browse_file())
  File "D:\sdx\DeepFake\voice\Real-Time-Voice-Cloning\toolbox\__init__.py", line 110, in load_from_browser
    wav = Synthesizer.load_preprocess_wav(fpath)
  File "D:\sdx\DeepFake\voice\Real-Time-Voice-Cloning\synthesizer\inference.py", line 111, in load_preprocess_wav
    wav = librosa.load(fpath, hparams.sample_rate)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\ProgramData\Anaconda3\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError

I have installed ffmpeg, but still get this error.

**Comment by fazlekarim** [comment]
You need to set the paths and all of that correctly. Type "ffmpeg -version" on your cmd prompt. If that is running then you installed ffmpeg correctly. Installing ffmpeg on windows in annoying.

**Comment by sdx0112** [comment]
Issue solved. Thanks for your advice.
