### ISSUE TITLE
Cuda out of memory? Wrong CuDNN version?

### ISSUE THREAD

**Issue by bondyfan** [CorentinJ/Real-Time-Voice-Cloning#229]
Hello,

When I run demo_cli.py I get this error:

  ```
Testing the vocoder...
Traceback (most recent call last):
  File "demo_cli.py", line 105, in <module>
    vocoder.infer_waveform(mel, target=200, overlap=50, progress_callback=no_action)
  File "C:\Users\Bondyfan\Desktop\Real-Time-Voice-Cloning-master\vocoder\inference.py", line 57, in infer_waveform
    wav = _model.generate(mel, batched, target, overlap, hp.mu_law, progress_callback)
  File "C:\Users\Bondyfan\Desktop\Real-Time-Voice-Cloning-master\vocoder\models\fatchord_version.py", line 167, in generate
    aux = self.fold_with_overlap(aux, target, overlap)
  File "C:\Users\Bondyfan\Desktop\Real-Time-Voice-Cloning-master\vocoder\models\fatchord_version.py", line 309, in fold_with_overlap
    folded = torch.zeros(num_folds, target + 2 * overlap, features).cuda()
RuntimeError: CUDA out of memory. Tried to allocate 80.00 MiB (GPU 0; 2.00 GiB total capacity; 204.31 MiB already allocated; 49.99 MiB free; 33.69 MiB cached)
```

When I try to to run it with --low_mem I get this:

```
E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.2.1 but source was compiled with: 7.4.1.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2019-11-23 09:00:03.457756: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.2.1 but source was compiled with: 7.4.1.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "demo_cli.py", line 90, in <module>
    mels = synthesizer.synthesize_spectrograms(texts, embeds)
  File "C:\Users\Bondyfan\Desktop\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 84, in synthesize_spectrograms
    [(self.checkpoint_fpath, embeddings, texts)])[0]
  File "C:\Users\Bondyfan\AppData\Local\Programs\Python\Python37\lib\site-packages\multiprocess\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Bondyfan\AppData\Local\Programs\Python\Python37\lib\site-packages\multiprocess\pool.py", line 657, in get
    raise self._value
multiprocess.pool.MaybeEncodingError: Error sending result: '<multiprocess.pool.ExceptionWithTraceback object at 0x000001D5D608D438>'. Reason: 'TypeError("can't pickle SwigPyObject objects")'
```

What could be wrong?

Thanks

**Comment by Artem-B** [comment]
Re: cudnn version mismatch. It appears that torch package carries its own copy of cudnn library which happens to be found before the cudnn library which comes from cudnn package and it happens to be not the version that tensorflow is looking for.  
I've managed to work around that by removing `site-packages\torch\lib\off\cudnn64_7.dll` so there's only one cudnn variant that can be found in `Library\bin\cudnn64_7.dll`. Torch didn't seem to complain and tensorflow is happy now, too.

**Comment by TOBACCOCN** [comment]
I met the same question when I run demo_cli.py, have you solve it yet

**Comment by blue-fish** [comment]
A GPU is no longer required to run the toolbox. Please try again after pulling the latest code and ensuring you have the packages in requirements.txt. The code has changed a bit recently and I don't expect we have much to gain by troubleshooting this issue, so I am closing it.
