### ISSUE TITLE
Could not Find 'cudnn64_7.dll'  (yet I have it installed)

### ISSUE THREAD

**Issue by sebbiee** [CorentinJ/Real-Time-Voice-Cloning#231]
CUDA Toolkit 10.0 (Sept 2018)

cuDNN v7.6.5 (November 5th, 2019), for CUDA 10.0 

pip install torch==1.2.0 torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

I tried downloading cuDDN again yet its not working heres what it says:
Traceback (most recent call last):
 " File "C:\Users\sebka\Real-Time-Voice-Cloning\demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\sebka\Real-Time-Voice-Cloning\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Users\sebka\Real-Time-Voice-Cloning\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Users\sebka\Real-Time-Voice-Cloning\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Users\sebka\Real-Time-Voice-Cloning\synthesizer\models\tacotron.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\sebka\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\sebka\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\sebka\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\sebka\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\self_check.py", line 97, in preload_check
    % (build_info.cudnn_dll_name, build_info.cudnn_version_number))
ImportError: Could not find 'cudnn64_7.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 7 from this URL: https://developer.nvidia.com/cudnn"

**Comment by sebbiee** [comment]
I figured it out I installed cudnn incorrectly
