### ISSUE TITLE
Error 0x7e / OSError: sndfile library not found 

### ISSUE THREAD

**Issue by Dammley** [CorentinJ/Real-Time-Voice-Cloning#270]
ive ran into some problems that i managed to fix and i thought everything was done , now when i run `python demo_toolbox.py` 
i get this problem: 

`C:\Users\n4mei\Real-Time-Voice-Cloning-master>python demo_toolbox.py
Traceback (most recent call last):
  File "C:\Users\n4mei\AppData\Local\Programs\Python\Python37\lib\site-packages\soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\n4mei\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\n4mei\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 5, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "C:\Users\n4mei\Real-Time-Voice-Cloning-master\encoder\inference.py", line 3, in <module>
    from encoder.audio import preprocess_wav   # We want to expose this function from here
  File "C:\Users\n4mei\Real-Time-Voice-Cloning-master\encoder\audio.py", line 7, in <module>
    import librosa
  File "C:\Users\n4mei\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\n4mei\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\__init__.py", line 126, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "C:\Users\n4mei\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 10, in <module>
    import soundfile as sf
  File "C:\Users\n4mei\AppData\Local\Programs\Python\Python37\lib\site-packages\soundfile.py", line 163, in <module>
    _path, '_soundfile_data', _libname))
OSError: cannot load library 'C:\Users\n4mei\AppData\Local\Programs\Python\Python37\lib\site-packages\_soundfile_data\libsndfile64bit.dll': error 0x7e`

I cant find a thread with a similar problem please help

**Comment by arunasank** [comment]
Install libsndfile1, libsndfile1-dev on Linux (They are system packages not python packages)

**Comment by blue-fish** [comment]
You need to install libsndfile to make it work. http://www.mega-nerd.com/libsndfile/#Download
