### ISSUE TITLE
TensorFlow can't find cudart64_100.dll in Cuda Path

### ISSUE THREAD

**Issue by Ixiplious** [CorentinJ/Real-Time-Voice-Cloning#271]
`Traceback (most recent call last):
  File "C:\Users\Name\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\Name\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Name\Desktop\All\Spook\Real-Time-Voice-Cloning-master\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\Name\Desktop\All\Spook\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\Name\Desktop\All\Spook\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Users\Name\Desktop\All\Spook\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Users\Name\Desktop\All\Spook\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Users\Name\Desktop\All\Spook\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Name\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Name\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Name\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\Name\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive`

I'm fairly new to deep learning/ai so I've been interested in this project for a while. I've been following the instructions on https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/ to install this correctly, but I keep getting the error above. Any tips help.

Additionally,  I don't get any of these error when I run it the intended way:
`>python demo_toolbox.py`

instead, it just runs and closes immediately. The only way to get it to do anything is just by typing:
`>demo_toolbox.py`

which gives me the above error.

Sorry for the trouble, and thanks for the help.

**Comment by Ixiplious** [comment]
Fixed. I re-downloaded cuDNN, and replaced the files in the path listed in the link above.

**Comment by blue-fish** [comment]
@Ixiplious I'm glad that it's working for you now. Thanks for sharing your solution.
