### ISSUE TITLE
Import Helper Issue

### ISSUE THREAD

**Issue by ThatOneGuy2259** [CorentinJ/Real-Time-Voice-Cloning#274]
Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\kille\Desktop\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Users\kille\Desktop\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Users\kille\Desktop\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Users\kille\Desktop\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 4, in <module>
    from synthesizer.models.helpers import TacoTrainingHelper, TacoTestHelper
  File "C:\Users\kille\Desktop\Real-Time-Voice-Cloning-master\synthesizer\models\helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
**ImportError: cannot import name 'Helper' from 'tensorflow.contrib.seq2seq' (unknown location)**

Not too sure what the issue is and why it can't locate it. Any help?

**Comment by blue-fish** [comment]
You need to install tensorflow 1.15 . I would recommend pulling the latest code from the repo while you are at it. If this does not solve your problem please reopen the issue.
