### ISSUE TITLE
Errorno 111

### ISSUE THREAD

**Issue by AmitBDA** [CorentinJ/Real-Time-Voice-Cloning#281]
during training the encoder I have faced an error 111. and the error massage is ,
Traceback (most recent call last):
  File "/home/sysadm/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/sysadm/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/sysadm/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

Can anyone tell me what is the actual issue ?

**Comment by AmitBDA** [comment]
issue solved.
