### ISSUE TITLE
during Encoder train， MemoryError happened sometimes

### ISSUE THREAD

**Issue by maemoKKK** [CorentinJ/Real-Time-Voice-Cloning#288]
Hi， 

below is log：
Average execution time over 10 steps:
  Blocking, waiting for batch (threaded) (10/10):  mean: 8459ms   std: 16934ms
  Data to cuda (10/10):                            mean:    8ms   std:    6ms
  Forward pass (10/10):                            mean:    7ms   std:    3ms
  Loss (10/10):                                    mean:   74ms   std:    8ms
  Backward pass (10/10):                           mean:  232ms   std:   10ms
  Parameter update (10/10):                        mean:   71ms   std:    6ms
  Extras (visualizations, saving) (10/10):         mean:  584ms   std: 1753ms

..........
Step    310   Loss: 2.7407   EER: 0.1718   Step time:  mean:  9797ms  std: 16272ms

Average execution time over 10 steps:
  Blocking, waiting for batch (threaded) (10/10):  mean: 8824ms   std: 15893ms
  Data to cuda (10/10):                            mean:    8ms   std:    6ms
  Forward pass (10/10):                            mean:    6ms   std:    0ms
  Loss (10/10):                                    mean:   76ms   std:   10ms
  Backward pass (10/10):                           mean:  225ms   std:   10ms
  Parameter update (10/10):                        mean:   74ms   std:    8ms
  Extras (visualizations, saving) (10/10):         mean:    2ms   std:    6ms

Traceback (most recent call last):
  File "D:\Anaconda3\envs\RTVD\lib\multiprocessing\queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "D:\Anaconda3\envs\RTVD\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError
..Traceback (most recent call last):
  File "encoder_train.py", line 46, in <module>
    train(**vars(args))
  File "E:\RTVC\encoder\train.py", line 70, in train
    for step, speaker_batch in enumerate(loader, init_step):
  File "D:\Anaconda3\envs\RTVD\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "D:\Anaconda3\envs\RTVD\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\RTVD\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
MemoryError: Caught MemoryError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\RTVD\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\RTVD\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "E:\RTVC\encoder\data_objects\speaker_verification_dataset.py", line 55, in collate
    return SpeakerBatch(speakers, self.utterances_per_speaker, partials_n_frames)
  File "E:\RTVC\encoder\data_objects\speaker_batch.py", line 8, in __init__
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "E:\RTVC\encoder\data_objects\speaker_batch.py", line 8, in <dictcomp>
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "E:\RTVC\encoder\data_objects\speaker.py", line 38, in random_partial
    a = [(u,) + u.random_partial(n_frames) for u in utterances]
  File "E:\RTVC\encoder\data_objects\speaker.py", line 38, in <listcomp>
    a = [(u,) + u.random_partial(n_frames) for u in utterances]
  File "E:\RTVC\encoder\data_objects\utterance.py", line 20, in random_partial
    frames = self.get_frames()
  File "E:\RTVC\encoder\data_objects\utterance.py", line 10, in get_frames
    return np.load(self.frames_fpath)
  File "D:\Anaconda3\envs\RTVD\lib\site-packages\numpy\lib\npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "D:\Anaconda3\envs\RTVD\lib\site-packages\numpy\lib\format.py", line 704, in read_array
    array = numpy.fromfile(fp, dtype=dtype, count=count)
MemoryError

hardware: CPU memory 32G, GPU memory 12G, 
analysis：
maybe something wrong with DataLoader. 
collate_fn in DataLoader is used for provide a way to deal with dataset ( just deal with, not create), however, our code use return np.load(self.frames_fpath)  in Utterance.py line 10.

 it means dataset just provide a filepath, the payload is created in DataLoader. As a result, the CPU memory is creased from 15GB to 32GB, and then MemoryError happened

is it becaused by memory in DataLoader  not be released?

**Comment by kangcp** [comment]
Hi, I also encountered this problem, my machine memory is 256G, but also MemoryError, did you solve this problem?

**Comment by blue-fish** [comment]
Closing issue due to inactivity. We are training a new encoder (#458) and will be vigilant for this problem.
