### ISSUE TITLE
please , solve this problem ..

### ISSUE THREAD

**Issue by IronSharkAdi** [CorentinJ/Real-Time-Voice-Cloning#316]
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "/home/adi/Downloads/real-time-weibel-master/toolbox/__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "/home/adi/Downloads/real-time-weibel-master/toolbox/ui.py", line 57
    def draw_utterance(self, utterance: Utterance, which):
                                      ^
SyntaxError: invalid syntax

**Comment by arongamer69** [comment]
you typed somthing wrong

**Comment by blue-fish** [comment]
Not enough info to troubleshoot. Please provide more details about your problem and reopen the issue.
