### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by meme-lord** [CorentinJ/Real-Time-Voice-Cloning#321]
Thought I was close to a working install when I ran into this error. There isn't much relevant information from my searches on the problem. Normally this occurs when your GPU driver isnt new enough but I have the newest driver installed and it is CUDA 10 compatible yet I'm getting this error.
```
Windows 10
CUDA Version          ( 10.0 )
CudNN Version        ( 7.6.5 )
Torch version           ( 1.2.0 )
torchvision	       ( 0.4.1 )
Tensorflow Version  ( 1.14.0 ) - also tried 1.13.1, 1.13.2
GPU Driver Version - GeForce Game Ready Driver 445.75
```

```
$ nvcc.exe --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130
```
```
C:\Program Files\NVIDIA Corporation\NVSMI>nvidia-smi.exe
Mon Apr 13 21:00:16 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 445.75       Driver Version: 445.75       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080   WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   38C    P8     6W /  N/A |   1246MiB /  8192MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
```
```
python demo_cli.py

SKIPPING A BUNCH OF OUTPUT

Traceback (most recent call last):
  File "demo_cli.py", line 91, in <module>
    mels = synthesizer.synthesize_spectrograms(texts, embeds)
  File "C:\Users\User\Desktop\Real-Time-Voice-Cloning\synthesizer\inference.py", line 77, in synthesize_spectrograms
    self.load()
  File "C:\Users\User\Desktop\Real-Time-Voice-Cloning\synthesizer\inference.py", line 58, in load
    self._model = Tacotron2(self.checkpoint_fpath, hparams)
  File "C:\Users\User\Desktop\Real-Time-Voice-Cloning\synthesizer\tacotron2.py", line 59, in __init__
    self.session = tf.Session(config=config)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1570, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\client\session.py", line 693, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
```

Any help appreciated.

**Comment by blue-fish** [comment]
Ok, I am going to presume that you just want to try out the toolbox. If this is the case then pull the latest code with CPU support, update your requirements and you should be good to go without figuring out the CUDA driver/runtime issue.

If you need the GPU speedup then I am afraid that this kind of troubleshooting is outside the scope of the issues here. You would need to find a more appropriate support channel for that.
