### ISSUE TITLE
TypeError on line 114 of \synthesizer\models\odules.py (pusalieth fork)

### ISSUE THREAD

**Issue by darovic** [CorentinJ/Real-Time-Voice-Cloning#337]
I'm receiving the following error attempting to run demo_cli.py. It does not occur on the upstream build.

```
Traceback (most recent call last):
  File ".\demo_cli.py", line 96, in <module>
    mels = synthesizer.synthesize_spectrograms(texts, embeds)
  File "C:\Users\damir\Desktop\Real-Time-Voice-Cloning\synthesizer\inference.py", line 77, in synthesize_spectrograms
    self.load()
  File "C:\Users\damir\Desktop\Real-Time-Voice-Cloning\synthesizer\inference.py", line 58, in load
    self._model = Tacotron2(self.checkpoint_fpath, hparams)
  File "C:\Users\damir\Desktop\Real-Time-Voice-Cloning\synthesizer\tacotron2.py", line 28, in __init__
    split_infos=split_infos)
  File "C:\Users\damir\Desktop\Real-Time-Voice-Cloning\synthesizer\models\tacotron.py", line 150, in initialize
    zoneout=hp.tacotron_zoneout_rate, scope="encoder_LSTM"))
  File "C:\Users\damir\Desktop\Real-Time-Voice-Cloning\synthesizer\models\modules.py", line 222, in __init__
    name="encoder_fw_LSTM")
  File "C:\Users\damir\Desktop\Real-Time-Voice-Cloning\synthesizer\models\modules.py", line 114, in __init__
    self._cell = tf.contrib.cudnn_rnn.CudnnLSTM(num_units, name=name)
TypeError: __init__() missing 1 required positional argument: 'num_units'
```

I am running:
- Windows 10 1909 build 18363.720
- Python 3.7.6
- conda 4.8.3
- pip 20.0.2
- pytorch 1.2.0
- CUDA 10.0.

conda info output is as follows:
```
(base) PS C:\Users\damir\Desktop\Real-Time-Voice-Cloning> conda info

     active environment : base
    active env location : C:\Users\damir\miniconda3
            shell level : 1
       user config file : C:\Users\damir\.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : C:\Users\damir\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\damir\miniconda3\pkgs
                          C:\Users\damir\.conda\pkgs
                          C:\Users\damir\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\damir\miniconda3\envs
                          C:\Users\damir\.conda\envs
                          C:\Users\damir\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by ninaburns** [comment]
I have this problem too!  Were you able to figure out why?  My conda info is:

```     active environment : forktts
    active env location : /data/nburns/anaconda3/envs/forktts
            shell level : 2
       user config file : /home/nburns/.condarc
 populated config files : /home/nburns/.condarc
          conda version : 4.8.3
    conda-build version : 3.15.1
         python version : 3.7.2.final.0
       virtual packages : __cuda=10.1
                          __glibc=2.17
       base environment : /data/nburns/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data/nburns/anaconda3/pkgs
                          /home/nburns/.conda/pkgs
       envs directories : /data/nburns/anaconda3/envs
                          /home/nburns/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.19.1 CPython/3.7.2 Linux/3.10.0-862.14.4.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 31602:5000
             netrc file : None
           offline mode : False
```

**Comment by me16io** [comment]
see my fix for this error [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/344).
