### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by AndrejHatzi** [CorentinJ/Real-Time-Voice-Cloning#341]
I have successfully installed Tensorflow but this library which is not in use anymore "contrib" prevents me from running demo_cli.py

```
I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\Jean-Paul Sartre\Downloads\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Users\Jean-Paul Sartre\Downloads\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Users\Jean-Paul Sartre\Downloads\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Users\Jean-Paul Sartre\Downloads\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 4, in <module>
    from synthesizer.models.helpers import TacoTrainingHelper, TacoTestHelper
  File "C:\Users\Jean-Paul Sartre\Downloads\Real-Time-Voice-Cloning-master\synthesizer\models\helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by t-qureshi** [comment]
Hi @AndrejHatzi , plz change your tensorflow version to 1.14.

**Comment by PortStone** [comment]
@t-qureshi That's sadly not possible.

```
pip install tensorflow-gpu==1.14.0
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow-gpu==1.14.0
```

**Comment by PortStone** [comment]
@t-qureshi getting the following:

```
pip install tensorflow==1.14.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow==1.14.0

```

**Comment by schematical** [comment]
I installed 1.14 from the github release https://github.com/tensorflow/tensorflow/releases/tag/v1.14.0 and I still get this error. Any ideas?

**Comment by mvdream** [comment]
First uninstalled tensorflow versions like tensorflow and tensorflow-gpu. 
Then install tensorflow like
 `pip3 install tensorflow==1.14.0.`
Its work for me.

**Comment by blue-fish** [comment]
Looks to be resolved, feel free to reopen if the issue persists.
