### ISSUE TITLE
ModuleNotFoundError: No module named 'Unidecode'

### ISSUE THREAD

**Issue by Miserness974** [CorentinJ/Real-Time-Voice-Cloning#342]
Can not run the demo_cli.py due to the fact that the python don't see unidecode. 
`Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "/Users/user/Downloads/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "/Users/user/Downloads/Real-Time-Voice-Cloning-master/synthesizer/tacotron2.py", line 1, in <module>
    from synthesizer.utils.text import text_to_sequence
  File "/Users/user/Downloads/Real-Time-Voice-Cloning-master/synthesizer/utils/text.py", line 2, in <module>
    from . import cleaners
  File "/Users/user/Downloads/Real-Time-Voice-Cloning-master/synthesizer/utils/cleaners.py", line 14, in <module>
    from Unidecode import unidecode
ModuleNotFoundError: No module named 'Unidecode'`

But when I do `pip3 list `, there is Unidecode in it (version 1.1.1)
I am using a Mac and python 3.

**Comment by Haven-Net** [comment]
pip install unidecode

**Comment by blue-fish** [comment]
I am not sure what happened with your copy of the repo, but you can see that it is referenced as `unidecode` with proper capitalization.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/f6fabeaf3effdf2f023db98b37bdabd1ec3d81e5/synthesizer/utils/cleaners.py#L14

Make your 14 of synthesizer/utils/cleaners.py match this and it will resolve the issue.
