### ISSUE TITLE
Running the demo_cli.py and demo_toolbox.py see this error (after training encode and synthesizer). Any one?

### ISSUE THREAD

**Issue by goodmangu** [CorentinJ/Real-Time-Voice-Cloning#383]
This is the error in the demo_toolbox:

ValueError: Variable Tacotron_model/inference/inputs_embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

Complete info:

(voice) goodman@goodman-dl-box:~/development/Real-Time-Voice-Cloning-master$ python demo_toolbox.py -d datasets/
Arguments:
    datasets_root:    datasets
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    low_mem:          False

Gtk-Message: 20:10:02.221: GtkDialog mapped without a transient parent. This is discouraged.
Loaded encoder "my_run.pt" trained to step 219501
Found synthesizer "pretrained" trained to step 278000
Constructing model: Tacotron
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:424: conv1d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv1D` instead.
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/layers/convolutional.py:218: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:425: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:428: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:238: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/rnn.py:464: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/contrib/rnn/python/ops/lstm_ops.py:360: Layer.add_variable (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/rnn.py:244: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:308: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:272: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
initialisation done /gpu:0
Traceback (most recent call last):
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 87, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 173, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 77, in synthesize_spectrograms
    self.load()
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 58, in load
    self._model = Tacotron2(self.checkpoint_fpath, hparams)
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/tacotron2.py", line 28, in __init__
    split_infos=split_infos)
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/tacotron.py", line 136, in initialize
    "inputs_embedding", [len(symbols), hp.embedding_dim], dtype=tf.float32)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1500, in get_variable
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1243, in get_variable
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 567, in get_variable
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 519, in _true_getter
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 868, in _get_single_variable
    (err_msg, "".join(traceback.format_list(tb))))
ValueError: Variable Tacotron_model/inference/inputs_embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)

Constructing model: Tacotron
initialisation done /gpu:0
Traceback (most recent call last):
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 173, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 77, in synthesize_spectrograms
    self.load()
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 58, in load
    self._model = Tacotron2(self.checkpoint_fpath, hparams)
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/tacotron2.py", line 28, in __init__
    split_infos=split_infos)
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/tacotron.py", line 136, in initialize
    "inputs_embedding", [len(symbols), hp.embedding_dim], dtype=tf.float32)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1500, in get_variable
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1243, in get_variable
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 567, in get_variable
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 519, in _true_getter
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 868, in _get_single_variable
    (err_msg, "".join(traceback.format_list(tb))))
ValueError: Variable Tacotron_model/inference/inputs_embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)

**Comment by goodmangu** [comment]
And this is the error in the demo_cli.py - hangs in the testing synthesizer step while constructing Tacotron:

ValueError: Variable Tacotron_model/inference/inputs_embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

Detailed info:

(voice) goodman@goodman-dl-box:~/development/Real-Time-Voice-Cloning-master$ python demo_cli.py
Arguments:
    enc_model_fpath:   encoder/saved_models/pretrained.pt
    syn_model_dir:     synthesizer/saved_models/logs-pretrained
    voc_model_fpath:   vocoder/saved_models/pretrained/pretrained.pt
    low_mem:           False
    no_sound:          False
    cpu:               False

Running a test of your configuration...

Found 2 GPUs available. Using GPU 0 (GeForce GTX 1080 Ti) of compute capability 6.1 with 11.7Gb total memory.

Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "pretrained.pt" trained to step 1564501
Found synthesizer "pretrained" trained to step 278000
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder/saved_models/pretrained/pretrained.pt
Testing your configuration with small inputs.
	Testing the encoder...
	Testing the synthesizer... (loading the model will output a lot of text)
Constructing model: Tacotron
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:424: conv1d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv1D` instead.
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/layers/convolutional.py:218: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:425: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:428: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:238: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/rnn.py:464: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/contrib/rnn/python/ops/lstm_ops.py:360: Layer.add_variable (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/rnn.py:244: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:308: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:272: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
initialisation done /gpu:0
Traceback (most recent call last):
  File "demo_cli.py", line 95, in <module>
    mels = synthesizer.synthesize_spectrograms(texts, embeds)
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 77, in synthesize_spectrograms
    self.load()
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 58, in load
    self._model = Tacotron2(self.checkpoint_fpath, hparams)
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/tacotron2.py", line 28, in __init__
    split_infos=split_infos)
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/tacotron.py", line 136, in initialize
    "inputs_embedding", [len(symbols), hp.embedding_dim], dtype=tf.float32)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1500, in get_variable
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1243, in get_variable
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 567, in get_variable
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 519, in _true_getter
    aggregation=aggregation)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 868, in _get_single_variable
    (err_msg, "".join(traceback.format_list(tb))))
ValueError: Variable Tacotron_model/inference/inputs_embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)

**Comment by blue-fish** [comment]
Have you ever successfully run demo_cli.py or demo_toolbox.py with the pretrained models in the wiki? Your 2nd message looks to be such an attempt. Try starting with a clean copy of the code and verify that demo_cli.py works with the pretrained models before switching to your own.

**Comment by goodmangu** [comment]
Yes, I can run both demo apps before starting encoder training using all
pretrained models. After finish encoder training, I am running issues with
running the demo apps.

**Comment by blue-fish** [comment]
Did you modify any hyperparameters or other files in the repo? If you want, you could upload your pretrained encoder and I can see if I also get the error message.

Also can you list your installed packages and their versions (`pip list` or `conda list`)?

**Comment by goodmangu** [comment]
Thanks, and here is my pre-trained encoder - I have not modified the hyperparameters. 
[my_run.zip](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/4873533/my_run.zip)

**Comment by goodmangu** [comment]
@blue-fish: do you have a version that passes synthesizer training, and also can run the demo apps?

**Comment by blue-fish** [comment]
Starting with a default install that has all the pretrained models, I overwrite `encoder/saved_models/pretrained.pt` with your `my_run.pt`. Then I can run demo_cli.py with no problems. The speech is barely intelligible since the synthesizer wasn't trained on it, but at least there are no errors.

**Comment by blue-fish** [comment]
@goodmangu Please do the following:
1. Clone a fresh copy of the repo (pick up all the recent changes)
2. Get a clean copy of the [pretrained models](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models) and place in the correct location
3. Run demo_cli.py and confirm no errors
4. Copy your encoder `my_run.pt` to `encoder/saved_models/pretrained.pt` (overwrite it)
5. Run demo_cli.py and see if that works for you.

After completing these 5 steps we can continue debugging the issue with your config.

**Comment by goodmangu** [comment]
This path has always worked for me My issue is once I have trained a model from scratch, the demo apps no longer work. And, I got this error. ValueError: Variable Tacotron_model/inference/inputs_embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?

**Comment by blue-fish** [comment]
> My issue is once I have trained a model from scratch, the demo apps no longer work.

If #382 is still an active issue, I think what happened is that your synthesizer model is not valid and it is having a problem loading it. You can pass the "--syn_model_dir" argument to demo_cli.py to point to the good pretrained model from Corentin. Try that and see if you still get the message.

**Comment by goodmangu** [comment]
Same issue, as by default, -s points to synthesizer/saved_models/logs-pretrained/ which is using the pre-trained model

**Comment by blue-fish** [comment]
Can you move the incomplete synthesizer model out of the saved model folder entirely so it doesn't see it? Which files in your repo are modified?

**Comment by goodmangu** [comment]
Hi @blue-fish: actually I have no models produced for the Synthesizer yet - I just finished the pre-processing step for the synthesizer. The only place I have changed was: 
 /synthesizer/models/modules.py", line 114 self._cell = tf.contrib.rnn.LSTMBlockCell(num_units, name=name)

**Comment by blue-fish** [comment]
If I make that change all tests still pass for me, using both the original encoder and yours. I have no way to reproduce the error that you are seeing. Are there any other changes that `git status` or `git diff` reports?

To ensure that further troubleshooting is productive, I suggest following the steps here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/383#issuecomment-657284710 , starting from a clean clone of the latest code, add your encoder model, and verify everything works before continuing.

It's very possible that training is breaking something but I want to first rule out any other issues with your setup that are interfering with operation of the toolbox.
