### ISSUE TITLE
can't open demo_toolbox.py

### ISSUE THREAD

**Issue by TheAwesomeYT** [CorentinJ/Real-Time-Voice-Cloning#393]
Whenever i try to open demo_toolbox.py, this happens:

```
UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
2020-07-02 10:10:33.214892: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    low_mem:          False

Warning: you did not pass a root directory for datasets as argument.
The recognized datasets are:
        LibriSpeech/dev-clean
        LibriSpeech/dev-other
        LibriSpeech/test-clean
        LibriSpeech/test-other
        LibriSpeech/train-clean-100
        LibriSpeech/train-clean-360
        LibriSpeech/train-other-500
        LibriTTS/dev-clean
        LibriTTS/dev-other
        LibriTTS/test-clean
        LibriTTS/test-other
        LibriTTS/train-clean-100
        LibriTTS/train-clean-360
        LibriTTS/train-other-500
        LJSpeech-1.1
        VoxCeleb1/wav
        VoxCeleb1/test_wav
        VoxCeleb2/dev/aac
        VoxCeleb2/test/aac
        VCTK-Corpus/wav48
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "demo_toolbox.py", line 32, in <module>
    Toolbox(**vars(args))
  File "C:\Users\HP Pavilion\Downloads\Real-Time-Voice-Cloning-master (1)\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 49, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir)
  File "C:\Users\HP Pavilion\Downloads\Real-Time-Voice-Cloning-master (1)\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 97, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_models_dir)
  File "C:\Users\HP Pavilion\Downloads\Real-Time-Voice-Cloning-master (1)\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 275, in populate_models
    raise Exception("No encoder models found in %s" % encoder_models_dir)
Exception: No encoder models found in encoder\saved_models
```

Please help!

**Comment by blue-fish** [comment]
You need a model. Get one here: [https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models)

**Comment by TheAwesomeYT** [comment]
I thought that was if you werent going to make your own? (im making my own btw)

**Comment by TheAwesomeYT** [comment]
wait nwm

**Comment by blue-fish** [comment]
If you're training your own models then you should start with the instructions here: [https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training)

I recommend first trying the toolbox with the pretrained models as it is a significant time investment to train your own.

**Comment by blue-fish** [comment]
I'm going to close this issue since #395 indicates the original issue has been resolved. We will work through any further issues you discover over there.
