### ISSUE TITLE
No encoder models found in encoder\saved_models error

### ISSUE THREAD

**Issue by sbkim052** [CorentinJ/Real-Time-Voice-Cloning#412]
Traceback (most recent call last):
  File "demo_toolbox.py", line 32, in <module>
    Toolbox(**vars(args))
  File "C:\Users\User\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 49, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir)
  File "C:\Users\User\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 98, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_models_dir)
  File "C:\Users\User\Desktop\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 327, in populate_models
    raise Exception("No encoder models found in %s" % encoder_models_dir)
Exception: No encoder models found in encoder\saved_models

How can i solve this error?

**Comment by blue-fish** [comment]
Hi @sbkim052 , thanks for reporting this. You need to download a model from here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models

We should make the error message direct the user to the wiki page to download the models.

**Comment by blue-fish** [comment]
If this solves your problem can you please go ahead and close this issue?

**Comment by sbkim052** [comment]
Thank you @blue-fish . I have solved it!
