### ISSUE TITLE
Getting an exception when browsing for files

### ISSUE THREAD

**Issue by kyukenmyo** [CorentinJ/Real-Time-Voice-Cloning#419]
For some reason, importing mp3 files is not working.  Anyone got an idea on why this might be the case.?

**Comment by kyukenmyo** [comment]
Here is the error:
Traceback (most recent call last):
  File "D:\downloads\Real-Time-Voice-Cloning\toolbox\__init__.py", line 84, in <lambda>
    func = lambda: self.load_from_browser(self.ui.browse_file())
  File "D:\downloads\Real-Time-Voice-Cloning\toolbox\__init__.py", line 145, in load_from_browser
    wav = Synthesizer.load_preprocess_wav(fpath)
  File "D:\downloads\Real-Time-Voice-Cloning\synthesizer\inference.py", line 111, in load_preprocess_wav
    wav = librosa.load(str(fpath), hparams.sample_rate)[0]
  File "C:\Users\paul1\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 162, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\paul1\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 186, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\paul1\AppData\Local\Programs\Python\Python37\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError
Traceback (most recent call last):
  File "C:\Users\paul1\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 129, in load
    with sf.SoundFile(path) as sf_desc:

**Comment by blue-fish** [comment]
Please make sure you have followed the installation instructions. You need to install ffmpeg which is a backend for audioread (which is used to load mp3 files).

Install ffmpeg and let us know if that solved the problem for you. A link is in README.md

**Comment by kyukenmyo** [comment]
This solved it for me! Thank you for an amazing response @blue-fish!! 
Forgot to install ffmpeg. Once I did so, and linked my system path variable to the location of ffmpeg, it worked perfectly!

**Comment by blue-fish** [comment]
We just updated the installation instructions, thanks for confirming that installing ffmpeg solved the issue. Have fun with the toolbox!
