### ISSUE TITLE
Update librosa and numba versions in requirements.txt

### ISSUE THREAD

**Issue by blue-fish** [CorentinJ/Real-Time-Voice-Cloning#461]
Librosa 0.8.0 is now available, and that fixes the issue which required us to pin numba to 0.48.0 (#373).

We should require `librosa>=0.8` in requirements.txt and allow any `numba` that is compatible. Anyone reading this is invited to submit a pull request. You can do this!

**Comment by blue-fish** [comment]
Before submitting the pull request please test it and make sure you can run demo_cli.py or demo_toolbox.py without errors, when using the latest librosa and numba.

The hard part is not the requirements.txt change, but taking the time to test it.

**Comment by blue-fish** [comment]
A bug to fix with librosa 0.8.0 (this may not be the only one):
> When I try to train vocoder I have this issue:
> 
> ```
> {| Epoch: 1 (24/24) | Loss: 5.4869 | 1.9 steps/s | Step: 0k | }
> | Generating: 1/5
> Traceback (most recent call last):
>   File "vocoder_train.py", line 55, in <module>
>     train(**vars(args))
>   File "/home/roma/Real-Time-Voice-Cloning/vocoder/train.py", line 126, in train
>     hp.voc_target, hp.voc_overlap, model_dir)
>   File "/home/roma/Real-Time-Voice-Cloning/vocoder/gen_wavernn.py", line 23, in gen_testset
>     save_wav(x, save_path.joinpath("%dk_steps_%d_target.wav" % (k, i)))
>   File "/home/roma/Real-Time-Voice-Cloning/vocoder/audio.py", line 23, in save_wav
>     librosa.output.write_wav(path, x.astype(np.float32), sr=hp.sample_rate)
> AttributeError: module 'librosa' has no attribute 'output'
> ```

_Originally posted by @rlutsyshyn in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/486#issuecomment-673451741_

**Comment by blue-fish** [comment]
Resolved in #572
