### ISSUE TITLE
Could not find Source.Txt file in dataset

### ISSUE THREAD

**Issue by Tayal-S** [CorentinJ/Real-Time-Voice-Cloning#467]
Hi

In ENCODER, speaker.py reads source.txt from data set which is not found. When i run the train loop , it is showing me error:

FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/shivani/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/shivani/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/shivani/Projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker_verification_dataset.py", line 55, in collate
    return SpeakerBatch(speakers, self.utterances_per_speaker, partials_n_frames)
  File "/home/shivani/Projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker_batch.py", line 8, in __init__
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "/home/shivani/Projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker_batch.py", line 8, in <dictcomp>
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "/home/shivani/Projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker.py", line 34, in random_partial
    self._load_utterances()
  File "/home/shivani/Projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker.py", line 14, in _load_utterances
    with self.root.joinpath("_sources.txt").open("r") as sources_file:
  File "/home/shivani/anaconda3/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
  File "/home/shivani/anaconda3/lib/python3.7/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'LibriSpeech/dev-clean/_sources.txt'

Please do an urgent help.

**Comment by blue-fish** [comment]
This looks like the same issue as #161 and #262. Please make sure you specify the path to your <datasets_root> folder as described in the [wiki documentation](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training#preprocessing-and-training).

If it still doesn't work, please share the command that you are using to run encoder_train.py.
