### ISSUE TITLE
SyntaxError: invalid syntax when running python demo_cli.py

### ISSUE THREAD

**Issue by biplab1** [CorentinJ/Real-Time-Voice-Cloning#468]
```
$: python demo_cli.py
Traceback (most recent call last):
  File "demo_cli.py", line 2, in <module>
    from utils.argutils import print_args
  File "Real-Time-Voice-Cloning-master/utils/argutils.py", line 22
    def print_args(args: argparse.Namespace, parser=None):
                       ^
SyntaxError: invalid syntax
```

**Comment by biplab1** [comment]
Resolved by replacing ":" by "="

def print_args(args=argparse.Namespace, parser=None):

**Comment by blue-fish** [comment]
Try replacing `python` with `python3` in your command.
On many systems "python" defaults to python2 which is incompatible.

**Comment by biplab1** [comment]
Just did that, it works now.
