### ISSUE TITLE
Can't install requirements on OSX

### ISSUE THREAD

**Issue by KeithYJohnson** [CorentinJ/Real-Time-Voice-Cloning#49]
I used the network install for CUDA before trying this and have pyenv local set to 3.7,  anyone know why I'm getting this error?

Thanks!

OSX Version: 10.12.6 (16G2016)
Here's the stack trace:

```
  Real-Time-Voice-Cloning git:(master) ✗ pip install -r requirements.txt --verbose
Created temporary directory: /private/var/folders/4p/9q3jmsg959s6gtjs4dc6sn14ks6wf6/T/pip-ephem-wheel-cache-3rpdn6k2
Created temporary directory: /private/var/folders/4p/9q3jmsg959s6gtjs4dc6sn14ks6wf6/T/pip-req-tracker-hwlp7vz4
Created requirements tracker '/private/var/folders/4p/9q3jmsg959s6gtjs4dc6sn14ks6wf6/T/pip-req-tracker-hwlp7vz4'
Created temporary directory: /private/var/folders/4p/9q3jmsg959s6gtjs4dc6sn14ks6wf6/T/pip-install-il8b8a11
Collecting tensorflow-gpu<=1.14.0,>=1.10.0 (from -r requirements.txt (line 1))
  1 location(s) to search for versions of tensorflow-gpu:
  * https://pypi.org/simple/tensorflow-gpu/
  Getting page https://pypi.org/simple/tensorflow-gpu/
  Looking up "https://pypi.org/simple/tensorflow-gpu/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/tensorflow-gpu/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/tensorflow-gpu/
    Skipping link https://files.pythonhosted.org/packages/e0/fe/9fb7fff32441dff89e00b359dade48f5f071127d604a7259fb6ee1f43e4f/tensorflow_gpu-0.12.0rc0-cp27-cp27mu-manylinux1_x86_64.whl#sha256=c97f916fc7edf0867149d8faa31cbee75bf4925bdfc0e0eef924cda1dd5c853b (from https://pypi.org/simple/tensorflow-gpu/); it is not compatible with this Python
  ....
    Skipping link https://files.pythonhosted.org/packages/ad/be/9a5ab6b9757113b841695a203883aa1a7a3ac514258038c885aa31d443be/tensorflow_gpu-2.0.0b1-cp37-cp37m-win_amd64.whl#sha256=0c8ced99e74f10c66604fa61e40cb8cfbc073e89eb95c061626d3535958142b5 (from https://pypi.org/simple/tensorflow-gpu/); it is not compatible with this Python
  ERROR: Could not find a version that satisfies the requirement tensorflow-gpu<=1.14.0,>=1.10.0 (from -r requirements.txt (line 1)) (from versions: none)
Cleaning up...
Removed build tracker '/private/var/folders/4p/9q3jmsg959s6gtjs4dc6sn14ks6wf6/T/pip-req-tracker-hwlp7vz4'
ERROR: No matching distribution found for tensorflow-gpu<=1.14.0,>=1.10.0 (from -r requirements.txt (line 1))
Exception information:
Traceback (most recent call last):
  File "/Users/ketjohn/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/Users/ketjohn/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/Users/ketjohn/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/ketjohn/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/ketjohn/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/ketjohn/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 282, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/Users/ketjohn/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 198, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/ketjohn/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip/_internal/index.py", line 792, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for tensorflow-gpu<=1.14.0,>=1.10.0 (from -r requirements.txt (line 1))
```

**Comment by KeithYJohnson** [comment]
Think I figured out my hardware can't run the nvidia stuff
