### ISSUE TITLE
Why do I get this error

### ISSUE THREAD

**Issue by jcshamir** [CorentinJ/Real-Time-Voice-Cloning#493]
Traceback (most recent call last):
  File ".\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\jcsha\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\jcsha\Desktop\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 5, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "C:\Users\jcsha\Desktop\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Users\jcsha\Desktop\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Users\jcsha\anacnda3\envs\voice-clone\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by jcshamir** [comment]
I already have Tensorflow 1.15

**Comment by blue-fish** [comment]
Which version of torch do you have? You can check it by launching Python and typing these commands. For example I have 1.5.1:
```
>>> import torch
>>> torch.__version__
'1.5.1'
>>>
```

**Comment by blue-fish** [comment]
Closing this request for setup support due to inactivity. @jcshamir please reopen this issue when you are ready to proceed with troubleshooting. Also see my question about your installed torch version above
