### ISSUE TITLE
training encode with LibriSpeech, VoxCeleb1, and VoxCeleb2 is failing

### ISSUE THREAD

**Issue by amintavakol** [CorentinJ/Real-Time-Voice-Cloning#497]
After preprocessing all three datasets, I'm getting the following error while training encoder. I carefully checked the preprocessed directories. They all have `_sources.txt`.
Can you help with this?

```
..Traceback (most recent call last):                                                                                                
  File "encoder_train.py", line 46, in <module>                                                                                     
    train(**vars(args))                                                                                                             
  File "/home/amin/voice_cloning/Real-Time-Voice-Cloning-master/encoder/train.py", line 67, in train                                
    for step, speaker_batch in enumerate(loader, init_step):                                                                        
  File "/usr/local/anaconda3/envs/voice_cloning/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__  
    data = self._next_data()                                                                                                        
  File "/usr/local/anaconda3/envs/voice_cloning/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 971, in _next_dat$
    return self._process_data(data)
  File "/usr/local/anaconda3/envs/voice_cloning/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process$data
    data.reraise()
  File "/usr/local/anaconda3/envs/voice_cloning/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
Exception: Caught Exception in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/voice_cloning/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worke$_loop
    data = fetcher.fetch(index)
  File "/usr/local/anaconda3/envs/voice_cloning/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/amin/voice_cloning/Real-Time-Voice-Cloning-master/encoder/data_objects/speaker_verification_dataset.py", line 55, in $ollate
    return SpeakerBatch(speakers, self.utterances_per_speaker, partials_n_frames)
  File "/home/amin/voice_cloning/Real-Time-Voice-Cloning-master/encoder/data_objects/speaker_batch.py", line 8, in __init__
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "/home/amin/voice_cloning/Real-Time-Voice-Cloning-master/encoder/data_objects/speaker_batch.py", line 8, in <dictcomp>
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "/home/amin/voice_cloning/Real-Time-Voice-Cloning-master/encoder/data_objects/speaker.py", line 34, in random_partial
    self._load_utterances()
 File "/home/amin/voice_cloning/Real-Time-Voice-Cloning-master/encoder/data_objects/speaker.py", line 18, in _load_utterances
    self.utterance_cycler = RandomCycler(self.utterances)
  File "/home/amin/voice_cloning/Real-Time-Voice-Cloning-master/encoder/data_objects/random_cycler.py", line 14, in __init__
    raise Exception("Can't create RandomCycler from an empty collection")
Exception: Can't create RandomCycler from an empty collection
```

**Comment by blue-fish** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/458#issuecomment-674328951

**Comment by blue-fish** [comment]
I also notice that you are using Python 3.8. Are you aware that the toolbox only supports 3.6 and 3.7? Anything torch-based will work (encoder, vocoder) but you will not be able to use the synthesizer until #472 is merged.

**Comment by mbdash** [comment]
I had this error on empty dies (no audio files)
You have to make a python script to check all folders and if only source file, del source file and folder

**Comment by amintavakol** [comment]
> I had this error on empty dirs (no audio files)
> You have to make a python script to check all folders and if only source file, del source file and folder.
> 
> I can share mine later, I am currently not in front of my PC.

Thanks! Fixed it.

**Comment by amintavakol** [comment]
> I also notice that you are using Python 3.8. Are you aware that the toolbox only supports 3.6 and 3.7? Anything torch-based will work (encoder, vocoder) but you will not be able to use the synthesizer until #472 is merged.

As far as preprocessing and training synthesizer, I didn't face any issue.
