### ISSUE TITLE
Toolbox doesn't start: "TypeError: 'NoneType' object is not callable"

### ISSUE THREAD

**Issue by blue-fish** [CorentinJ/Real-Time-Voice-Cloning#504]
Matplotlib backend issue reported by @ZeroCool940711 in #447

> @blue-fish Im trying to run your branch with Pytorch and im getting some errors when trying to run the `demo_toolbox.py`, not sure if its something on my computer that I messed up but would appreciate some help, the `demo_cli.py` seems to work but im not completely sure as I havent been able to test it fully, I'm still downloading the datasets to test it later but it does start which is more than what I can say about the original version using Tensorflow xD, this is the error im getting when running the `demo_toolbox.py`:
> 
> ```
> D:\ZeroCool\Projects\Python\Otros\Machine Learning\Voice Cloning\Real-Time-Voice-Cloning_pytorch>python demo_toolbox.py
> Arguments:
>     datasets_root:    None
>     enc_models_dir:   encoder\saved_models
>     syn_models_dir:   synthesizer\saved_models
>     voc_models_dir:   vocoder\saved_models
>     low_mem:          False
>     seed:             None
> 
> Traceback (most recent call last):
>   File "demo_toolbox.py", line 39, in <module>
>     Toolbox(**vars(args))
>   File "D:\ZeroCool\Projects\Python\Otros\Machine Learning\Voice Cloning\Real-Time-Voice-Cloning_pytorch\toolbox\__init__.py", line 63, in __init__
>     self.ui = UI()
>   File "D:\ZeroCool\Projects\Python\Otros\Machine Learning\Voice Cloning\Real-Time-Voice-Cloning_pytorch\toolbox\ui.py", line 455, in __init__
>     fig, self.umap_ax = plt.subplots(figsize=(3, 3), facecolor="#F0F0F0")
>   File "D:\Python\lib\site-packages\matplotlib\cbook\deprecation.py", line 451, in wrapper
>     return func(*args, **kwargs)
>   File "D:\Python\lib\site-packages\matplotlib\pyplot.py", line 1271, in subplots
>     fig = figure(**fig_kw)
>   File "D:\Python\lib\site-packages\matplotlib\pyplot.py", line 677, in figure
>     **kwargs)
>   File "D:\Python\lib\site-packages\matplotlib\pyplot.py", line 299, in new_figure_manager
>     return _backend_mod.new_figure_manager(*args, **kwargs)
>   File "D:\Python\lib\site-packages\matplotlib\backend_bases.py", line 3494, in new_figure_manager
>     return cls.new_figure_manager_given_figure(num, fig)
>   File "D:\Python\lib\site-packages\matplotlib\backend_bases.py", line 3499, in new_figure_manager_given_figure
>     canvas = cls.FigureCanvas(figure)
> TypeError: 'NoneType' object is not callable
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "D:\ZeroCool\Projects\Python\Otros\Machine Learning\Voice Cloning\Real-Time-Voice-Cloning_pytorch\toolbox\__init__.py", line 70, in excepthook
>     self.ui.log("Exception: %s" % exc_value)
> AttributeError: 'Toolbox' object has no attribute 'ui'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "demo_toolbox.py", line 39, in <module>
>     Toolbox(**vars(args))
>   File "D:\ZeroCool\Projects\Python\Otros\Machine Learning\Voice Cloning\Real-Time-Voice-Cloning_pytorch\toolbox\__init__.py", line 63, in __init__
>     self.ui = UI()
>   File "D:\ZeroCool\Projects\Python\Otros\Machine Learning\Voice Cloning\Real-Time-Voice-Cloning_pytorch\toolbox\ui.py", line 455, in __init__
>     fig, self.umap_ax = plt.subplots(figsize=(3, 3), facecolor="#F0F0F0")
>   File "D:\Python\lib\site-packages\matplotlib\cbook\deprecation.py", line 451, in wrapper
>     return func(*args, **kwargs)
>   File "D:\Python\lib\site-packages\matplotlib\pyplot.py", line 1271, in subplots
>     fig = figure(**fig_kw)
>   File "D:\Python\lib\site-packages\matplotlib\pyplot.py", line 677, in figure
>     **kwargs)
>   File "D:\Python\lib\site-packages\matplotlib\pyplot.py", line 299, in new_figure_manager
>     return _backend_mod.new_figure_manager(*args, **kwargs)
>   File "D:\Python\lib\site-packages\matplotlib\backend_bases.py", line 3494, in new_figure_manager
>     return cls.new_figure_manager_given_figure(num, fig)
>   File "D:\Python\lib\site-packages\matplotlib\backend_bases.py", line 3499, in new_figure_manager_given_figure
>     canvas = cls.FigureCanvas(figure)
> TypeError: 'NoneType' object is not callable
> ```
> 
> Edit: Just in case someone finds this comment because they are getting the same error this is caused by some problem with `matplotlib` when installing it using `pip install matplotlib`, it can be fixed by installing `matplotlib` using `conda install matplotlib`, it doesnt matter what version you try to install using `pip` it will always give you the same error but any version installed with `conda` will just work.

_Originally posted by @ZeroCool940711 in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/447#issuecomment-678619906_

**Comment by blue-fish** [comment]
A fix for this has been merged in matplotlib, to be released in 3.3.2. Since it's their bug, I am going to label this as dependency issue instead. We still have unresolved issues with matplotlib 3.3.x, see #455.

It would still be a good idea to change the order of the imports on our end to prevent unnecessary frustration for those not using matplotlib>=3.3.2.

**Comment by blue-fish** [comment]
Resolved in #546
