### ISSUE TITLE
Have probles to get it working on a Devuan distribution.

### ISSUE THREAD

**Issue by afantasialiberal** [CorentinJ/Real-Time-Voice-Cloning#508]
Hello i am having this output on a Devuan (it directly did nt work on my old linux mint :C)  python3 demo_cli.py
2020-08-24 22:00:26.726664: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-24 22:00:26.726717: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "demo_cli.py", line 4, in <module>
    from synthesizer.inference import Synthesizer
  File "/home/src/voiceclone/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "/home/src/voiceclone/Real-Time-Voice-Cloning-master/synthesizer/tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "/home/src/voiceclone/Real-Time-Voice-Cloning-master/synthesizer/models/__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "/home/src/voiceclone/Real-Time-Voice-Cloning-master/synthesizer/models/tacotron.py", line 4, in <module>
    from synthesizer.models.helpers import TacoTrainingHelper, TacoTestHelper
  File "/home/src/voiceclone/Real-Time-Voice-Cloning-master/synthesizer/models/helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
ModuleNotFoundError: No module named 'tensorflow.contrib'

seems somethi with the tensor flow version? the requieremnt subversion from the requirment.txt give me an error for that exact version, i just install the last one :c

**Comment by blue-fish** [comment]
Hi @afantasialiberal, tensorflow 1.15 is required. I do have a pull request that eliminates the tensorflow dependency (#472) but we don't have a very good pretrained model for use with it at this time.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-664038511
> ### No module named 'tensorflow.contrib'
> #### Summary
> 
> The toolbox requires Tensorflow 1.15 and this error message occurs when Tensorflow 2.x is installed.
> #### Solution
> 
> Install Tensorflow 1.15.
> 
> If you get a pip error `Could not find a version that satisfies the requirement tensorflow==1.15` then you are likely using Python 3.8+ which is incompatible with TF 1.15. To resolve that, you will need to switch to Python 3.6 or 3.7.

**Comment by blue-fish** [comment]
@afantasialiberal Please open a new issue if you are still stuck with the installation.
