### ISSUE TITLE
Problem opening the toolbox

### ISSUE THREAD

**Issue by Oriolazotroll5** [CorentinJ/Real-Time-Voice-Cloning#515]
Everytime i try to open the toolbox i get this:
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\MYUSERNAME\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\MYUSERNAME\Desktop\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 5, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "C:\Users\MYUSERNAME\Desktop\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Users\MYUSERNAME\Desktop\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
ModuleNotFoundError: No module named 'torch'

**Comment by blue-fish** [comment]
Try `python3 demo_toolbox.py`

On many systems `python` opens python 2.x which does not have torch.

**Comment by Oriolazotroll5** [comment]
Problem fixed!
Turns out i'm stupid and didn't download pytorch

**Comment by LiamCat** [comment]
Hi, This is really really helpful! and I found out that maybe I don't have python at all because it now says this: `python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.`  thanks.

**Comment by blue-fish** [comment]
@LiamCat Windows 10 install instructions (tested): https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
