### ISSUE TITLE
Error in loading state_dict for WaveRNN:

### ISSUE THREAD

**Issue by xieyuankun** [CorentinJ/Real-Time-Voice-Cloning#52]
I have sucessfully run the program with your checkpoint in Griffin-LIM.My dataset is LibriSpeech.But when i used pretrained wavernn vocoder,i meet a error.
Here is the code
```
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt
Traceback (most recent call last):
  File "D:\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 249, in init_vocoder
    vocoder.load_model(model_fpath)
  File "D:\Real-Time-Voice-Cloning-master\vocoder\inference.py", line 31, in load_model
    _model.load_state_dict(checkpoint['model_state'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for WaveRNN:
        Unexpected key(s) in state_dict: "upsample.resnet.batch_norm.num_batches_tracked", "upsample.resnet.layers.0.batch_norm1.num_batches_tracked", "upsample.resnet.layers.0.batch_n
orm2.num_batches_tracked", "upsample.resnet.layers.1.batch_norm1.num_batches_tracked", "upsample.resnet.layers.1.batch_norm2.num_batches_tracked", "upsample.resnet.layers.2.batch_norm1
.num_batches_tracked", "upsample.resnet.layers.2.batch_norm2.num_batches_tracked", "upsample.resnet.layers.3.batch_norm1.num_batches_tracked", "upsample.resnet.layers.3.batch_norm2.num
_batches_tracked", "upsample.resnet.layers.4.batch_norm1.num_batches_tracked", "upsample.resnet.layers.4.batch_norm2.num_batches_tracked", "upsample.resnet.layers.5.batch_norm1.num_bat
ches_tracked", "upsample.resnet.layers.5.batch_norm2.num_batches_tracked", "upsample.resnet.layers.6.batch_norm1.num_batches_tracked", "upsample.resnet.layers.6.batch_norm2.num_batches
_tracked", "upsample.resnet.layers.7.batch_norm1.num_batches_tracked", "upsample.resnet.layers.7.batch_norm2.num_batches_tracked", "upsample.resnet.layers.8.batch_norm1.num_batches_tra
cked", "upsample.resnet.layers.8.batch_norm2.num_batches_tracked", "upsample.resnet.layers.9.batch_norm1.num_batches_tracked", "upsample.resnet.layers.9.batch_norm2.num_batches_tracked
".

```

**Comment by CorentinJ** [comment]
Are you sure you have the latest commit and that your vocoder directoy is exactly what is currently on the master branch?

**Comment by xieyuankun** [comment]
> Are you sure you have the latest commit and that your vocoder directoy is exactly what is currently on the master branch?

i change the pytorch verision into 1.1.0 and it solve the problem
