### ISSUE TITLE
When I press "Synthesise Only" a error appears. 

### ISSUE THREAD

**Issue by mineLdiver** [CorentinJ/Real-Time-Voice-Cloning#535]
Here's the log:
`
Traceback (most recent call last):
  File "C:\Users\ABLPHA\Desktop\mods\Source SDK\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 121, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "C:\Users\ABLPHA\Desktop\mods\Source SDK\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 229, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "C:\Users\ABLPHA\Desktop\mods\Source SDK\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 101, in synthesize_spectrograms
    [(self.checkpoint_fpath, embeddings, texts)])[0]
  File "C:\ProgramData\Anaconda3\envs\deep-voice-cloning-no-avx\lib\site-packages\multiprocess\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\ProgramData\Anaconda3\envs\deep-voice-cloning-no-avx\lib\site-packages\multiprocess\pool.py", line 657, in get
    raise self._value
NameError: name 'self' is not defined
`

I have CUDA 10.1, cuDNN 8.0.3.33, TF 1.14 GPU with no AVX, Python 3.7.6, running on Win10

**Comment by blue-fish** [comment]
I have been overly optimistic about how quickly we could switch over to the pytorch synthesizer (which does not have this issue). Since you're the third person who has asked (others in #491, #529), I'll submit a pull request to fix this bug.

**Comment by mineLdiver** [comment]
> I have been overly optimistic about how quickly we could switch over to the pytorch synthesizer (which does not have this issue). Since you're the third person who has asked (others in #491, #529), I'll submit a pull request to fix this bug.

Thank you! So all I need is just wait and download updated version after?

**Comment by blue-fish** [comment]
@mineLdiver Please see #536 for the fix, please report if it works.

**Comment by mineLdiver** [comment]
> @mineLdiver Please see #536 for the fix, please report if it works.

I'll check it out in about 10 hours, can't do it right now, but will definitely. Thanks

**Comment by blue-fish** [comment]
Because only one file changed, you may find it easier to replace the contents of your `synthesizer/inference.py` with this: https://raw.githubusercontent.com/blue-fish/Real-Time-Voice-Cloning/491_fix_lowmem_seed/synthesizer/inference.py

**Comment by mineLdiver** [comment]
> Because only one file changed, you may find it easier to replace the contents of your `synthesizer/inference.py` with this: https://raw.githubusercontent.com/blue-fish/Real-Time-Voice-Cloning/491_fix_lowmem_seed/synthesizer/inference.py

Now it went much further, but another error appeared:
`Traceback (most recent call last):
  File "C:\Users\ABLPHA\Desktop\mods\Source SDK\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 229, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "C:\Users\ABLPHA\Desktop\mods\Source SDK\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 102, in synthesize_spectrograms
    [(self.checkpoint_fpath, embeddings, texts, self._seed)])[0]
  File "C:\ProgramData\Anaconda3\envs\deep-voice-cloning-no-avx\lib\site-packages\multiprocess\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\ProgramData\Anaconda3\envs\deep-voice-cloning-no-avx\lib\site-packages\multiprocess\pool.py", line 657, in get
    raise self._value
multiprocess.pool.MaybeEncodingError: Error sending result: '<multiprocess.pool.ExceptionWithTraceback object at 0x0000025FA21D69E8>'. Reason: 'TypeError("can't pickle SwigPyObject objects")'`

**Comment by blue-fish** [comment]
This might be related? https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/229#issuecomment-557975932

Regarding your configuration, you should consider running tensorflow 1.15.2 with CUDA 10.0 and cuDNN 7.4 per the [compatibility chart](https://www.tensorflow.org/install/source_windows#tested_build_configurations). Do you get a tensorflow warning about CUDA and cuDNN mismatch?

**Comment by mineLdiver** [comment]
> This might be related? [#229 (comment)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/229#issuecomment-557975932)
> 
> Regarding your configuration, you should consider running tensorflow 1.15.2 with CUDA 10.0 and cuDNN 7.4 per the [compatibility chart](https://www.tensorflow.org/install/source_windows#tested_build_configurations). Do you get a tensorflow warning about CUDA and cuDNN mismatch?

I'd switch to TF 1.15.2 and CUDA 10.0, but I can't find TF 1.15.2 that doesn't use AVX and uses CUDA 10.0, the closest one I can find is 1.15.0 with CUDA 10.1
Also, tried solution from 229, but now this error appears on startup:
`Traceback (most recent call last):
  File ".\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\ABLPHA\Desktop\mods\Source SDK\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\ABLPHA\Desktop\mods\Source SDK\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 5, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "C:\Users\ABLPHA\Desktop\mods\Source SDK\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Users\ABLPHA\Desktop\mods\Source SDK\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\ProgramData\Anaconda3\envs\deep-voice-cloning-no-avx\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.`

**Comment by mineLdiver** [comment]
> This might be related? [#229 (comment)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/229#issuecomment-557975932)
> 
> Regarding your configuration, you should consider running tensorflow 1.15.2 with CUDA 10.0 and cuDNN 7.4 per the [compatibility chart](https://www.tensorflow.org/install/source_windows#tested_build_configurations). Do you get a tensorflow warning about CUDA and cuDNN mismatch?

I've found a solution! I installed pytorch using:
`conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
`
and used this tensorflow wheel: https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.14.0/py37/GPU/cuda101cudnn76sse2/tensorflow_gpu-1.14.0-cp37-cp37m-win_amd64.whl

and just left the cudnn64_7.dll there, and it works now! It synthesises and vocodes just fine. Thank you!

**Comment by mineLdiver** [comment]
Should I close the issue?

**Comment by blue-fish** [comment]
If you have no further questions at this time, please close it. You're welcome to open another issue whenever you have something to discuss.
