### ISSUE TITLE
error trying to run demo

### ISSUE THREAD

**Issue by Its-Just-Luci** [CorentinJ/Real-Time-Voice-Cloning#551]
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
File "M:\Children of Apollo\Software\Real-Time-Voice-Cloning\pretrained\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "M:\Children of Apollo\Software\Real-Time-Voice-Cloning\pretrained\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 2, in <module>
    from matplotlib.figure import Figure
  File "C:\Users\lk00d\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\figure.py", line 18, in <module>
    from matplotlib import docstring, projections
  File "C:\Users\lk00d\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\projections\__init__.py", line 4, in <module>
    from mpl_toolkits.mplot3d import Axes3D
ModuleNotFoundError: No module named 'mpl_toolkits.mplot3d'

**Comment by Its-Just-Luci** [comment]
ok, I got it running, but now it spits out the following error in the command prompt:

 0:   N
2020-10-09 01:10:17.358266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5680 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:29:00.0, compute capability: 7.5)
2020-10-09 01:10:18.018608: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-09 01:10:18.252081: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-09 01:10:18.254978: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.2.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-10-09 01:10:18.262729: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.2.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "C:\Users\lk00d\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\lk00d\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\lk00d\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node Tacotron_model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/conv1d/conv1d}}]]
         [[Tacotron_model/inference/add/_269]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node Tacotron_model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/conv1d/conv1d}}]]
0 successful operations.
0 derived errors ignored.

**Comment by blue-fish** [comment]
This is a tensorflow issue, you can browse the issues there and look for a solution. Different people report different things solve it for them. For example here's a similar problem reported: https://github.com/tensorflow/tensorflow/issues/23715
