### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Erfie** [CorentinJ/Real-Time-Voice-Cloning#575]
C:\Real-Time-Voice-Cloning>python demo_cli.py
2020-10-26 21:55:28.229051: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
C:\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_dir:     synthesizer\saved_models\logs-pretrained
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    low_mem:           False
    no_sound:          False
    seed:              None
    no_mp3_support:    False

C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
Running a test of your configuration...

Found 1 GPUs available. Using GPU 0 (GeForce RTX 3080) of compute capability 8.6 with 10.7Gb total memory.

Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "pretrained.pt" trained to step 1564501
Found synthesizer "pretrained" trained to step 278000
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt
Testing your configuration with small inputs.
        Testing the encoder...
Traceback (most recent call last):
  File "demo_cli.py", line 90, in <module>
    encoder.embed_utterance(np.zeros(encoder.sampling_rate))
  File "C:\Real-Time-Voice-Cloning\encoder\inference.py", line 147, in embed_utterance
    partial_embeds = embed_frames_batch(frames_batch)
  File "C:\Real-Time-Voice-Cloning\encoder\inference.py", line 55, in embed_frames_batch
    embed = _model.forward(frames).detach().cpu().numpy()
  File "C:\Real-Time-Voice-Cloning\encoder\model.py", line 53, in forward
    out, (hidden, cell) = self.lstm(utterances, hidden_init)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\rnn.py", line 564, in forward
    return self.forward_tensor(input, hx)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\rnn.py", line 543, in forward_tensor
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\rnn.py", line 526, in forward_impl
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by blue-fish** [comment]
@Erfie 

I'm sorry, but we no longer allow the issues board to be used for technical support questions. If you have evidence that this is a bug of our software, please share and we will reopen the issue and investigate.

Most likely you have an incompatibility between your CUDA, cuDNN and pytorch versions. You can try reinstalling pytorch using the instructions at https://pytorch.org and see if that helps.
