### ISSUE TITLE
Custom dataset encoder training

### ISSUE THREAD

**Issue by quirijnve** [CorentinJ/Real-Time-Voice-Cloning#579]
Hi, how do i implement a cusom data set for the encoder training?

**Comment by quirijnve** [comment]
Currently i have tried importing it as one of the example models but my dutch dataset has just one transcript.txt which states what file has what text, but how do i implement this data correctly?

**Comment by blue-fish** [comment]
Are you familiar with the folder structure of the [LibriSpeech dataset](https://openslr.org/12)? Make your dataset look like that. For each speaker, you should have a separate folder that collects audio files of that speaker.

Otherwise, you will need to edit [encoder/preprocess.py](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/47a9093f901469486fca5b83babeb26ca98fa85d/encoder/preprocess.py) to preprocess a dataset in a different format. We aren't able to help with your custom dataset, but would welcome a pull request if you make any code improvements while doing this.

**Comment by quirijnve** [comment]
I still ned some help

**Comment by quirijnve** [comment]
Currently my dataset is structured like this:

NL
     clips
             common_voice_nl_17691032
     transcript.tsv

where transcript.tsv contains:
client_id	namefile	    sentence (all separeted with a tab):

037cfe75436b3f535ccd1035df41847b8d0706c31b0d451151dae5b8e9eccc64404fe870ce14553dd286b13d7687ea2503608248bf8d1f62523b182d1cbf6906	common_voice_nl_18054747.mp3	Nucleaire energie is goedkoop, maar niet zo duurzaam

My clips arent sorted on speaker, do you know any code that can sort them according to the transcript.tsv
And do you need to have a separet transcript file per mp3/wav?

**Comment by blue-fish** [comment]
I recommend skipping straight to synthesizer training, using Corentin's pretrained encoder. You will not need to separate the files for each speaker which will simplify things considerably. It will be easiest if you make a separate transcript file per mp3/wav.

**Comment by quirijnve** [comment]
Hi, i separeted all the transcripts into common_voice_nl_17691033.txt and then i have the file common_voice_nl_17691033.mp4 repeated for all the files i have all in one folder, but i get this error:

LibriTTS: 100%|██████████████████████████████████████████████████████████████████████| 83648/83648 [00:20<00:00, 4128.04speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 49, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

it recognizes all the files but what is going wrong?

**Comment by blue-fish** [comment]
You might need to put the audio files inside a "book" folder that is contained in the speaker folder. See this: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538

Also, make sure to use the `--no_alignments` option for preprocess since you have separate text files for each utterance.

**Comment by quirijnve** [comment]
Thanks, that fixed it! is it correct even tough i installed the tensorflow gpu version, the synthesizer_preprocess_audio.py uses a lot of cpu?

**Comment by blue-fish** [comment]
> the synthesizer_preprocess_audio.py uses a lot of cpu?

You're welcome. The high CPU usage is expected.

**Comment by quirijnve** [comment]
I have around 40K.wav and txt files but the /SV2TTS/synnthesizer/audio ends with 12K files is there something wrong
I get a long output:

`  File "C:\Users\quiri\anaconda3\envs\voice1\lib\runpy.py", line 96, in _run_module_code
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer_preprocess_audio.py", line 1, in <module>
    exec(code, run_globals)
    mod_name, mod_spec, pkg_name, script_name)
    from synthesizer.preprocess import preprocess_dataset
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer_preprocess_audio.py", line 1, in <module>
  File "C:\Users\quiri\anaconda3\envs\voice1\lib\runpy.py", line 85, in _run_code
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 5, in <module>
    from synthesizer.preprocess import preprocess_dataset
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 5, in <module>
    from encoder import inference as encoder
    exec(code, run_globals)
    from encoder import inference as encoder
  File "E:\Python\Voice\Real-Time-Voice-Cloning\encoder\inference.py", line 2, in <module>
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer_preprocess_audio.py", line 1, in <module>
  File "E:\Python\Voice\Real-Time-Voice-Cloning\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "E:\Python\Voice\Real-Time-Voice-Cloning\encoder\model.py", line 5, in <module>
    from encoder.model import SpeakerEncoder
  File "E:\Python\Voice\Real-Time-Voice-Cloning\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
    from synthesizer.preprocess import preprocess_dataset
    from torch.nn.utils import clip_grad_norm_
  File "C:\Users\quiri\anaconda3\envs\voice1\lib\site-packages\torch\__init__.py", line 117, in <module>
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 5, in <module>
  File "C:\Users\quiri\anaconda3\envs\voice1\lib\site-packages\torch\__init__.py", line 117, in <module>
    from encoder import inference as encoder
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\quiri\anaconda3\envs\voice1\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\quiri\anaconda3\envs\voice1\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
  File "E:\Python\Voice\Real-Time-Voice-Cloning\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "E:\Python\Voice\Real-Time-Voice-Cloning\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Users\quiri\anaconda3\envs\voice1\lib\site-packages\torch\__init__.py", line 117, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\quiri\anaconda3\envs\voice1\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
C:\Users\quiri\anaconda3\envs\voice1\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
2020-10-31 20:15:40.735238: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-31 20:15:40.775576: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-31 20:15:40.805657: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-31 20:15:40.885325: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
C:\Users\quiri\anaconda3\envs\voice1\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
2020-10-31 20:15:41.728081: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-31 20:15:41.800110: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-31 20:15:41.815603: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
LibriTTS:   0%|                                                                            | 0/1 [46:28<?, ?speakers/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\quiri\anaconda3\envs\voice1\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 78, in preprocess_speaker
    text = "".join([line for line in text_file])
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 78, in <listcomp>
    text = "".join([line for line in text_file])
  File "C:\Users\quiri\anaconda3\envs\voice1\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 42: character maps to <undefined>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 35, in preprocess_dataset
    for speaker_metadata in tqdm(job, datasets_name, len(speaker_dirs), unit="speakers"):
  File "C:\Users\quiri\anaconda3\envs\voice1\lib\site-packages\tqdm\std.py", line 1171, in __iter__
    for obj in iterable:
  File "C:\Users\quiri\anaconda3\envs\voice1\lib\multiprocessing\pool.py", line 748, in next
    raise value
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 42: character maps to <undefined>`

**Comment by quirijnve** [comment]
i think i foudn the problem

> Ik heb net alle seizoenen van “Friends” in één ruk uitgekeken.	

It is porbbably the "".

**Comment by quirijnve** [comment]
I removed the " from all txt files and all other weird characters, now i get this error

`(voice2) E:\Python\Voice\Real-Time-Voice-Cloning>python synthesizer_preprocess_audio.py E:\Python\ADATA --datasets_name LibriTTS --subfolders train-clean-100 --no_alignments
2020-11-01 11:13:45.064517: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 1, in <module>
    from synthesizer.preprocess import preprocess_dataset
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 2, in <module>
    from synthesizer import audio
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\audio.py", line 4, in <module>
    import tensorflow as tf
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\site-packages\tensorflow_core\__init__.py", line 36, in <module>
    from tensorflow._api.v1 import compat
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\site-packages\tensorflow_core\_api\v1\compat\__init__.py", line 23, in <module>
    from tensorflow._api.v1.compat import v1
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\site-packages\tensorflow_core\_api\v1\compat\v1\__init__.py", line 674, in <module>
    [_module_util.get_parent_dir(estimator)] + _current_module.__path__)
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\site-packages\tensorflow_core\python\tools\module_util.py", line 24, in get_parent_dir
    return os.path.abspath(os.path.join(os.path.dirname(module.__file__), ".."))
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\ntpath.py", line 221, in dirname
    return split(p)[0]
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by quirijnve** [comment]
Same error asgain...

`(voice2) E:\Python\Voice\Real-Time-Voice-Cloning>python synthesizer_preprocess_audio.py E:\Python\ADATA --datasets_name LibriTTS --subfolders train-clean-100 --no_alignments
2020-11-01 11:36:43.492077: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Arguments:
    datasets_root:   E:\Python\ADATA
    out_dir:         E:\Python\ADATA\SV2TTS\synthesizer
    n_processes:     None
    skip_existing:   False
    hparams:
    no_alignments:   True
    datasets_name:   LibriTTS
    subfolders:      train-clean-100

Using data from:
    E:\Python\ADATA\LibriTTS\train-clean-100
LibriTTS:   0%|                                                                                                                                                                                                                                                                                                              | 0/1 [00:00<?, ?speakers/s]2020-11-01 11:36:49.384569: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.387587: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.394051: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.397403: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.408732: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.434932: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.449949: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.453167: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.459298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.459375: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.488964: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-01 11:36:49.490559: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
C:\Users\quiri\anaconda3\envs\voice2\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
C:\Users\quiri\anaconda3\envs\voice2\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
LibriTTS:   0%|                                                                                                                                                                                                                                                                                                            | 0/1 [1:03:16<?, ?speakers/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 78, in preprocess_speaker
    text = "".join([line for line in text_file])
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 78, in <listcomp>
    text = "".join([line for line in text_file])
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 42: character maps to <undefined>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "E:\Python\Voice\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 35, in preprocess_dataset
    for speaker_metadata in tqdm(job, datasets_name, len(speaker_dirs), unit="speakers"):
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\site-packages\tqdm\std.py", line 1171, in __iter__
    for obj in iterable:
  File "C:\Users\quiri\anaconda3\envs\voice2\lib\multiprocessing\pool.py", line 748, in next
    raise value
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 42: character maps to <undefined>`

do you know what to do

**Comment by blue-fish** [comment]
You might need to change the character encoding to utf-8 in this line:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/47a9093f901469486fca5b83babeb26ca98fa85d/synthesizer/preprocess.py#L77

```
with text_fpath.open("r", encoding="utf-8") as text_file:
```

Also, I apologize but the github issues board is not for technical support. It is for coordinating development of the software and reporting bugs. This is a research code, not a finished product. You'll have to get help somewhere else if there's a problem that you're unable to solve.

**Comment by woodrow73** [comment]
Hi, I've developed a Java program to help a little in the collection of utterances (I'm looking forward to using it for single speaker models).  It takes a 16-bit PCM wav file as input, and then it splits the wav file wherever it detects silence in the recording (no audio playing level of silence) - it deletes the periods of silence (a variable can change the amount of silence padding the audio).  The program can output to either .wav or .flac formats, and by default gives the LibriSpeech naming format of 211-122425-0000.flac

I plan on using it with Audacity to manually record a single speaker for 12-18 minutes with a dab of silence between the utterances that are each 2-17 seconds in length - I hear audacity loses a little in audio quality, but that it does well with the Windows WASAPI option.

Anyways, I'm mentioning this in case there's any demand for it.
