### ISSUE TITLE
Numpy fails to pass a sanity check due to a bug in the windows runtime

### ISSUE THREAD

**Issue by BlockyBoyRoll** [CorentinJ/Real-Time-Voice-Cloning#596]
I am getting this error:
** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\olive\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\olive\Desktop\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\olive\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File "C:\Users\olive\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\cbook\__init__.py", line 28, in <module>
    import numpy as np
  File "C:\Users\olive\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\olive\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\olive\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

can someone help please, thank you.

**Comment by blue-fish** [comment]
Try `pip install numpy==1.19.3` as suggested in https://github.com/numpy/numpy/issues/17746#issuecomment-724782963

**Comment by BlockyBoyRoll** [comment]
> Try `pip install numpy==1.19.3` as suggested in [numpy/numpy#17746 (comment)](https://github.com/numpy/numpy/issues/17746#issuecomment-724782963)

yes! i am one step away from being able to use this. but there is one issue. it keeps saying i need ffmpeg even though i already have ffmpeg, ive done pip install ffmpeg but i still get the error. have any tips?

**Comment by blue-fish** [comment]
Make sure to set your environment variables as in: https://video.stackexchange.com/a/20496

Thank you for reporting the numpy issue, we have updated requirements.txt in #597 so other users will not experience the error.
