### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Vi22388** [CorentinJ/Real-Time-Voice-Cloning#618]
How do I solve this when Loading dataset?

Traceback (most recent call last):
  File "C:\Users\Vicente\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 83, in <lambda>
    self.ui.browser_load_button.clicked.connect(lambda: self.load_from_browser())
  File "C:\Users\Vicente\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 168, in load_from_browser
    wav = Synthesizer.load_preprocess_wav(fpath)
  File "C:\Users\Vicente\Desktop\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 129, in load_preprocess_wav
    wav = librosa.load(str(fpath), hparams.sample_rate)[0]
  File "D:\Python 3.7\lib\site-packages\librosa\core\audio.py", line 163, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\Python 3.7\lib\site-packages\librosa\core\audio.py", line 187, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "D:\Python 3.7\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "D:\Python 3.7\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Vicente\\Desktop\\Real-Time-Voice-Cloning-master\\datasets\\LibriSpeech\\train-clean-100'

**Comment by blue-fish** [comment]
What is the python command you are using to launch the toolbox?

**Comment by mbdash** [comment]
win 13 error is an i/o error. 
Do you have all the proper files in the folder?
Are they writable? 
Maybe you need to remove read only on folder and files in folder?
(right click on folder and remove read only)

**Comment by Vi22388** [comment]
Python demo_toolbox.py --low_mem -d "C:\Users\Vicente\Desktop\Real-Time-Voice-Cloning-master\datasets"

So, I got it to work, I didn't realize I had to uncompress the .tar.gz file into a normal folder, and it worked now.

(permissions are correct anyways)
