### ISSUE TITLE
Tutorial: Windows installation

### ISSUE THREAD

**Issue by car1ot** [CorentinJ/Real-Time-Voice-Cloning#647]
Hello,
I have an issues with installing to windows (10). Please, could you give a guide?

**Comment by blue-fish** [comment]
Here is a Windows 10 install guide: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
Feedback is appreciated.

**Comment by bigdog3604** [comment]
I have been trying to install this program for over two days without any luck.  I've followed the "Poorly Documented" guide and believe I have followed all the steps.  I try to launch the CLI toolbox and get an error:  ModuleNotFound:  No module name 'webrtcvad'.  I go to the Python 3.7 lib folder and the module is there.  I would love to work with @tomodachi94 to test out his new process for Windows 10 users.  The existing process sucks.

**Comment by blue-fish** [comment]
@bigdog3604 
Since #376, `webrtcvad` is optional and the toolbox will run without it.
Make sure you have downloaded the latest version of Real-Time-Voice-Cloning from this site.
Here's a download link: [master.zip](https://github.com/CorentinJ/Real-Time-Voice-Cloning/archive/master.zip)

**Comment by blue-fish** [comment]
The "Poorly Documented" guide is obsolete given the recent usability improvements. It is hurting users more than it is helping now. We should stop linking to it in the README.

**Comment by HeliumHead** [comment]
If you'd like to use ```
webrtcvad
```, I think it requires the 64 bit version of Python 3.7, but I could be confusing that with something else...

**Comment by daman-cyngh** [comment]
> Here is a Windows 10 install guide: [#642 (comment)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542)
> Feedback is appreciated.

I am using these steps for windows installation.
I faced following issues:
i) In step * running "pip install --upgrade pip" after certain installations I get "ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\DAMAND~1\\AppData\\Local\\Temp\\pip-uninstall-whymyu95\\pip.exe' Consider using the `--user` option or check the permissions." but i guess pip runs fine for next steps
ii) In step 9 the link to download zip folder for ffmpeg says FILE NOT FOUND.

Can you please help with this?

**Comment by CarvellScott** [comment]
I'm attempting to install this on Windows 10 as well. I used Anaconda to install Pytorch and the rest of the requirements, but as far as downloading ffmpeg goes, I'm not sure where to place it for the executable to be found...

Nonetheless, the rest of the installation seemed to proceed without any issues. Upon running the demo however, I see this message:
```
C:\Users\Carvell\gitrepos\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_fpath:   synthesizer\saved_models\pretrained\pretrained.pt
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    cpu:               False
    no_sound:          False
    seed:              None
    no_mp3_support:    False

A s s e r t i o n   f a i l e d !

 P r o g r a m :   C : \ U s e r s \ C a r v e l l \ a n a c o n d a 3 \ e n v s \ v o i c e _ c l o n i n g \ p y t h o n . e x e
 F i l e :   s r c / h o s t a p i / w d m k s / p a _ w i n _ w d m k s . c ,   L i n e   1 0 6 1

 E x p r e s s i o n :   F A L S E
 ```
The `s p a c e d  o u t` text appears there as it does in my terminal. The python version in the conda env I'm using is 3.8.8.

**Comment by AyseEe501** [comment]
this can help https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/758#issuecomment-846289096

**Comment by Tomcattwo** [comment]
@CarvellScott You can install ffmpeg via sourceforge in Anaconda using this command:
`conda install -c conda-forge ffmpeg-python`
See here for details: [(https://anaconda.org/conda-forge/ffmpeg-python)]
Regards, Tomcattwo

**Comment by Tornakin** [comment]
I've been able to install every thing else so far but can't figure out what I'm supposed to do with (pip install -r requirements.txt)

**Comment by LukeCronquist** [comment]
Error: Model files not found.   even though they are there D;

**Comment by blue-fish** [comment]
> Error: Model files not found. even though they are there D;

Most of the time, can be solved with https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/758#issuecomment-850954893 or https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-864340065

**Comment by Bob123360** [comment]
great guide! but ran into a bit of an issue with this, I just copied over everything since I clicked enter.

(venv) C:\Real-Time-Voice-Cloning-master>cd C:\Real-Time-Voice-Cloning-master

(venv) C:\Real-Time-Voice-Cloning-master>venv\Scripts\activate.bat

(venv) C:\Real-Time-Voice-Cloning-master>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 5, in <module>
    from toolbox import Toolbox
  File "C:\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 6, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

so what's numpy? what am I missing?

**Comment by MuhammadWaqar621** [comment]
i want to train for other language, can you able to help me?

**Comment by Tomcattwo** [comment]
Muhammad,
No, I can't. That is a much bigger project than what I have done. Sorry.

________________________________

**Comment by PixelcrafterEXE** [comment]
> ### Get FFmpeg
> 9. Download FFmpeg from here: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-10-31-12-23/ffmpeg-N-104454-gd92fdc7144-win64-lgpl.zip
> 10. Extract the zip file. Move `ffmpeg.exe` to `C:\Real-Time-Voice-Cloning-master` (the same folder as demo_toolbox.py)

Alternatively `winget install FFmpeg` would be more elegant.

**Comment by MaraScott** [comment]
Damn ! Thx

**Comment by lightcode4** [comment]
3. Edit the environment variables for your account. Add these locations
   to PATH. First is for python.exe, second is for pip.exe. Move these to the
   top to take precedence over any pre-existing Python installations.

i keep getting an error in editing paths

**Comment by goldentechie** [comment]
![image](https://github.com/user-attachments/assets/bc422582-0197-4d5f-a302-9b00c3278198)
Installed Python3.7 by following the tutorial. Can't install venv

**Comment by sharmausa** [comment]
While running pip install -r requirements.txt, I am getting following error.

pip install -r .\requirements.txt
Collecting inflect==5.3.0 (from -r .\requirements.txt (line 1))
  Using cached inflect-5.3.0-py3-none-any.whl.metadata (21 kB)
Collecting librosa==0.8.1 (from -r .\requirements.txt (line 2))
  Using cached librosa-0.8.1-py3-none-any.whl.metadata (6.8 kB)
Collecting matplotlib==3.5.1 (from -r .\requirements.txt (line 3))
  Using cached matplotlib-3.5.1.tar.gz (35.3 MB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.20.3 (from -r .\requirements.txt (line 4))
  Using cached numpy-1.20.3.zip (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\cli\req_command.py", line 68, in wrapper
    return func(self, options, args)
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\commands\install.py", line 387, in run
    requirement_set = resolver.resolve(
        reqs, check_supported_wheels=not options.target_dir
    )
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 96, in resolve        
    result = self._result = resolver.resolve(
                            ~~~~~~~~~~~~~~~~^
        collected.requirements, max_rounds=limit_how_complex_resolution_can_be
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 515, in resolve        
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 388, in resolve        
    self._add_to_criteria(self.state.criteria, r, parent=None)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 141, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 194, in __bool__
    return bool(self._sequence)
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 163, in __bool__
    self._bool = any(self)
                 ~~~^^^^^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 147, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 37, in _iter_built
    candidate = func()
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        link, template, name, version
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ~~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<3 lines>...
        version=version,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 306, in __init__    
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        link=link,
        ^^^^^^^^^^
    ...<4 lines>...
        version=version,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__    
    self.dist = self._prepare()
                ~~~~~~~~~~~~~^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare    
    dist = self._prepare_distribution()
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 317, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\operations\prepare.py", line 532, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\operations\prepare.py", line 647, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
        req,
    ...<3 lines>...
        self.check_build_deps,
    )
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution 
    abstract_dist.prepare_distribution_metadata(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        finder, build_isolation, check_build_deps
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs      
    build_reqs = self._get_build_requires_wheel()
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_internal\utils\misc.py", line 684, in get_requires_for_build_wheel      
    return super().get_requires_for_build_wheel(config_settings=cs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 196, in get_requires_for_build_wheel
    return self._call_hook(
           ~~~~~~~~~~~~~~~^
        "get_requires_for_build_wheel", {"config_settings": config_settings}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\New User\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 402, in _call_hook
    raise BackendUnavailable(
    ...<4 lines>...
    )
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'setuptools.build_meta'
