### ISSUE TITLE
demo_toolbox.py on MacOS

### ISSUE THREAD

**Issue by mrgloom** [CorentinJ/Real-Time-Voice-Cloning#65]
On MacOS 10.14.5,  I have installed 
`pip install PyQt5`

python demo_toolbox.py

```
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "/data/Real-Time-Voice-Cloning/toolbox/__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "/data/Real-Time-Voice-Cloning/toolbox/ui.py", line 1, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import (
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 18, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 201, in <module>
    "Matplotlib qt-based backends require an external PyQt4, PyQt5,\n"
ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
PySide or PySide2 package to be installed, but it was not found.
```

`pip install PySide2` solved the problem.

But I get next one:

```
Traceback (most recent call last):
  File "demo_toolbox.py", line 32, in <module>
    Toolbox(**vars(args))
  File "/data/Real-Time-Voice-Cloning/toolbox/__init__.py", line 48, in __init__
    self.ui = UI()
  File "/data/Real-Time-Voice-Cloning/toolbox/ui.py", line 375, in __init__
    self.projections_layout.addWidget(FigureCanvas(fig))
TypeError: addWidget(self, QWidget, stretch: int = 0, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 1 has unexpected type 'FigureCanvasQTAgg'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/data/Real-Time-Voice-Cloning/toolbox/__init__.py", line 55, in excepthook
    self.ui.log("Exception: %s" % exc_value)
AttributeError: 'Toolbox' object has no attribute 'ui'

Original exception was:
Traceback (most recent call last):
  File "demo_toolbox.py", line 32, in <module>
    Toolbox(**vars(args))
  File "/data/Real-Time-Voice-Cloning/toolbox/__init__.py", line 48, in __init__
    self.ui = UI()
  File "/data/Real-Time-Voice-Cloning/toolbox/ui.py", line 375, in __init__
    self.projections_layout.addWidget(FigureCanvas(fig))
TypeError: addWidget(self, QWidget, stretch: int = 0, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 1 has unexpected type 'FigureCanvasQTAgg'
```
```

python -V
Python 3.6.5

pip freeze | grep PyQt5
PyQt5==5.13.0
PyQt5-sip==4.19.18

pip freeze | grep PySide2
PySide2==5.13.0
```

**Comment by johndpope** [comment]
mac + cuda does not go together. high sierra was last time nvidia released drivers for mac.

**Comment by minmugil** [comment]
my os is window10 but totally same symptom with him

Traceback (most recent call last):
  File "demo_toolbox.py", line 32, in <module>
    Toolbox(**vars(args))
  File "C:\Users\alsan\Real-Time-Voice-Cloning\toolbox\__init__.py", line 48, in __init__
    self.ui = UI()
  File "C:\Users\alsan\Real-Time-Voice-Cloning\toolbox\ui.py", line 375, in __init__
    self.projections_layout.addWidget(FigureCanvas(fig))
TypeError: addWidget(self, QWidget, stretch: int = 0, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 1 has unexpected type 'FigureCanvasQTAgg'

**Comment by daggydove** [comment]
@minmugil @mrgloom I'm having the same problem, did y'all ever figure this out?

**Comment by minmugil** [comment]
> @minmugil @mrgloom I'm having the same problem, did y'all ever figure this out?

no i gave up

**Comment by inglesuniversal** [comment]
Can this run on a Google Colab Machine?
