### ISSUE TITLE
Issues with pretrained model

### ISSUE THREAD

**Issue by Musskk** [CorentinJ/Real-Time-Voice-Cloning#682]
I downloaded and installed the pretrained models, but when I try to run the toolbox it says that there are no models.

**Comment by blue-fish** [comment]
Please make sure you are running `python demo_toolbox.py` from the folder where demo_toolbox.py exists. If that still doesn't work, try this: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/680#issuecomment-786452068

**Comment by Musskk** [comment]
I was missing one of the requirements, but now when I run it I get this:
Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_fpath:   synthesizer\saved_models\pretrained\pretrained.pt
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    cpu:               False
    no_sound:          False
    seed:              None
    no_mp3_support:    False

C:\Users\Horus50\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
Traceback (most recent call last):
  File "C:\Users\Horus50\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 146, in load
    with sf.SoundFile(path) as sf_desc:
  File "C:\Users\Horus50\AppData\Local\Programs\Python\Python37\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\Horus50\AppData\Local\Programs\Python\Python37\lib\site-packages\soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "C:\Users\Horus50\AppData\Local\Programs\Python\Python37\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'samples/1320_00000.mp3': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Horus50\Desktop\Coding\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\demo_cli.py", line 50, in <module>
    librosa.load("samples/1320_00000.mp3")
  File "C:\Users\Horus50\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 163, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\Horus50\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 187, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\Horus50\AppData\Local\Programs\Python\Python37\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "C:\Users\Horus50\AppData\Local\Programs\Python\Python37\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'samples/1320_00000.mp3'

It seems like I'm missing some files somehow, but I downloaded the entire project earlier today and the only change that I have made is sticking the pretrained models into it.

**Comment by blue-fish** [comment]
I answered this question in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/683#issuecomment-787405161 .
