### ISSUE TITLE
test checks out just fine and the test synthesizer even works but when I go to run the toolbox I get this error

### ISSUE THREAD

**Issue by mistuhjones** [CorentinJ/Real-Time-Voice-Cloning#684]
(base) C:\Users\aarn3\OneDrive\Documents\Real-Time-Voice-Cloning>python demo_toolbox.py
C:\Users\aarn3\OneDrive\Documents\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\aarn3\OneDrive\Documents\Real-Time-Voice-Cloning\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\aarn3\OneDrive\Documents\Real-Time-Voice-Cloning\toolbox\ui.py", line 15, in <module>
    import umap
  File "C:\Users\aarn3\anaconda3\lib\site-packages\umap\__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "C:\Users\aarn3\anaconda3\lib\site-packages\umap\umap_.py", line 47, in <module>
    from pynndescent import NNDescent
  File "C:\Users\aarn3\anaconda3\lib\site-packages\pynndescent\__init__.py", line 3, in <module>
    from .pynndescent_ import NNDescent, PyNNDescentTransformer
  File "C:\Users\aarn3\anaconda3\lib\site-packages\pynndescent\pynndescent_.py", line 21, in <module>
    import pynndescent.sparse as sparse
  File "C:\Users\aarn3\anaconda3\lib\site-packages\pynndescent\sparse.py", line 10, in <module>
    from pynndescent.utils import norm, tau_rand
  File "C:\Users\aarn3\anaconda3\lib\site-packages\pynndescent\utils.py", line 9, in <module>
    from numba.experimental import structref
ImportError: cannot import name 'structref' from 'numba.experimental' (C:\Users\aarn3\anaconda3\lib\site-packages\numba\experimental\__init__.py)

**Comment by blue-fish** [comment]
Thanks for reporting the issue, but I can't provide support for installations using Anaconda. It's recommended to use a normal Python environment. See the Windows setup instructions in: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

**Comment by arosha445** [comment]
Check your numba version by running below
`pip show numba`

I had a older version of numba, Solved it by installing 0.53.0
`pip install numba==0.53.0`
