### ISSUE TITLE
Error running synthesizer_preprocess_audio.py: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by ks-sav** [CorentinJ/Real-Time-Voice-Cloning#691]
I want to go through the steps of preprocessing and training a synthesizer using the LibriSpeech train-clean-100 dataset

I have the latest version of this repo and I'm able to run demo_toolbox.py without errors.

I use the command `python synthesizer_preprocess_audio.py C:\Real-Time-Voice-Cloning-master\sav --datasets_name LibriSpeech --subfolders train-clean-100 --no_trim`

Here is the error from running synthesizer_preprocess_audio.py:

```
C:\Real-Time-Voice-Cloning-master\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    datasets_root:   C:\SAV
    out_dir:         C:\SAV\SV2TTS\synthesizer
    n_processes:     None
    skip_existing:   False
    hparams:
    no_alignments:   False
    datasets_name:   LibriSpeech
    subfolders:      train-clean-100

Using data from:
    C:\SAV\LibriSpeech\train-clean-100
LibriSpeech:   0%|                                                                        | 0/10 [00:00<?, ?speakers/s]Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
    exitcode = _main(fd)
    exitcode = _main(fd)
    exitcode = _main(fd)
    exitcode = _main(fd)
    exitcode = _main(fd)
    exitcode = _main(fd)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
    prepare(preparation_data)
    prepare(preparation_data)
    prepare(preparation_data)
    prepare(preparation_data)
    prepare(preparation_data)
    prepare(preparation_data)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
    run_name="__mp_main__")
    run_name="__mp_main__")
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    run_name="__mp_main__")
    run_name="__mp_main__")
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    run_name="__mp_main__")
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
    pkg_name=pkg_name, script_name=fname)
    pkg_name=pkg_name, script_name=fname)
    pkg_name=pkg_name, script_name=fname)
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    pkg_name=pkg_name, script_name=fname)
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
    mod_name, mod_spec, pkg_name, script_name)
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
    exec(code, run_globals)
    exec(code, run_globals)
    exec(code, run_globals)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
    exec(code, run_globals)
  File "C:\Real-Time-Voice-Cloning-master\synthesizer_preprocess_audio.py", line 1, in <module>
  File "C:\Real-Time-Voice-Cloning-master\synthesizer_preprocess_audio.py", line 1, in <module>
  File "C:\Real-Time-Voice-Cloning-master\synthesizer_preprocess_audio.py", line 1, in <module>
  File "C:\Real-Time-Voice-Cloning-master\synthesizer_preprocess_audio.py", line 1, in <module>
    exec(code, run_globals)
  File "C:\Real-Time-Voice-Cloning-master\synthesizer_preprocess_audio.py", line 1, in <module>
  File "C:\Real-Time-Voice-Cloning-master\synthesizer_preprocess_audio.py", line 1, in <module>
    from synthesizer.preprocess import preprocess_dataset
    from synthesizer.preprocess import preprocess_dataset
    from synthesizer.preprocess import preprocess_dataset
    from synthesizer.preprocess import preprocess_dataset
  File "C:\Real-Time-Voice-Cloning-master\synthesizer_preprocess_audio.py", line 1, in <module>
    from synthesizer.preprocess import preprocess_dataset
    from synthesizer.preprocess import preprocess_dataset
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 5, in <module>
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 5, in <module>
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 5, in <module>
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 5, in <module>
    from encoder import inference as encoder
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 5, in <module>
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 5, in <module>
    from encoder import inference as encoder
    from encoder import inference as encoder
    from synthesizer.preprocess import preprocess_dataset
    from encoder import inference as encoder
  File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder import inference as encoder
    from encoder import inference as encoder
  File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
  File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 5, in <module>
  File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
    from encoder import inference as encoder
    from encoder.model import SpeakerEncoder
  File "C:\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
  File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
  File "C:\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
    from encoder.model import SpeakerEncoder
    from torch.nn.utils import clip_grad_norm_
  File "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\__init__.py", line 123, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\__init__.py", line 123, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\__init__.py", line 123, in <module>
  File "C:\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    raise err
    raise err
  File "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\__init__.py", line 123, in <module>
    raise err
  File "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\__init__.py", line 123, in <module>
  File "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\__init__.py", line 123, in <module>
    from torch.nn.utils import clip_grad_norm_
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
OSError: [WinError 1455] The paging file is too small for this operation to complete.  Error loading "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
    raise err
    raise err
  File "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\__init__.py", line 123, in <module>
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
C:\Real-Time-Voice-Cloning-master\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
LibriSpeech: 100%|███████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.98speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "C:\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 49, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence
```

I tried [this method](https://github.com/Spandan-Madan/Pytorch_fine_tuning_Tutorial/issues/10#issuecomment-768135516) and it didn't help.

I use Windows OS and I only have 450GB of free space left on my SSD and RAM is 8 GB. Can't I do something about it?

**Comment by blue-fish** [comment]
This may help: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/669#issuecomment-781130738

**Comment by blue-fish** [comment]
"The paging file is too small" is not the relevant error message. The problem is that it is not finding any wav files. It looks like you're trying to use a custom dataset. Make sure your dataset folder has this hierarchy. You might be missing the "book" directory. https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538

**Comment by blue-fish** [comment]
We should make the error message more informative if no audio files are detected.

**Comment by ks-sav** [comment]
I just downloaded and unzipped LibriSpeech/train-clean-100, I didn't think there would be any problems with it. Perhaps the problem is also what is used there .flac instead .wav? 
![image](https://user-images.githubusercontent.com/52282778/110200322-5e634b00-7e6e-11eb-9f8e-6e3cf8759438.png)

**Comment by blue-fish** [comment]
It's failing because it expects each audio file to have a text transcript when you specify `--no_alignments`. You'll need alignment files for LibriSpeech. This is metadata that relates each word in the transcript to a segment of audio. The LibriSpeech recordings are too long, so we split them into shorter recordings. The alignments are used to create a transcript for each segment. Follow the directions in our [training documentation](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training) to get the alignment files.

Another option is to download train-clean-100 from LibriTTS. That dataset does not require alignments because the utterances are already split and the transcript files are provided. Preprocess it with the `--datasets_name LibriTTS --no_alignments` options.

**Comment by ks-sav** [comment]
Thanks! It works with LibriTTS! And I'm starting to figure out how everything works. I want to make a Russian model, I hope everything will work out

**Comment by MuhammadWaqar621** [comment]
I'm facing the same issue. what is the solution for this one?
  print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
