### ISSUE TITLE
Can't start demo_cli or demo_toolbox.py

### ISSUE THREAD

**Issue by t0g3pii** [CorentinJ/Real-Time-Voice-Cloning#706]
C:\Users\n-har\Desktop\deepaudio>python demo_cli.py
> Traceback (most recent call last):
  File "demo_cli.py", line 4, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\n-har\Desktop\deepaudio\synthesizer\inference.py", line 1, in <module>
    import torch
  File "C:\Users\n-har\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden

C:\Users\n-har\Desktop\deepaudio>python` demo_toolbox.py
> Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\n-har\Desktop\deepaudio\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\n-har\Desktop\deepaudio\toolbox\ui.py", line 2, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "C:\Users\n-har\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "C:\Users\n-har\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\backends\backend_qt5.py", line 16, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\n-har\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "C:\Users\n-har\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\backends\qt_compat.py", line 177, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding

PIP Freeze:
> appdirs==1.4.4
audioread==2.1.9
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
cycler==0.10.0
decorator==4.4.2
dill==0.3.3
ffmpeg==1.4
future==0.18.2
idna==2.10
inflect==5.3.0
joblib==1.0.1
jsonpatch==1.32
jsonpointer==2.1
kiwisolver==1.3.1
librosa==0.8.0
llvmlite==0.36.0
matplotlib==3.3.4
multiprocess==0.70.11.1
numba==0.53.0
numpy==1.19.3
packaging==20.9
Pillow==8.1.2
pooch==1.3.0
pycparser==2.20
pynndescent==0.5.2
pyparsing==2.4.7
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1
python-dateutil==2.8.1
pyzmq==22.0.3
requests==2.25.1
resampy==0.2.2
scikit-learn==0.24.1
scipy==1.6.1
six==1.15.0
sounddevice==0.4.1
SoundFile==0.10.3.post1
threadpoolctl==2.1.0
torch==1.5.1+cpu
torchfile==0.1.0
torchvision==0.6.1+cpu
tornado==6.1
tqdm==4.59.0
typing-extensions==3.7.4.3
umap-learn==0.5.1
Unidecode==1.2.0
urllib3==1.26.4
visdom==0.1.8.9
websocket-client==0.58.0

Using Windows 10 with Python 3.7.9 - Did i missed something?

**Comment by t0g3pii** [comment]
Solved it by using this: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
