### ISSUE TITLE
ImportError: Failed to import any qt binding

### ISSUE THREAD

**Issue by 32r81b** [CorentinJ/Real-Time-Voice-Cloning#733]
I face the error when run demo_toolbox.py:

```
(venv2) C:\Users\dev_user\PycharmProjects\Real-Time-Voice-Cloning>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\dev_user\PycharmProjects\Real-Time-Voice-Cloning\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\dev_user\PycharmProjects\Real-Time-Voice-Cloning\toolbox\ui.py", line 2, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "C:\Users\dev_user\PycharmProjects\Real-Time-Voice-Cloning\venv2\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "C:\Users\dev_user\PycharmProjects\Real-Time-Voice-Cloning\venv2\lib\site-packages\matplotlib\backends\backend_qt5.py", line 13, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\dev_user\PycharmProjects\Real-Time-Voice-Cloning\venv2\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "C:\Users\dev_user\PycharmProjects\Real-Time-Voice-Cloning\venv2\lib\site-packages\matplotlib\backends\qt_compat.py", line 179, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

Windows 10
Python 3.7.1
pip 21.0.1
"pip freeze" result:
appdirs==1.4.4
audioread==2.1.9
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
cycler==0.10.0
decorator==5.0.6
dill==0.3.3
idna==2.10
inflect==5.3.0
joblib==1.0.1
jsonpatch==1.32
jsonpointer==2.1
kiwisolver==1.3.1
librosa==0.8.0
llvmlite==0.36.0
matplotlib==3.4.1
multiprocess==0.70.11.1
numba==0.53.1
numpy==1.19.3
packaging==20.9
Pillow==8.2.0
pooch==1.3.0
pycparser==2.20
pynndescent==0.5.2
pyparsing==2.4.7
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1
python-dateutil==2.8.1
pyzmq==22.0.3
requests==2.25.1
resampy==0.2.2
scikit-learn==0.24.1
scipy==1.6.2
six==1.15.0
sounddevice==0.4.1
SoundFile==0.10.3.post1
threadpoolctl==2.1.0
torch==1.8.1+cpu
torchaudio==0.8.1
torchfile==0.1.0
torchvision==0.9.1+cpu
tornado==6.1
tqdm==4.60.0
typing-extensions==3.7.4.3
umap-learn==0.5.1
Unidecode==1.2.0
urllib3==1.26.4
visdom==0.1.8.9
websocket-client==0.58.0

**Comment by blue-fish** [comment]
Please try following these Windows 10 setup instructions verbatim and see if you still get this issue. https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

**Comment by blue-fish** [comment]
Reopen this issue if you've followed the above instructions and you still have this problem.
