### ISSUE TITLE
Failed to run demo_toolbox

### ISSUE THREAD

**Issue by KiwoNtV** [CorentinJ/Real-Time-Voice-Cloning#742]
If I try to run demo_Toolbox it shows me this error message:

C:\Users\kiwok\Downloads\Real-Time-Voice-Cloning-master\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Traceback (most recent call last):
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\errors.py", line 744, in new_error_context
    yield
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\lowering.py", line 328, in lower_inst
    self.storevar(val, inst.target.name)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\lowering.py", line 1278, in storevar
    raise AssertionError(msg)
AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\kiwok\Downloads\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\kiwok\Downloads\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 15, in <module>
    import umap
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\umap\__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\umap\umap_.py", line 54, in <module>
    from umap.layouts import (
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\umap\layouts.py", line 36, in <module>
    "dim": numba.types.int32,
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\decorators.py", line 221, in wrapper
    disp.compile(sig)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\dispatcher.py", line 111, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler.py", line 395, in _compile_core
    raise e
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler_machinery.py", line 339, in run
    raise patched_exception
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\typed_passes.py", line 463, in run_pass
    NativeLowering().run_pass(state)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\typed_passes.py", line 384, in run_pass
    lower.lower()
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\numba\core\errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Storing i64 to ptr of i32 ('dim'). FE type int32

File "..\..\anaconda3\envs\voice-clone\lib\site-packages\umap\layouts.py", line 52:
def rdist(x, y):
    <source elided>
    result = 0.0
    dim = x.shape[0]
    ^

During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at C:\Users\kiwok\anaconda3\envs\voice-clone\lib\site-packages\umap\layouts.py (52)
(voice-clone) PS C:\Users\kiwok\Downloads\Real-Time-Voice-Cloning-master>

**Comment by blue-fish** [comment]
Please try with a normal python installation, not anaconda. Instructions here for Windows. https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
