### ISSUE TITLE
PATH ISSUE module note recognized after installation

### ISSUE THREAD

**Issue by PsychoJack88** [CorentinJ/Real-Time-Voice-Cloning#747]
Hello I am so far doing good with the installation but finally when ready to start it, I receive the error

D:\Real Time Voice Cloning - Copy\Real-Time-Voice-Cloning-master>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\Real Time Voice Cloning - Copy\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "D:\Real Time Voice Cloning - Copy\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 6, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "D:\Real Time Voice Cloning - Copy\Real-Time-Voice-Cloning-master\encoder\inference.py", line 3, in <module>
    from encoder.audio import preprocess_wav   # We want to expose this function from here
  File "D:\Real Time Voice Cloning - Copy\Real-Time-Voice-Cloning-master\encoder\audio.py", line 7, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'

The strange thing is that when prompted for librosa or to install librosa (specifically I perform a pip install) librosa is already installed. I believe this is simply a path issue because I have a dual hard drive setup. How exactly do I go about pathing the file to recognize librosa since the demo toolbox simply can't find the librosa. If possible can you maybe use imagery since I don't want to demand too much of your time, especially since you developed this amazing piece of software. Thank you for your diligence as well as pro level programming.

**Comment by blue-fish** [comment]
You will want to use a Python virtual environment (venv) to mitigate the path issues. I wrote up the Windows 10 setup instructions here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542 . Sorry, it doesn't have screenshots. Maybe someone will make a video of it.
