### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by jasonkhanlar** [CorentinJ/Real-Time-Voice-Cloning#760]
Last year I had a working copy of this software running in Archlinux, but after various system updates, trying to run this software again, I see this error:
```
$ python demo_cli.py 
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/mnt/media/Real-Time-Voice-Cloning/demo_cli.py", line 4, in <module>
    from synthesizer.inference import Synthesizer
  File "/mnt/media/Real-Time-Voice-Cloning/synthesizer/inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "/mnt/media/Real-Time-Voice-Cloning/synthesizer/tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "/mnt/media/Real-Time-Voice-Cloning/synthesizer/models/__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "/mnt/media/Real-Time-Voice-Cloning/synthesizer/models/tacotron.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "/usr/lib/python3.9/site-packages/tensorflow/python/data/__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "/usr/lib/python3.9/site-packages/tensorflow/python/data/experimental/__init__.py", line 99, in <module>
    from tensorflow.python.data.experimental import service
  File "/usr/lib/python3.9/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 140, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/usr/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 25, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/usr/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "/usr/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "/usr/lib/python3.9/site-packages/tensorflow/python/data/util/nest.py", line 40, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/usr/lib/python3.9/site-packages/tensorflow/python/framework/sparse_tensor.py", line 28, in <module>
    from tensorflow.python.framework import constant_op
  File "/usr/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "/usr/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "/usr/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py", line 32, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
        () -> handle

```

Any ideas what I need to do?

**Comment by Calhoun-z** [comment]
@jasonkhanlar just had a very similar issue trying to use python 3.9 with this project. Fixed it by install 3.7 and running the setup on that. What version is your python?

**Comment by Calhoun-z** [comment]
Just realized it's right there in the log "python3.9". Let me know if you would like my steps for setting up a seperate 3.7 install along side your current 3.9(Did this on manjaro).

**Comment by blue-fish** [comment]
Hi @jasonkhanlar , you should use Python 3.7 as @Calhoun-z suggests.
