### ISSUE TITLE
Could not find any synthesizer weights under synthesizer/saved_models/pretrained/taco_pretrained

### ISSUE THREAD

**Issue by cecilbowen** [CorentinJ/Real-Time-Voice-Cloning#796]
When I hit "Synthesize and Vocode" after loading an audio file, I get the following error:
```
Traceback (most recent call last):
  File "D:\Downloads\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 89, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "D:\Downloads\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 172, in synthesize
    self.synthesizer = Synthesizer(checkpoints_dir, low_mem=self.low_mem)
  File "D:\Downloads\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 37, in __init__
    raise Exception("Could not find any synthesizer weights under %s" % checkpoints_dir)
Exception: Could not find any synthesizer weights under synthesizer\saved_models\pretrained\taco_pretrained
```

I have downloaded the pretrained models.
```
enc_models_dir:   encoder\saved_models
syn_models_dir:   synthesizer\saved_models
voc_models_dir:   vocoder\saved_models
```

My synthesizer directory does not have a "taco_pretrained" folder, only "synthesizer/saved_models/pretrained/pretrained.pt".

This is the closest issue I have found, but it does not have a solution for me (I am running on Windows): https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/310

**Comment by cecilbowen** [comment]
I was using the wrong pretrained models.  These are the correct ones for my setup: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models/2cd3887f379d4921b193214973b463043efa5c23
