### ISSUE TITLE
The dataset consists of 0 utterances

### ISSUE THREAD

**Issue by FreeSlave** [CorentinJ/Real-Time-Voice-Cloning#798]
I've downloaded the `test-clean` dataset from http://www.openslr.org/12/ and unpacked it into the root of the git repo.
I'm trying to start a synthesizer training on this data:

```
python synthesizer_preprocess_audio.py . --subfolders test-clean
```

Getting output:

```
Arguments:
    datasets_root:   .
    out_dir:         SV2TTS/synthesizer
    n_processes:     None
    skip_existing:   False
    hparams:         
    no_alignments:   False
    datasets_name:   LibriSpeech
    subfolders:      test-clean

Using data from:
    LibriSpeech/test-clean
LibriSpeech: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 4701.61speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "/home/freeslave/git_projects/Real-Time-Voice-Cloning/synthesizer/preprocess.py", line 49, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence
```

Is there something wrong with my setup?

**Comment by pilnyjakub** [comment]
You will need to download LibriSpeech alignments from Training Wiki.

**Comment by FreeSlave** [comment]
@pilnyjakub thanks. Somehow I overlooked that alignments are also mandatory.
