### ISSUE TITLE
unable to run demo_toolbox.py (%1 is not a valid Win32 application)

### ISSUE THREAD

**Issue by catfishjw** [CorentinJ/Real-Time-Voice-Cloning#801]
I have been attempting to run the demo toolbox for the past few days according to the instructions given for windows. I have come across this issue and after searching through other issues in this repo and others, cannot find a solution. I have tried:

- deleting conflicting versions (specifically anaconda) and resetting PATH
- reinstalling python
- uninstalling and reinstalling numpy and matplotlib
At this point any advice would be helpful. 
The Error:
`(venv) C:\Real-Time-Voice-Cloning-master>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 6, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "C:\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Real-Time-Voice-Cloning-master\encoder\model.py", line 3, in <module>
    from scipy.interpolate import interp1d
  File "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Real-Time-Voice-Cloning-master\venv\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\james\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application`

**Comment by catfishjw** [comment]
Image of terminal because I cant figure out this formatting
![terminalVoiceClone](https://user-images.githubusercontent.com/39639229/126004511-8debb5f2-ae63-4eb7-84fc-5e3847fd16b6.png)

**Comment by catfishjw** [comment]
Solved, ended up having to reinstall most of the libraries that were supposed to be installed by requirements.txt. I don't know how this problem came about, but reinstalling various libraries solved this error and every error after it.
