### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (1440x512 and 320x128) TRAINING SYNTHETIZER

### ISSUE THREAD

**Issue by ireneb612** [CorentinJ/Real-Time-Voice-Cloning#852]
Can someone help me with this issue?

Traceback (most recent call last):
  File "D:\PycharmProjects\Realtime\synthesizer_train.py", line 35, in <module>
    train(**vars(args))
  File "D:\PycharmProjects\Realtime\synthesizer\train.py", line 178, in train
    m1_hat, m2_hat, attention, stop_pred = model(texts, mels, embeds)
  File "D:\PycharmProjects\Realtime\venv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PycharmProjects\Realtime\synthesizer\models\tacotron.py", line 387, in forward
    encoder_seq_proj = self.encoder_proj(encoder_seq)
  File "D:\PycharmProjects\Realtime\venv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PycharmProjects\Realtime\venv\lib\site-packages\torch\nn\modules\linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\PycharmProjects\Realtime\venv\lib\site-packages\torch\nn\functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1440x512 and 320x128)

**Comment by blue-fish** [comment]
What modifications have you made to `encoder/model.py` and `synthesizer/hparams.py`?

**Comment by ireneb612** [comment]
@blue-fish I have changed only the hparams.
this:
 speaker_embedding_size = 64,               # Dimension for the speaker embedding
and this:
 tts_cleaner_names = ["transliteration_cleaners"]

About the encodere i have used the pretrained models!

**Comment by ireneb612** [comment]
@blue-fish okkey I changed back to 256 the speaker embeds and it worked
