### ISSUE TITLE
vocoder precprocess

### ISSUE THREAD

**Issue by ireneb612** [CorentinJ/Real-Time-Voice-Cloning#875]
This error comes out when I try to run the vocoder_preprocess.py, Do you know why?

Found 161835 samples
  0%|                                                                                                                                                           | 0/10115 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "D:\PycharmProjects\Realtime\vocoder_preprocess.py", line 59, in <module>
    run_synthesis(args.in_dir, args.out_dir, args.model_dir, modified_hp)
  File "D:\PycharmProjects\Realtime\synthesizer\synthesize.py", line 86, in run_synthesis
    _, mels_out, _ = model(texts, mels, embeds)
ValueError: too many values to unpack (expected 3)

**Comment by blue-fish** [comment]
You are using an older version of synthesize.py. Please pull the latest code from the repo and try again.
