### ISSUE TITLE
preprocess_audio.py ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by Dannypeja** [CorentinJ/Real-Time-Voice-Cloning#957]
Any Ideas what this failure could be about doing preprocess_audio.py? 

```python
Arguments:
    datasets_root:   /Users/dape/SWAL/Datasets
    out_dir:         /Users/dape/SWAL/Datasets/SV2TTS/synthesizer
    n_processes:     None
    skip_existing:   False
    hparams:         
    no_alignments:   True
    datasets_name:   
    subfolders:      de_DE/by_book/female,de_DE/by_book/male,de_DE/by_book/mix/
    wav_dir:         True

Using data from:
    /Users/dape/SWAL/Datasets/de_DE/by_book/female
    /Users/dape/SWAL/Datasets/de_DE/by_book/male
    /Users/dape/SWAL/Datasets/de_DE/by_book/mix
Speaker dirs: [PosixPath('/Users/dape/SWAL/Datasets/de_DE/by_book/female/eva_k'), PosixPath('/Users/dape/SWAL/Datasets/de_DE/by_book/female/ramona_deininger'), PosixPath('/Users/dape/SWAL/Datasets/de_DE/by_book/female/angela_merkel'), PosixPath('/Users/dape/SWAL/Datasets/de_DE/by_book/female/rebecca_braunert_plunkett'), PosixPath('/Users/dape/SWAL/Datasets/de_DE/by_book/male/karlsson'), PosixPath('/Users/dape/SWAL/Datasets/de_DE/by_book/mix/unnkown')]
  0%|                                                                                                                               | 0/6 [00:00<?, ?speakers/s]Speaker metadata: []
Speaker metadata: []
Speaker metadata: []
Speaker metadata: []
Speaker metadata: []
Speaker metadata: []
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 140.23speakers/s]
Medata file: /Users/dape/SWAL/Datasets/SV2TTS/synthesizer/train.txt
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 60, in <module>
    preprocess_dataset(**vars(args))
  File "/Users/dape/SWAL/Real-Time-Voice-Cloning-German/synthesizer/preprocess.py", line 54, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence
```

**Comment by Dannypeja** [comment]
Nevermind, the code was made for windows filepaths with double \\. 
I needed to replace it with single /.
