### ISSUE TITLE
Not sure if my Directory is wrong or i'm missing something but i get hit by this.What am i doing wrong? Thanks in advance :)

### ISSUE THREAD

**Issue by santaonholidays** [CorentinJ/Real-Time-Voice-Cloning#964]
ERROR: Command errored out with exit status 1:
   command: 'D:\python\python.exe' 'D:\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\yasin\AppData\Local\Temp\tmp3hdlg1od'
       cwd: C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4
  Complete output (135 lines):
  setup.py:66: RuntimeWarning: NumPy 1.20.3 may not yet support Python 3.10.
    warnings.warn(
  Running from numpy source directory.
  setup.py:485: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
    run_build = parse_setuppy_commands()
  Processing numpy/random\_bounded_integers.pxd.in
  Processing numpy/random\bit_generator.pyx
  Processing numpy/random\mtrand.pyx
  Processing numpy/random\_bounded_integers.pyx.in
  Processing numpy/random\_common.pyx
  Processing numpy/random\_generator.pyx
  Processing numpy/random\_mt19937.pyx
  Processing numpy/random\_pcg64.pyx
  Processing numpy/random\_philox.pyx
  Processing numpy/random\_sfc64.pyx
  Cythonizing sources
  Could not locate executable g77
  Could not locate executable f77
  Could not locate executable ifort
  Could not locate executable ifl
  Could not locate executable f90
  Could not locate executable DF
  Could not locate executable efl
  Could not locate executable gfortran
  Could not locate executable f95
  Could not locate executable g95
  Could not locate executable efort
  Could not locate executable efc
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
  C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\system_info.py:1989: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\system_info.py:1989: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\system_info.py:1989: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
  C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\system_info.py:1849: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\system_info.py:1849: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  non-existing path in 'numpy\\distutils': 'site.cfg'
  running dist_info
  running build_src
  creating build
  creating build\src.win-amd64-3.10
  creating build\src.win-amd64-3.10\numpy
  creating build\src.win-amd64-3.10\numpy\distutils
  Traceback (most recent call last):
    File "D:\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "D:\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\build_meta.py", line 248, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 513, in <module>
      setup_package()
    File "setup.py", line 505, in setup_package
      setup(**metadata)
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\core.py", line 169, in setup
      return old_setup(**new_attr)
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 31, in run
      egg_info.run()
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\command\egg_info.py", line 24, in run
      self.run_command("build_src")
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\command\build_src.py", line 144, in run
      self.build_sources()
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\command\build_src.py", line 155, in build_sources
      self.build_library_sources(*libname_info)
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\command\build_src.py", line 288, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\command\build_src.py", line 378, in generate_sources
      source = func(extension, build_dir)
    File "numpy\core\setup.py", line 671, in get_mathlib_info
      st = config_cmd.try_link('int main(void) { return 0;}')
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 243, in try_link
      self._link(body, headers, include_dirs,
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\command\config.py", line 162, in _link
      return self._wrap_method(old_config._link, lang,
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\command\config.py", line 96, in _wrap_method
      ret = mth(*((self,)+args))
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 137, in _link
      (src, obj) = self._compile(body, headers, include_dirs, lang)
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\command\config.py", line 105, in _compile
      src, obj = self._wrap_method(old_config._compile, lang,
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\command\config.py", line 96, in _wrap_method
      ret = mth(*((self,)+args))
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
      self.compiler.compile([src], include_dirs=include_dirs)
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 401, in compile
      self.spawn(args)
    File "C:\Users\yasin\AppData\Local\Temp\pip-build-env-6pkcd6kp\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 505, in spawn
      return super().spawn(cmd, env=env)
    File "C:\Users\yasin\AppData\Local\Temp\pip-install-594l2te2\numpy_6377a46b864645e683fccdd25c76f1f4\numpy\distutils\ccompiler.py", line 90, in <lambda>
      m = lambda self, *args, **kw: func(self, *args, **kw)
  TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f3/1f/fe9459e39335e7d0e372b5e5dcd60f4381d3d1b42f0b9c8222102ff29ded/numpy-1.20.3.zip#sha256=e55185e51b18d788e49fe8305fd73ef4470596b33fc2c1ceb304566b99c71a69 (from https://pypi.org/simple/numpy/) (requires-python:>=3.7). Command errored out with exit status 1: 'D:\python\python.exe' 'D:\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\yasin\AppData\Local\Temp\tmp3hdlg1od' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement numpy==1.20.3 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0rc1, 1.20.0rc2, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0rc1, 1.21.0rc2, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.22.0rc1, 1.22.0rc2, 1.22.0rc3)
ERROR: No matching distribution found for numpy==1.20.3

**Comment by CorentinJ** [comment]
Your python version is too recent. You can should get away with it by unpinning the dependencies. I'll add a note in the readme
