### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by samson80** [CorentinJ/Real-Time-Voice-Cloning#97]
File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\users\xxx\AppData\Local\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\xxx\AppData\Local\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 5, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "C:\Users\xx\AppData\Local\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Users\xx\AppData\Local\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
ModuleNotFoundError: No module named 'torch'

I can't seem to find anyway to install torch with windows 10.  

I have pip install torch and receive this error 

  ERROR: Command errored out with exit status 1:
   command: 'c:\users\xx\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-ugvuvz4g\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-ugvuvz4g\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\xx\AppData\Local\Temp\pip-wheel-y1y532al' --python-tag cp37
       cwd: C:\Users\xx\AppData\Local\Temp\pip-install-ugvuvz4g\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\xxxxx\AppData\Local\Temp\pip-install-ugvuvz4g\torch\setup.py", line 265, in <module>
      description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    File "c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\xxxx\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\xxxx\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\xxx\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\xx\appdata\local\programs\python\python37\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "c:\users\xxx\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\xxxx\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\xxxx\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\xxx\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\xxxxxx\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\xxxx\AppData\Local\Temp\pip-install-ugvuvz4g\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\xx\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-ugvuvz4g\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-ugvuvz4g\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\xx\AppData\Local\Temp\pip-install-ugvuvz4g\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: torch
  Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xxx\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-ugvuvz4g\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxxx\\AppData\\Local\\Temp\\pip-install-ugvuvz4g\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xx\AppData\Local\Temp\pip-record-x9boybwy\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\xx\AppData\Local\Temp\pip-install-ugvuvz4g\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-ugvuvz4g\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "c:\users\xx\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\xx\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\xx\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\xx\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\xx\AppData\Local\Temp\pip-install-ugvuvz4g\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\users\xx\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\xx\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\xx\AppData\Local\Temp\pip-install-ugvuvz4g\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\xx\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-ugvuvz4g\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-install-ugvuvz4g\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xx\AppData\Local\Temp\pip-record-x9boybwy\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by CorentinJ** [comment]
You need to install torch separately, as is said in the readme.

https://pytorch.org/get-started/locally/
