### ISSUE TITLE
swedish models

### ISSUE THREAD

**Issue by Archviz360** [CorentinJ/Real-Time-Voice-Cloning#984]
since blue fish is gone and the page where the installation instruction with Swedish models are gone and even all dropbox is gone I wonder if there are some others here that might have it and could upload it again?? since I'm don't understand how to train or even have the right pc specs and time I would appreciate if someone with all the files including Swedish model could upload or contact me personally and send the files.

**Comment by raccoonML** [comment]
@Archviz360 I spent a few hours getting the Swedish model to work and collected all required files at this link. The setup is a little tricky because it uses tensorflow 1.15. Enjoy!
https://github.com/raccoonML/Real-Time-Voice-Cloning/releases/tag/Swedish-1

**Comment by ireneb612** [comment]
@raccoonML I was wondering if you changed the symbols.py for swedish! Because I have to change che _characters  for italian but it gives me error:

size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([66, 512]) from checkpoint, the shape in current model is torch.Size([74, 512])

Wich models did you start off? did you train synthesizer from scratch?

**Comment by raccoonML** [comment]
The Swedish pretrained synthesizer model is not my work, but it is trained from scratch and uses the English speaker encoder as ViktorAlm explains in #257 . I made these updates to symbols.py: https://github.com/raccoonML/Real-Time-Voice-Cloning/commit/b358eb5d8f64a00cfee32a0e46ce4122355f7d41

Updating the symbol list will require training a new synthesizer model from scratch.

**Comment by ireneb612** [comment]
@raccoonML Hi! Yes I started retraining the synthétiser, I was wondering how you felt with NUMBERS because I know there are libraries that convert digits to English numbers but not other languages! How did you deal? Thank you

**Comment by raccoonML** [comment]
Here is an idea for how to deal with numbers in other languages. Code not available at this time. https://github.com/sveneschlbeck/Multi-Language-RTVC/issues/13#issuecomment-1001240560

**Comment by ireneb612** [comment]
@raccoonML Thank you! yes one idea was to then translate! :)

**Comment by ireneb612** [comment]
@raccoonML Sorry for bothering, When retraining the synthetizer I also need to re do the preprocessing of the dataset with the new symbols right? Because I retrained on and older pre processed dataset and it is not pronouncing the new letters :(

**Comment by Archviz360** [comment]
PS C:\Users\dacia\OneDrive\Skrivbord\RTVC-Swedish> python demo_toolbox.py
2022-08-19 21:21:27.615361: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2022-08-19 21:21:27.615492: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\dacia\OneDrive\Skrivbord\RTVC-Swedish\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\dacia\OneDrive\Skrivbord\RTVC-Swedish\toolbox\ui.py", line 15, in <module>
    import umap
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\umap\__init__.py", line 7, in <module>
    from .parametric_umap import ParametricUMAP
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\umap\parametric_umap.py", line 14, in <module>
    import tensorflow as tf
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\core\framework\node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\core\framework\tensor_shape_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "C:\Users\dacia\AppData\Local\Programs\Python\Python37\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

how do i fix this?
